/* Generated by Nim Compiler v1.7.1 */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct tyObject_PDispatchercolonObjectType___mNiwh37MfaAP9cG4kqT6kpg tyObject_PDispatchercolonObjectType___mNiwh37MfaAP9cG4kqT6kpg;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_PDispatcherBasecolonObjectType___YNzlM8oq8NLlO720L2VFMw tyObject_PDispatcherBasecolonObjectType___YNzlM8oq8NLlO720L2VFMw;
typedef struct RootObj RootObj;
typedef struct tyObject_HeapQueue__mgfFdry9aKsRMW9au5u9bSpOQ tyObject_HeapQueue__mgfFdry9aKsRMW9au5u9bSpOQ;
typedef struct tySequence__oKfdUHDH0q5oP14wOM6kug tySequence__oKfdUHDH0q5oP14wOM6kug;
typedef struct tyObject_Deque__NuwIXbomwb0PtcywOgXRnA tyObject_Deque__NuwIXbomwb0PtcywOgXRnA;
typedef struct tySequence__aNpJjaoUowCQc7fBn3wtDQ tySequence__aNpJjaoUowCQc7fBn3wtDQ;
typedef struct tyTuple__5aoVPIWYzahUyBc9bMm0M5w tyTuple__5aoVPIWYzahUyBc9bMm0M5w;
typedef struct tyObject_MonoTime__FEvFMlkqJiSSGVO6HgTv8w tyObject_MonoTime__FEvFMlkqJiSSGVO6HgTv8w;
typedef struct tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_SelectorImpl__jkoZicTBtYdKkYck5SFJEQ tyObject_SelectorImpl__jkoZicTBtYdKkYck5SFJEQ;
typedef struct tySequence__5L9b5Ztm9adPEys1vE9cEPQJA tySequence__5L9b5Ztm9adPEys1vE9cEPQJA;
typedef struct tyObject_SelectorKey__561GPxg10TdJiEAAWoraPw tyObject_SelectorKey__561GPxg10TdJiEAAWoraPw;
typedef struct tyObject_AsyncData__hOYUN4IOpj9adMwn6W7S2VA tyObject_AsyncData__hOYUN4IOpj9adMwn6W7S2VA;
typedef struct tySequence__mqHCvcswroDetkzsL3ixtg tySequence__mqHCvcswroDetkzsL3ixtg;
typedef struct tyTuple__JfHvHzMrhKkWAUvQKe0i1A tyTuple__JfHvHzMrhKkWAUvQKe0i1A;
typedef struct tyObject_Env_asyncdispatchdotnim_asyncdispatch___diB2NTuAIWY0FO9c5IUJRGg tyObject_Env_asyncdispatchdotnim_asyncdispatch___diB2NTuAIWY0FO9c5IUJRGg;
typedef NU8 tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc__ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
NI align;
tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc__ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct RootObj {
TNimType* m_type;
};
struct tyObject_HeapQueue__mgfFdry9aKsRMW9au5u9bSpOQ {
tySequence__oKfdUHDH0q5oP14wOM6kug* data;
};
struct tyObject_Deque__NuwIXbomwb0PtcywOgXRnA {
tySequence__aNpJjaoUowCQc7fBn3wtDQ* data;
NI head;
NI tail;
NI count;
NI mask;
};
struct tyObject_PDispatcherBasecolonObjectType___YNzlM8oq8NLlO720L2VFMw {
  RootObj Sup;
tyObject_HeapQueue__mgfFdry9aKsRMW9au5u9bSpOQ timers;
tyObject_Deque__NuwIXbomwb0PtcywOgXRnA callbacks;
};
struct tyObject_MonoTime__FEvFMlkqJiSSGVO6HgTv8w {
NI64 ticks;
};
struct tyTuple__5aoVPIWYzahUyBc9bMm0M5w {
tyObject_MonoTime__FEvFMlkqJiSSGVO6HgTv8w Field0;
tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w* Field1;
};
struct TGenericSeq {
NI len;
NI reserved;
};
struct tyObject_PDispatchercolonObjectType___mNiwh37MfaAP9cG4kqT6kpg {
  tyObject_PDispatcherBasecolonObjectType___YNzlM8oq8NLlO720L2VFMw Sup;
tyObject_SelectorImpl__jkoZicTBtYdKkYck5SFJEQ* selector;
};
struct tyObject_SelectorImpl__jkoZicTBtYdKkYck5SFJEQ {
int epollFD;
NI maxFD;
NI numFD;
tySequence__5L9b5Ztm9adPEys1vE9cEPQJA* fds;
NI count;
};
typedef NU32 tySet_tyEnum_Event__nI40bZzTyYVrl763dZ9aHDg;
struct tyObject_AsyncData__hOYUN4IOpj9adMwn6W7S2VA {
tySequence__mqHCvcswroDetkzsL3ixtg* readList;
tySequence__mqHCvcswroDetkzsL3ixtg* writeList;
};
struct tyObject_SelectorKey__561GPxg10TdJiEAAWoraPw {
NI ident;
tySet_tyEnum_Event__nI40bZzTyYVrl763dZ9aHDg events;
NI param;
tyObject_AsyncData__hOYUN4IOpj9adMwn6W7S2VA data;
};
struct tyTuple__JfHvHzMrhKkWAUvQKe0i1A {
void* Field0;
tyObject_Env_asyncdispatchdotnim_asyncdispatch___diB2NTuAIWY0FO9c5IUJRGg* Field1;
};
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClP_0) (int fd_0, void* ClE_0);
void* ClE_0;
} tyProc__kbFLS7lxxUPzrFcbZuGUzQ;
typedef N_NIMCALL_PTR(void, tyProc__T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (void* ClE_0);
void* ClE_0;
} tyProc__HzVCwACFYM9cx9aV62PdjtuA;
struct tySequence__oKfdUHDH0q5oP14wOM6kug {
  TGenericSeq Sup;
  tyTuple__5aoVPIWYzahUyBc9bMm0M5w data[SEQ_DECL_SIZE];
};
struct tySequence__mqHCvcswroDetkzsL3ixtg {
  TGenericSeq Sup;
  tyProc__kbFLS7lxxUPzrFcbZuGUzQ data[SEQ_DECL_SIZE];
};
struct tySequence__5L9b5Ztm9adPEys1vE9cEPQJA {
  TGenericSeq Sup;
  tyObject_SelectorKey__561GPxg10TdJiEAAWoraPw data[SEQ_DECL_SIZE];
};
struct tySequence__aNpJjaoUowCQc7fBn3wtDQ {
  TGenericSeq Sup;
  tyProc__HzVCwACFYM9cx9aV62PdjtuA data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tySequence__oKfdUHDH0q5oP14wOM6kug)(void* p, NI op);
static N_NIMCALL(void, Marker_tySequence__mqHCvcswroDetkzsL3ixtg)(void* p, NI op);
static N_NIMCALL(void, Marker_tySequence__5L9b5Ztm9adPEys1vE9cEPQJA)(void* p, NI op);
static N_NIMCALL(void, Marker_tyRef__Y5hK0M9cL3lXwccEV9cgR9cQw)(void* p, NI op);
static N_NIMCALL(void, Marker_tyRef__OGnyBMU9csFmaJm9bh2uOQiQ)(void* p, NI op);
static N_NIMCALL(void, TM__gfe9a52b5gJr8GSrnr883iA_9)(void);
N_LIB_PRIVATE N_NIMCALL(void, nimRegisterThreadLocalMarker)(tyProc__T4eqaYlFJYZUv9aG9b1TV0bQ markerProc);
extern TNimType NTIrootobj__ytyiCJqK439aF9cIibuRVpAg_;
N_LIB_PRIVATE TNimType NTIpdispatcherbase58objecttype__YNzlM8oq8NLlO720L2VFMw_;
N_LIB_PRIVATE TNimType NTIheapqueue__mgfFdry9aKsRMW9au5u9bSpOQ_;
N_LIB_PRIVATE TNimType NTItupleLfinishat58monotime_fut58futureLsystemOvoidTT__5aoVPIWYzahUyBc9bMm0M5w_;
extern TNimType NTImonotime__FEvFMlkqJiSSGVO6HgTv8w_;
extern TNimType NTIfuture__TjokxNjmnZmr9bygVDVC9bvg_;
N_LIB_PRIVATE TNimType NTIseqLtupleLfinishat58monotime_fut58futureLsystemOvoidTTT__oKfdUHDH0q5oP14wOM6kug_;
N_LIB_PRIVATE TNimType NTIdeque__NuwIXbomwb0PtcywOgXRnA_;
extern TNimType NTIseqLprocLTLOclosure_gcsafeOTT__aNpJjaoUowCQc7fBn3wtDQ_;
extern TNimType NTIint__rR5Bzr1D5krxoo1NcNyeMA_;
N_LIB_PRIVATE TNimType NTIpdispatcher58objecttype__mNiwh37MfaAP9cG4kqT6kpg_;
N_LIB_PRIVATE TNimType NTIselectorimpl__jkoZicTBtYdKkYck5SFJEQ_;
extern TNimType NTIcint__nlCscttRCss70IBTyuBqnA_;
N_LIB_PRIVATE TNimType NTIselectorkey__561GPxg10TdJiEAAWoraPw_;
extern TNimType NTIsetLeventT__YIRsZrDT89buh37M5yeUgng_;
N_LIB_PRIVATE TNimType NTIasyncdata__hOYUN4IOpj9adMwn6W7S2VA_;
N_LIB_PRIVATE TNimType NTIcallback__kbFLS7lxxUPzrFcbZuGUzQ_;
extern TNimType NTIpointer__vr5DoT1jILTGdRlYv1OYpw_;
extern TNimType NTIrefobject__HsJiUUcO9cHBdUCi0HwkSTA_;
N_LIB_PRIVATE TNimType NTIseqLcallbackT__mqHCvcswroDetkzsL3ixtg_;
N_LIB_PRIVATE TNimType NTIseqLselectorkeyLasyncdispatchOasyncdataTT__5L9b5Ztm9adPEys1vE9cEPQJA_;
N_LIB_PRIVATE TNimType NTIselector__Y5hK0M9cL3lXwccEV9cgR9cQw_;
N_LIB_PRIVATE TNimType NTIpdispatcher__OGnyBMU9csFmaJm9bh2uOQiQ_;
N_LIB_PRIVATE NIM_THREADVAR tyObject_PDispatchercolonObjectType___mNiwh37MfaAP9cG4kqT6kpg* gDisp__pureZasyncdispatch_1593;
static N_NIMCALL(void, Marker_tySequence__oKfdUHDH0q5oP14wOM6kug)(void* p, NI op) {
	tySequence__oKfdUHDH0q5oP14wOM6kug* a;
	NI T1_;
	a = (tySequence__oKfdUHDH0q5oP14wOM6kug*)p;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < (a ? a->Sup.len : 0); T1_++) {
	nimGCvisit((void*)a->data[T1_].Field1, op);
	}
}
static N_NIMCALL(void, Marker_tySequence__mqHCvcswroDetkzsL3ixtg)(void* p, NI op) {
	tySequence__mqHCvcswroDetkzsL3ixtg* a;
	NI T1_;
	a = (tySequence__mqHCvcswroDetkzsL3ixtg*)p;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < (a ? a->Sup.len : 0); T1_++) {
	nimGCvisit((void*)a->data[T1_].ClE_0, op);
	}
}
static N_NIMCALL(void, Marker_tySequence__5L9b5Ztm9adPEys1vE9cEPQJA)(void* p, NI op) {
	tySequence__5L9b5Ztm9adPEys1vE9cEPQJA* a;
	NI T1_;
	a = (tySequence__5L9b5Ztm9adPEys1vE9cEPQJA*)p;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < (a ? a->Sup.len : 0); T1_++) {
	nimGCvisit((void*)a->data[T1_].data.readList, op);
	nimGCvisit((void*)a->data[T1_].data.writeList, op);
	}
}
static N_NIMCALL(void, Marker_tyRef__Y5hK0M9cL3lXwccEV9cgR9cQw)(void* p, NI op) {
	tyObject_SelectorImpl__jkoZicTBtYdKkYck5SFJEQ* a;
	a = (tyObject_SelectorImpl__jkoZicTBtYdKkYck5SFJEQ*)p;
	nimGCvisit((void*)(*a).fds, op);
}
static N_NIMCALL(void, Marker_tyRef__OGnyBMU9csFmaJm9bh2uOQiQ)(void* p, NI op) {
	tyObject_PDispatchercolonObjectType___mNiwh37MfaAP9cG4kqT6kpg* a;
	a = (tyObject_PDispatchercolonObjectType___mNiwh37MfaAP9cG4kqT6kpg*)p;
	nimGCvisit((void*)(*a).Sup.timers.data, op);
	nimGCvisit((void*)(*a).Sup.callbacks.data, op);
	nimGCvisit((void*)(*a).selector, op);
}
static N_NIMCALL(void, TM__gfe9a52b5gJr8GSrnr883iA_9)(void) {
	nimGCvisit((void*)gDisp__pureZasyncdispatch_1593, 0);
}
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsNimatslibatspureatsasyncdispatchdotnim_Init000)(void) {
{
	TFrame FR_; FR_.len = 0;

	nimRegisterThreadLocalMarker(TM__gfe9a52b5gJr8GSrnr883iA_9);

}/* preInitProc end */
{
}
}

N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsNimatslibatspureatsasyncdispatchdotnim_DatInit000)(void) {
static TNimNode* TM__gfe9a52b5gJr8GSrnr883iA_2_2[2];
static TNimNode* TM__gfe9a52b5gJr8GSrnr883iA_3_2[2];
static TNimNode* TM__gfe9a52b5gJr8GSrnr883iA_4_5[5];
static TNimNode* TM__gfe9a52b5gJr8GSrnr883iA_5_5[5];
static TNimNode* TM__gfe9a52b5gJr8GSrnr883iA_6_4[4];
static TNimNode* TM__gfe9a52b5gJr8GSrnr883iA_7_2[2];
static TNimNode* TM__gfe9a52b5gJr8GSrnr883iA_8_2[2];
static TNimNode TM__gfe9a52b5gJr8GSrnr883iA_0[31];
NTIpdispatcherbase58objecttype__YNzlM8oq8NLlO720L2VFMw_.size = sizeof(tyObject_PDispatcherBasecolonObjectType___YNzlM8oq8NLlO720L2VFMw);
NTIpdispatcherbase58objecttype__YNzlM8oq8NLlO720L2VFMw_.align = NIM_ALIGNOF(tyObject_PDispatcherBasecolonObjectType___YNzlM8oq8NLlO720L2VFMw);
NTIpdispatcherbase58objecttype__YNzlM8oq8NLlO720L2VFMw_.kind = 17;
NTIpdispatcherbase58objecttype__YNzlM8oq8NLlO720L2VFMw_.base = (&NTIrootobj__ytyiCJqK439aF9cIibuRVpAg_);
TM__gfe9a52b5gJr8GSrnr883iA_2_2[0] = &TM__gfe9a52b5gJr8GSrnr883iA_0[1];
NTIheapqueue__mgfFdry9aKsRMW9au5u9bSpOQ_.size = sizeof(tyObject_HeapQueue__mgfFdry9aKsRMW9au5u9bSpOQ);
NTIheapqueue__mgfFdry9aKsRMW9au5u9bSpOQ_.align = NIM_ALIGNOF(tyObject_HeapQueue__mgfFdry9aKsRMW9au5u9bSpOQ);
NTIheapqueue__mgfFdry9aKsRMW9au5u9bSpOQ_.kind = 18;
NTIheapqueue__mgfFdry9aKsRMW9au5u9bSpOQ_.base = 0;
NTItupleLfinishat58monotime_fut58futureLsystemOvoidTT__5aoVPIWYzahUyBc9bMm0M5w_.size = sizeof(tyTuple__5aoVPIWYzahUyBc9bMm0M5w);
NTItupleLfinishat58monotime_fut58futureLsystemOvoidTT__5aoVPIWYzahUyBc9bMm0M5w_.align = NIM_ALIGNOF(tyTuple__5aoVPIWYzahUyBc9bMm0M5w);
NTItupleLfinishat58monotime_fut58futureLsystemOvoidTT__5aoVPIWYzahUyBc9bMm0M5w_.kind = 18;
NTItupleLfinishat58monotime_fut58futureLsystemOvoidTT__5aoVPIWYzahUyBc9bMm0M5w_.base = 0;
TM__gfe9a52b5gJr8GSrnr883iA_3_2[0] = &TM__gfe9a52b5gJr8GSrnr883iA_0[4];
TM__gfe9a52b5gJr8GSrnr883iA_0[4].kind = 1;
TM__gfe9a52b5gJr8GSrnr883iA_0[4].offset = offsetof(tyTuple__5aoVPIWYzahUyBc9bMm0M5w, Field0);
TM__gfe9a52b5gJr8GSrnr883iA_0[4].typ = (&NTImonotime__FEvFMlkqJiSSGVO6HgTv8w_);
TM__gfe9a52b5gJr8GSrnr883iA_0[4].name = "Field0";
TM__gfe9a52b5gJr8GSrnr883iA_3_2[1] = &TM__gfe9a52b5gJr8GSrnr883iA_0[5];
TM__gfe9a52b5gJr8GSrnr883iA_0[5].kind = 1;
TM__gfe9a52b5gJr8GSrnr883iA_0[5].offset = offsetof(tyTuple__5aoVPIWYzahUyBc9bMm0M5w, Field1);
TM__gfe9a52b5gJr8GSrnr883iA_0[5].typ = (&NTIfuture__TjokxNjmnZmr9bygVDVC9bvg_);
TM__gfe9a52b5gJr8GSrnr883iA_0[5].name = "Field1";
TM__gfe9a52b5gJr8GSrnr883iA_0[3].len = 2; TM__gfe9a52b5gJr8GSrnr883iA_0[3].kind = 2; TM__gfe9a52b5gJr8GSrnr883iA_0[3].sons = &TM__gfe9a52b5gJr8GSrnr883iA_3_2[0];
NTItupleLfinishat58monotime_fut58futureLsystemOvoidTT__5aoVPIWYzahUyBc9bMm0M5w_.node = &TM__gfe9a52b5gJr8GSrnr883iA_0[3];
NTIseqLtupleLfinishat58monotime_fut58futureLsystemOvoidTTT__oKfdUHDH0q5oP14wOM6kug_.size = sizeof(tySequence__oKfdUHDH0q5oP14wOM6kug*);
NTIseqLtupleLfinishat58monotime_fut58futureLsystemOvoidTTT__oKfdUHDH0q5oP14wOM6kug_.align = NIM_ALIGNOF(tySequence__oKfdUHDH0q5oP14wOM6kug*);
NTIseqLtupleLfinishat58monotime_fut58futureLsystemOvoidTTT__oKfdUHDH0q5oP14wOM6kug_.kind = 24;
NTIseqLtupleLfinishat58monotime_fut58futureLsystemOvoidTTT__oKfdUHDH0q5oP14wOM6kug_.base = (&NTItupleLfinishat58monotime_fut58futureLsystemOvoidTT__5aoVPIWYzahUyBc9bMm0M5w_);
NTIseqLtupleLfinishat58monotime_fut58futureLsystemOvoidTTT__oKfdUHDH0q5oP14wOM6kug_.marker = Marker_tySequence__oKfdUHDH0q5oP14wOM6kug;
TM__gfe9a52b5gJr8GSrnr883iA_0[2].kind = 1;
TM__gfe9a52b5gJr8GSrnr883iA_0[2].offset = offsetof(tyObject_HeapQueue__mgfFdry9aKsRMW9au5u9bSpOQ, data);
TM__gfe9a52b5gJr8GSrnr883iA_0[2].typ = (&NTIseqLtupleLfinishat58monotime_fut58futureLsystemOvoidTTT__oKfdUHDH0q5oP14wOM6kug_);
TM__gfe9a52b5gJr8GSrnr883iA_0[2].name = "data";
NTIheapqueue__mgfFdry9aKsRMW9au5u9bSpOQ_.node = &TM__gfe9a52b5gJr8GSrnr883iA_0[2];
TM__gfe9a52b5gJr8GSrnr883iA_0[1].kind = 1;
TM__gfe9a52b5gJr8GSrnr883iA_0[1].offset = offsetof(tyObject_PDispatcherBasecolonObjectType___YNzlM8oq8NLlO720L2VFMw, timers);
TM__gfe9a52b5gJr8GSrnr883iA_0[1].typ = (&NTIheapqueue__mgfFdry9aKsRMW9au5u9bSpOQ_);
TM__gfe9a52b5gJr8GSrnr883iA_0[1].name = "timers";
TM__gfe9a52b5gJr8GSrnr883iA_2_2[1] = &TM__gfe9a52b5gJr8GSrnr883iA_0[6];
NTIdeque__NuwIXbomwb0PtcywOgXRnA_.size = sizeof(tyObject_Deque__NuwIXbomwb0PtcywOgXRnA);
NTIdeque__NuwIXbomwb0PtcywOgXRnA_.align = NIM_ALIGNOF(tyObject_Deque__NuwIXbomwb0PtcywOgXRnA);
NTIdeque__NuwIXbomwb0PtcywOgXRnA_.kind = 18;
NTIdeque__NuwIXbomwb0PtcywOgXRnA_.base = 0;
TM__gfe9a52b5gJr8GSrnr883iA_4_5[0] = &TM__gfe9a52b5gJr8GSrnr883iA_0[8];
TM__gfe9a52b5gJr8GSrnr883iA_0[8].kind = 1;
TM__gfe9a52b5gJr8GSrnr883iA_0[8].offset = offsetof(tyObject_Deque__NuwIXbomwb0PtcywOgXRnA, data);
TM__gfe9a52b5gJr8GSrnr883iA_0[8].typ = (&NTIseqLprocLTLOclosure_gcsafeOTT__aNpJjaoUowCQc7fBn3wtDQ_);
TM__gfe9a52b5gJr8GSrnr883iA_0[8].name = "data";
TM__gfe9a52b5gJr8GSrnr883iA_4_5[1] = &TM__gfe9a52b5gJr8GSrnr883iA_0[9];
TM__gfe9a52b5gJr8GSrnr883iA_0[9].kind = 1;
TM__gfe9a52b5gJr8GSrnr883iA_0[9].offset = offsetof(tyObject_Deque__NuwIXbomwb0PtcywOgXRnA, head);
TM__gfe9a52b5gJr8GSrnr883iA_0[9].typ = (&NTIint__rR5Bzr1D5krxoo1NcNyeMA_);
TM__gfe9a52b5gJr8GSrnr883iA_0[9].name = "head";
TM__gfe9a52b5gJr8GSrnr883iA_4_5[2] = &TM__gfe9a52b5gJr8GSrnr883iA_0[10];
TM__gfe9a52b5gJr8GSrnr883iA_0[10].kind = 1;
TM__gfe9a52b5gJr8GSrnr883iA_0[10].offset = offsetof(tyObject_Deque__NuwIXbomwb0PtcywOgXRnA, tail);
TM__gfe9a52b5gJr8GSrnr883iA_0[10].typ = (&NTIint__rR5Bzr1D5krxoo1NcNyeMA_);
TM__gfe9a52b5gJr8GSrnr883iA_0[10].name = "tail";
TM__gfe9a52b5gJr8GSrnr883iA_4_5[3] = &TM__gfe9a52b5gJr8GSrnr883iA_0[11];
TM__gfe9a52b5gJr8GSrnr883iA_0[11].kind = 1;
TM__gfe9a52b5gJr8GSrnr883iA_0[11].offset = offsetof(tyObject_Deque__NuwIXbomwb0PtcywOgXRnA, count);
TM__gfe9a52b5gJr8GSrnr883iA_0[11].typ = (&NTIint__rR5Bzr1D5krxoo1NcNyeMA_);
TM__gfe9a52b5gJr8GSrnr883iA_0[11].name = "count";
TM__gfe9a52b5gJr8GSrnr883iA_4_5[4] = &TM__gfe9a52b5gJr8GSrnr883iA_0[12];
TM__gfe9a52b5gJr8GSrnr883iA_0[12].kind = 1;
TM__gfe9a52b5gJr8GSrnr883iA_0[12].offset = offsetof(tyObject_Deque__NuwIXbomwb0PtcywOgXRnA, mask);
TM__gfe9a52b5gJr8GSrnr883iA_0[12].typ = (&NTIint__rR5Bzr1D5krxoo1NcNyeMA_);
TM__gfe9a52b5gJr8GSrnr883iA_0[12].name = "mask";
TM__gfe9a52b5gJr8GSrnr883iA_0[7].len = 5; TM__gfe9a52b5gJr8GSrnr883iA_0[7].kind = 2; TM__gfe9a52b5gJr8GSrnr883iA_0[7].sons = &TM__gfe9a52b5gJr8GSrnr883iA_4_5[0];
NTIdeque__NuwIXbomwb0PtcywOgXRnA_.node = &TM__gfe9a52b5gJr8GSrnr883iA_0[7];
TM__gfe9a52b5gJr8GSrnr883iA_0[6].kind = 1;
TM__gfe9a52b5gJr8GSrnr883iA_0[6].offset = offsetof(tyObject_PDispatcherBasecolonObjectType___YNzlM8oq8NLlO720L2VFMw, callbacks);
TM__gfe9a52b5gJr8GSrnr883iA_0[6].typ = (&NTIdeque__NuwIXbomwb0PtcywOgXRnA_);
TM__gfe9a52b5gJr8GSrnr883iA_0[6].name = "callbacks";
TM__gfe9a52b5gJr8GSrnr883iA_0[0].len = 2; TM__gfe9a52b5gJr8GSrnr883iA_0[0].kind = 2; TM__gfe9a52b5gJr8GSrnr883iA_0[0].sons = &TM__gfe9a52b5gJr8GSrnr883iA_2_2[0];
NTIpdispatcherbase58objecttype__YNzlM8oq8NLlO720L2VFMw_.node = &TM__gfe9a52b5gJr8GSrnr883iA_0[0];
NTIpdispatcher58objecttype__mNiwh37MfaAP9cG4kqT6kpg_.size = sizeof(tyObject_PDispatchercolonObjectType___mNiwh37MfaAP9cG4kqT6kpg);
NTIpdispatcher58objecttype__mNiwh37MfaAP9cG4kqT6kpg_.align = NIM_ALIGNOF(tyObject_PDispatchercolonObjectType___mNiwh37MfaAP9cG4kqT6kpg);
NTIpdispatcher58objecttype__mNiwh37MfaAP9cG4kqT6kpg_.kind = 17;
NTIpdispatcher58objecttype__mNiwh37MfaAP9cG4kqT6kpg_.base = (&NTIpdispatcherbase58objecttype__YNzlM8oq8NLlO720L2VFMw_);
NTIselectorimpl__jkoZicTBtYdKkYck5SFJEQ_.size = sizeof(tyObject_SelectorImpl__jkoZicTBtYdKkYck5SFJEQ);
NTIselectorimpl__jkoZicTBtYdKkYck5SFJEQ_.align = NIM_ALIGNOF(tyObject_SelectorImpl__jkoZicTBtYdKkYck5SFJEQ);
NTIselectorimpl__jkoZicTBtYdKkYck5SFJEQ_.kind = 18;
NTIselectorimpl__jkoZicTBtYdKkYck5SFJEQ_.base = 0;
TM__gfe9a52b5gJr8GSrnr883iA_5_5[0] = &TM__gfe9a52b5gJr8GSrnr883iA_0[15];
TM__gfe9a52b5gJr8GSrnr883iA_0[15].kind = 1;
TM__gfe9a52b5gJr8GSrnr883iA_0[15].offset = offsetof(tyObject_SelectorImpl__jkoZicTBtYdKkYck5SFJEQ, epollFD);
TM__gfe9a52b5gJr8GSrnr883iA_0[15].typ = (&NTIcint__nlCscttRCss70IBTyuBqnA_);
TM__gfe9a52b5gJr8GSrnr883iA_0[15].name = "epollFD";
TM__gfe9a52b5gJr8GSrnr883iA_5_5[1] = &TM__gfe9a52b5gJr8GSrnr883iA_0[16];
TM__gfe9a52b5gJr8GSrnr883iA_0[16].kind = 1;
TM__gfe9a52b5gJr8GSrnr883iA_0[16].offset = offsetof(tyObject_SelectorImpl__jkoZicTBtYdKkYck5SFJEQ, maxFD);
TM__gfe9a52b5gJr8GSrnr883iA_0[16].typ = (&NTIint__rR5Bzr1D5krxoo1NcNyeMA_);
TM__gfe9a52b5gJr8GSrnr883iA_0[16].name = "maxFD";
TM__gfe9a52b5gJr8GSrnr883iA_5_5[2] = &TM__gfe9a52b5gJr8GSrnr883iA_0[17];
TM__gfe9a52b5gJr8GSrnr883iA_0[17].kind = 1;
TM__gfe9a52b5gJr8GSrnr883iA_0[17].offset = offsetof(tyObject_SelectorImpl__jkoZicTBtYdKkYck5SFJEQ, numFD);
TM__gfe9a52b5gJr8GSrnr883iA_0[17].typ = (&NTIint__rR5Bzr1D5krxoo1NcNyeMA_);
TM__gfe9a52b5gJr8GSrnr883iA_0[17].name = "numFD";
TM__gfe9a52b5gJr8GSrnr883iA_5_5[3] = &TM__gfe9a52b5gJr8GSrnr883iA_0[18];
NTIselectorkey__561GPxg10TdJiEAAWoraPw_.size = sizeof(tyObject_SelectorKey__561GPxg10TdJiEAAWoraPw);
NTIselectorkey__561GPxg10TdJiEAAWoraPw_.align = NIM_ALIGNOF(tyObject_SelectorKey__561GPxg10TdJiEAAWoraPw);
NTIselectorkey__561GPxg10TdJiEAAWoraPw_.kind = 18;
NTIselectorkey__561GPxg10TdJiEAAWoraPw_.base = 0;
TM__gfe9a52b5gJr8GSrnr883iA_6_4[0] = &TM__gfe9a52b5gJr8GSrnr883iA_0[20];
TM__gfe9a52b5gJr8GSrnr883iA_0[20].kind = 1;
TM__gfe9a52b5gJr8GSrnr883iA_0[20].offset = offsetof(tyObject_SelectorKey__561GPxg10TdJiEAAWoraPw, ident);
TM__gfe9a52b5gJr8GSrnr883iA_0[20].typ = (&NTIint__rR5Bzr1D5krxoo1NcNyeMA_);
TM__gfe9a52b5gJr8GSrnr883iA_0[20].name = "ident";
TM__gfe9a52b5gJr8GSrnr883iA_6_4[1] = &TM__gfe9a52b5gJr8GSrnr883iA_0[21];
TM__gfe9a52b5gJr8GSrnr883iA_0[21].kind = 1;
TM__gfe9a52b5gJr8GSrnr883iA_0[21].offset = offsetof(tyObject_SelectorKey__561GPxg10TdJiEAAWoraPw, events);
TM__gfe9a52b5gJr8GSrnr883iA_0[21].typ = (&NTIsetLeventT__YIRsZrDT89buh37M5yeUgng_);
TM__gfe9a52b5gJr8GSrnr883iA_0[21].name = "events";
TM__gfe9a52b5gJr8GSrnr883iA_6_4[2] = &TM__gfe9a52b5gJr8GSrnr883iA_0[22];
TM__gfe9a52b5gJr8GSrnr883iA_0[22].kind = 1;
TM__gfe9a52b5gJr8GSrnr883iA_0[22].offset = offsetof(tyObject_SelectorKey__561GPxg10TdJiEAAWoraPw, param);
TM__gfe9a52b5gJr8GSrnr883iA_0[22].typ = (&NTIint__rR5Bzr1D5krxoo1NcNyeMA_);
TM__gfe9a52b5gJr8GSrnr883iA_0[22].name = "param";
TM__gfe9a52b5gJr8GSrnr883iA_6_4[3] = &TM__gfe9a52b5gJr8GSrnr883iA_0[23];
NTIasyncdata__hOYUN4IOpj9adMwn6W7S2VA_.size = sizeof(tyObject_AsyncData__hOYUN4IOpj9adMwn6W7S2VA);
NTIasyncdata__hOYUN4IOpj9adMwn6W7S2VA_.align = NIM_ALIGNOF(tyObject_AsyncData__hOYUN4IOpj9adMwn6W7S2VA);
NTIasyncdata__hOYUN4IOpj9adMwn6W7S2VA_.kind = 18;
NTIasyncdata__hOYUN4IOpj9adMwn6W7S2VA_.base = 0;
TM__gfe9a52b5gJr8GSrnr883iA_7_2[0] = &TM__gfe9a52b5gJr8GSrnr883iA_0[25];
NTIcallback__kbFLS7lxxUPzrFcbZuGUzQ_.size = sizeof(tyTuple__JfHvHzMrhKkWAUvQKe0i1A);
NTIcallback__kbFLS7lxxUPzrFcbZuGUzQ_.align = NIM_ALIGNOF(tyTuple__JfHvHzMrhKkWAUvQKe0i1A);
NTIcallback__kbFLS7lxxUPzrFcbZuGUzQ_.kind = 18;
NTIcallback__kbFLS7lxxUPzrFcbZuGUzQ_.base = 0;
TM__gfe9a52b5gJr8GSrnr883iA_8_2[0] = &TM__gfe9a52b5gJr8GSrnr883iA_0[27];
TM__gfe9a52b5gJr8GSrnr883iA_0[27].kind = 1;
TM__gfe9a52b5gJr8GSrnr883iA_0[27].offset = offsetof(tyTuple__JfHvHzMrhKkWAUvQKe0i1A, Field0);
TM__gfe9a52b5gJr8GSrnr883iA_0[27].typ = (&NTIpointer__vr5DoT1jILTGdRlYv1OYpw_);
TM__gfe9a52b5gJr8GSrnr883iA_0[27].name = "Field0";
TM__gfe9a52b5gJr8GSrnr883iA_8_2[1] = &TM__gfe9a52b5gJr8GSrnr883iA_0[28];
TM__gfe9a52b5gJr8GSrnr883iA_0[28].kind = 1;
TM__gfe9a52b5gJr8GSrnr883iA_0[28].offset = offsetof(tyTuple__JfHvHzMrhKkWAUvQKe0i1A, Field1);
TM__gfe9a52b5gJr8GSrnr883iA_0[28].typ = (&NTIrefobject__HsJiUUcO9cHBdUCi0HwkSTA_);
TM__gfe9a52b5gJr8GSrnr883iA_0[28].name = "Field1";
TM__gfe9a52b5gJr8GSrnr883iA_0[26].len = 2; TM__gfe9a52b5gJr8GSrnr883iA_0[26].kind = 2; TM__gfe9a52b5gJr8GSrnr883iA_0[26].sons = &TM__gfe9a52b5gJr8GSrnr883iA_8_2[0];
NTIcallback__kbFLS7lxxUPzrFcbZuGUzQ_.node = &TM__gfe9a52b5gJr8GSrnr883iA_0[26];
NTIseqLcallbackT__mqHCvcswroDetkzsL3ixtg_.size = sizeof(tySequence__mqHCvcswroDetkzsL3ixtg*);
NTIseqLcallbackT__mqHCvcswroDetkzsL3ixtg_.align = NIM_ALIGNOF(tySequence__mqHCvcswroDetkzsL3ixtg*);
NTIseqLcallbackT__mqHCvcswroDetkzsL3ixtg_.kind = 24;
NTIseqLcallbackT__mqHCvcswroDetkzsL3ixtg_.base = (&NTIcallback__kbFLS7lxxUPzrFcbZuGUzQ_);
NTIseqLcallbackT__mqHCvcswroDetkzsL3ixtg_.marker = Marker_tySequence__mqHCvcswroDetkzsL3ixtg;
TM__gfe9a52b5gJr8GSrnr883iA_0[25].kind = 1;
TM__gfe9a52b5gJr8GSrnr883iA_0[25].offset = offsetof(tyObject_AsyncData__hOYUN4IOpj9adMwn6W7S2VA, readList);
TM__gfe9a52b5gJr8GSrnr883iA_0[25].typ = (&NTIseqLcallbackT__mqHCvcswroDetkzsL3ixtg_);
TM__gfe9a52b5gJr8GSrnr883iA_0[25].name = "readList";
TM__gfe9a52b5gJr8GSrnr883iA_7_2[1] = &TM__gfe9a52b5gJr8GSrnr883iA_0[29];
TM__gfe9a52b5gJr8GSrnr883iA_0[29].kind = 1;
TM__gfe9a52b5gJr8GSrnr883iA_0[29].offset = offsetof(tyObject_AsyncData__hOYUN4IOpj9adMwn6W7S2VA, writeList);
TM__gfe9a52b5gJr8GSrnr883iA_0[29].typ = (&NTIseqLcallbackT__mqHCvcswroDetkzsL3ixtg_);
TM__gfe9a52b5gJr8GSrnr883iA_0[29].name = "writeList";
TM__gfe9a52b5gJr8GSrnr883iA_0[24].len = 2; TM__gfe9a52b5gJr8GSrnr883iA_0[24].kind = 2; TM__gfe9a52b5gJr8GSrnr883iA_0[24].sons = &TM__gfe9a52b5gJr8GSrnr883iA_7_2[0];
NTIasyncdata__hOYUN4IOpj9adMwn6W7S2VA_.node = &TM__gfe9a52b5gJr8GSrnr883iA_0[24];
TM__gfe9a52b5gJr8GSrnr883iA_0[23].kind = 1;
TM__gfe9a52b5gJr8GSrnr883iA_0[23].offset = offsetof(tyObject_SelectorKey__561GPxg10TdJiEAAWoraPw, data);
TM__gfe9a52b5gJr8GSrnr883iA_0[23].typ = (&NTIasyncdata__hOYUN4IOpj9adMwn6W7S2VA_);
TM__gfe9a52b5gJr8GSrnr883iA_0[23].name = "data";
TM__gfe9a52b5gJr8GSrnr883iA_0[19].len = 4; TM__gfe9a52b5gJr8GSrnr883iA_0[19].kind = 2; TM__gfe9a52b5gJr8GSrnr883iA_0[19].sons = &TM__gfe9a52b5gJr8GSrnr883iA_6_4[0];
NTIselectorkey__561GPxg10TdJiEAAWoraPw_.node = &TM__gfe9a52b5gJr8GSrnr883iA_0[19];
NTIseqLselectorkeyLasyncdispatchOasyncdataTT__5L9b5Ztm9adPEys1vE9cEPQJA_.size = sizeof(tySequence__5L9b5Ztm9adPEys1vE9cEPQJA*);
NTIseqLselectorkeyLasyncdispatchOasyncdataTT__5L9b5Ztm9adPEys1vE9cEPQJA_.align = NIM_ALIGNOF(tySequence__5L9b5Ztm9adPEys1vE9cEPQJA*);
NTIseqLselectorkeyLasyncdispatchOasyncdataTT__5L9b5Ztm9adPEys1vE9cEPQJA_.kind = 24;
NTIseqLselectorkeyLasyncdispatchOasyncdataTT__5L9b5Ztm9adPEys1vE9cEPQJA_.base = (&NTIselectorkey__561GPxg10TdJiEAAWoraPw_);
NTIseqLselectorkeyLasyncdispatchOasyncdataTT__5L9b5Ztm9adPEys1vE9cEPQJA_.marker = Marker_tySequence__5L9b5Ztm9adPEys1vE9cEPQJA;
TM__gfe9a52b5gJr8GSrnr883iA_0[18].kind = 1;
TM__gfe9a52b5gJr8GSrnr883iA_0[18].offset = offsetof(tyObject_SelectorImpl__jkoZicTBtYdKkYck5SFJEQ, fds);
TM__gfe9a52b5gJr8GSrnr883iA_0[18].typ = (&NTIseqLselectorkeyLasyncdispatchOasyncdataTT__5L9b5Ztm9adPEys1vE9cEPQJA_);
TM__gfe9a52b5gJr8GSrnr883iA_0[18].name = "fds";
TM__gfe9a52b5gJr8GSrnr883iA_5_5[4] = &TM__gfe9a52b5gJr8GSrnr883iA_0[30];
TM__gfe9a52b5gJr8GSrnr883iA_0[30].kind = 1;
TM__gfe9a52b5gJr8GSrnr883iA_0[30].offset = offsetof(tyObject_SelectorImpl__jkoZicTBtYdKkYck5SFJEQ, count);
TM__gfe9a52b5gJr8GSrnr883iA_0[30].typ = (&NTIint__rR5Bzr1D5krxoo1NcNyeMA_);
TM__gfe9a52b5gJr8GSrnr883iA_0[30].name = "count";
TM__gfe9a52b5gJr8GSrnr883iA_0[14].len = 5; TM__gfe9a52b5gJr8GSrnr883iA_0[14].kind = 2; TM__gfe9a52b5gJr8GSrnr883iA_0[14].sons = &TM__gfe9a52b5gJr8GSrnr883iA_5_5[0];
NTIselectorimpl__jkoZicTBtYdKkYck5SFJEQ_.node = &TM__gfe9a52b5gJr8GSrnr883iA_0[14];
NTIselector__Y5hK0M9cL3lXwccEV9cgR9cQw_.size = sizeof(tyObject_SelectorImpl__jkoZicTBtYdKkYck5SFJEQ*);
NTIselector__Y5hK0M9cL3lXwccEV9cgR9cQw_.align = NIM_ALIGNOF(tyObject_SelectorImpl__jkoZicTBtYdKkYck5SFJEQ*);
NTIselector__Y5hK0M9cL3lXwccEV9cgR9cQw_.kind = 22;
NTIselector__Y5hK0M9cL3lXwccEV9cgR9cQw_.base = (&NTIselectorimpl__jkoZicTBtYdKkYck5SFJEQ_);
NTIselector__Y5hK0M9cL3lXwccEV9cgR9cQw_.marker = Marker_tyRef__Y5hK0M9cL3lXwccEV9cgR9cQw;
TM__gfe9a52b5gJr8GSrnr883iA_0[13].kind = 1;
TM__gfe9a52b5gJr8GSrnr883iA_0[13].offset = offsetof(tyObject_PDispatchercolonObjectType___mNiwh37MfaAP9cG4kqT6kpg, selector);
TM__gfe9a52b5gJr8GSrnr883iA_0[13].typ = (&NTIselector__Y5hK0M9cL3lXwccEV9cgR9cQw_);
TM__gfe9a52b5gJr8GSrnr883iA_0[13].name = "selector";
NTIpdispatcher58objecttype__mNiwh37MfaAP9cG4kqT6kpg_.node = &TM__gfe9a52b5gJr8GSrnr883iA_0[13];
NTIpdispatcher__OGnyBMU9csFmaJm9bh2uOQiQ_.size = sizeof(tyObject_PDispatchercolonObjectType___mNiwh37MfaAP9cG4kqT6kpg*);
NTIpdispatcher__OGnyBMU9csFmaJm9bh2uOQiQ_.align = NIM_ALIGNOF(tyObject_PDispatchercolonObjectType___mNiwh37MfaAP9cG4kqT6kpg*);
NTIpdispatcher__OGnyBMU9csFmaJm9bh2uOQiQ_.kind = 22;
NTIpdispatcher__OGnyBMU9csFmaJm9bh2uOQiQ_.base = (&NTIpdispatcher58objecttype__mNiwh37MfaAP9cG4kqT6kpg_);
NTIpdispatcher__OGnyBMU9csFmaJm9bh2uOQiQ_.marker = Marker_tyRef__OGnyBMU9csFmaJm9bh2uOQiQ;
}

