/* Generated by Nim Compiler v1.7.1 */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_Uri__j49bukNPrq747O1GRd4Ng9bQ tyObject_Uri__j49bukNPrq747O1GRd4Ng9bQ;
typedef struct tyObject_PackageInfo__y9ahmwzrCcWrfsrJgR1q4lw tyObject_PackageInfo__y9ahmwzrCcWrfsrJgR1q4lw;
typedef struct tyObject_HashSet__CD8Dpv0WGmASelVaNSo6zg tyObject_HashSet__CD8Dpv0WGmASelVaNSo6zg;
typedef struct tySequence__4eRCaZmrYLLw2k30GPTiMw tySequence__4eRCaZmrYLLw2k30GPTiMw;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ tySequence__sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tySequence__kLwf9aGQcuduFr4gekUDa2w tySequence__kLwf9aGQcuduFr4gekUDa2w;
typedef struct tyObject_Table__Ji6x6JQ0gVMaFr8AIk18Ug tyObject_Table__Ji6x6JQ0gVMaFr8AIk18Ug;
typedef struct tySequence__SFipDZIkFtPcrLs0AGBBjQ tySequence__SFipDZIkFtPcrLs0AGBBjQ;
typedef struct tyTuple__BjxoJYFE5BulbiU15SM6nQ tyTuple__BjxoJYFE5BulbiU15SM6nQ;
typedef struct tyObject_Version__9bU0a4Oqtl9aJmGyzYi8ZnBA tyObject_Version__9bU0a4Oqtl9aJmGyzYi8ZnBA;
typedef struct tyObject_Sha1Hash__zQwLVDNef3gJr9bhL9bRloJw tyObject_Sha1Hash__zQwLVDNef3gJr9bhL9bRloJw;
typedef struct tyObject_OrderedTable__b2SAayIK9c6IoZnFt9cutJhQ tyObject_OrderedTable__b2SAayIK9c6IoZnFt9cutJhQ;
typedef struct tySequence__ZkxkVxJvB9aqet9cfVQmFTZw tySequence__ZkxkVxJvB9aqet9cfVQmFTZw;
typedef struct tyObject_PackageMetaData__EO1rPizWROcibmAlVzA30w tyObject_PackageMetaData__EO1rPizWROcibmAlVzA30w;
typedef struct tyObject_HashSet__aCgx9aJWOlGNhL9b41LIC4Wg tyObject_HashSet__aCgx9aJWOlGNhL9b41LIC4Wg;
typedef struct tySequence__72hOjuY2LKiowAwLCg19a9bA tySequence__72hOjuY2LKiowAwLCg19a9bA;
typedef struct tyTuple__gDWaEqPfhOauJWKMBm8bzg tyTuple__gDWaEqPfhOauJWKMBm8bzg;
typedef struct tyObject_VersionRangeObj__FrJQzed5Yezqp6gCbEyg0w tyObject_VersionRangeObj__FrJQzed5Yezqp6gCbEyg0w;
typedef struct tyObject_LockFileDep__PkUOL8vzIvRRmF9bLOPRlhg tyObject_LockFileDep__PkUOL8vzIvRRmF9bLOPRlhg;
typedef struct tyObject_Checksums__aZcxVfkZCt9bd29bg29aMe9aaA tyObject_Checksums__aZcxVfkZCt9bd29bg29aMe9aaA;
typedef struct tyTuple__QeWl6B6ffS4pU6WWrtcrDw tyTuple__QeWl6B6ffS4pU6WWrtcrDw;
typedef struct tyTuple__8ZxhPt1NwfElsJs8zUSV9bg tyTuple__8ZxhPt1NwfElsJs8zUSV9bg;
typedef struct tyTuple__m8l9a4rYFktlUTIniXgnvog tyTuple__m8l9a4rYFktlUTIniXgnvog;
typedef struct tyTuple__r1NtfsBxxsYs1cV48P1DyA tyTuple__r1NtfsBxxsYs1cV48P1DyA;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyObject_Uri__j49bukNPrq747O1GRd4Ng9bQ {
NimStringDesc* scheme;
NimStringDesc* username;
NimStringDesc* password;
NimStringDesc* hostname;
NimStringDesc* port;
NimStringDesc* path;
NimStringDesc* query;
NimStringDesc* anchor;
NIM_BOOL opaque;
NIM_BOOL isIpv6;
};
struct tyObject_HashSet__CD8Dpv0WGmASelVaNSo6zg {
tySequence__4eRCaZmrYLLw2k30GPTiMw* data;
NI counter;
};
struct tyObject_Table__Ji6x6JQ0gVMaFr8AIk18Ug {
tySequence__SFipDZIkFtPcrLs0AGBBjQ* data;
NI counter;
};
struct tyObject_Version__9bU0a4Oqtl9aJmGyzYi8ZnBA {
NimStringDesc* version;
};
struct tyObject_Sha1Hash__zQwLVDNef3gJr9bhL9bRloJw {
NimStringDesc* hashValue;
};
struct tyTuple__BjxoJYFE5BulbiU15SM6nQ {
NimStringDesc* Field0;
tyObject_Version__9bU0a4Oqtl9aJmGyzYi8ZnBA Field1;
tyObject_Sha1Hash__zQwLVDNef3gJr9bhL9bRloJw Field2;
};
struct tyObject_OrderedTable__b2SAayIK9c6IoZnFt9cutJhQ {
tySequence__ZkxkVxJvB9aqet9cfVQmFTZw* data;
NI counter;
NI first;
NI last;
};
typedef NU8 tyEnum_DownloadMethod__IqkMKe5PGkzDG0ayIWPJ6w;
struct tyObject_HashSet__aCgx9aJWOlGNhL9b41LIC4Wg {
tySequence__72hOjuY2LKiowAwLCg19a9bA* data;
NI counter;
};
struct tyObject_PackageMetaData__EO1rPizWROcibmAlVzA30w {
NimStringDesc* url;
tyEnum_DownloadMethod__IqkMKe5PGkzDG0ayIWPJ6w downloadMethod;
tyObject_Sha1Hash__zQwLVDNef3gJr9bhL9bRloJw vcsRevision;
tySequence__sM4lkSb7zS6F7OVMvW9cffQ* files;
tySequence__sM4lkSb7zS6F7OVMvW9cffQ* binaries;
tyObject_HashSet__aCgx9aJWOlGNhL9b41LIC4Wg specialVersions;
};
struct tyObject_PackageInfo__y9ahmwzrCcWrfsrJgR1q4lw {
NimStringDesc* myPath;
NIM_BOOL isNimScript;
NIM_BOOL isMinimal;
NIM_BOOL isInstalled;
tyObject_HashSet__CD8Dpv0WGmASelVaNSo6zg nimbleTasks;
tyObject_HashSet__CD8Dpv0WGmASelVaNSo6zg postHooks;
tyObject_HashSet__CD8Dpv0WGmASelVaNSo6zg preHooks;
NimStringDesc* author;
NimStringDesc* description;
NimStringDesc* license;
tySequence__sM4lkSb7zS6F7OVMvW9cffQ* skipDirs;
tySequence__sM4lkSb7zS6F7OVMvW9cffQ* skipFiles;
tySequence__sM4lkSb7zS6F7OVMvW9cffQ* skipExt;
tySequence__sM4lkSb7zS6F7OVMvW9cffQ* installDirs;
tySequence__sM4lkSb7zS6F7OVMvW9cffQ* installFiles;
tySequence__sM4lkSb7zS6F7OVMvW9cffQ* installExt;
tySequence__kLwf9aGQcuduFr4gekUDa2w* requires;
tyObject_Table__Ji6x6JQ0gVMaFr8AIk18Ug bin;
NimStringDesc* binDir;
NimStringDesc* srcDir;
NimStringDesc* backend;
tySequence__sM4lkSb7zS6F7OVMvW9cffQ* foreignDeps;
tyTuple__BjxoJYFE5BulbiU15SM6nQ basicInfo;
tyObject_OrderedTable__b2SAayIK9c6IoZnFt9cutJhQ lockedDeps;
tyObject_PackageMetaData__EO1rPizWROcibmAlVzA30w metaData;
NIM_BOOL isLink;
};
struct tyTuple__gDWaEqPfhOauJWKMBm8bzg {
NimStringDesc* Field0;
tyObject_VersionRangeObj__FrJQzed5Yezqp6gCbEyg0w* Field1;
};
struct tyObject_Checksums__aZcxVfkZCt9bd29bg29aMe9aaA {
tyObject_Sha1Hash__zQwLVDNef3gJr9bhL9bRloJw sha1;
};
struct tyObject_LockFileDep__PkUOL8vzIvRRmF9bLOPRlhg {
tyObject_Version__9bU0a4Oqtl9aJmGyzYi8ZnBA version;
tyObject_Sha1Hash__zQwLVDNef3gJr9bhL9bRloJw vcsRevision;
NimStringDesc* url;
tyEnum_DownloadMethod__IqkMKe5PGkzDG0ayIWPJ6w downloadMethod;
tySequence__sM4lkSb7zS6F7OVMvW9cffQ* dependencies;
tyObject_Checksums__aZcxVfkZCt9bd29bg29aMe9aaA checksums;
};
struct tyTuple__QeWl6B6ffS4pU6WWrtcrDw {
NI Field0;
NimStringDesc* Field1;
};
struct tyTuple__8ZxhPt1NwfElsJs8zUSV9bg {
NI Field0;
NimStringDesc* Field1;
NimStringDesc* Field2;
};
struct tyTuple__m8l9a4rYFktlUTIniXgnvog {
NI Field0;
NI Field1;
NimStringDesc* Field2;
tyObject_LockFileDep__PkUOL8vzIvRRmF9bLOPRlhg Field3;
};
struct tyTuple__r1NtfsBxxsYs1cV48P1DyA {
NI Field0;
tyObject_Version__9bU0a4Oqtl9aJmGyzYi8ZnBA Field1;
};
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct tySequence__kLwf9aGQcuduFr4gekUDa2w {
  TGenericSeq Sup;
  tyTuple__gDWaEqPfhOauJWKMBm8bzg data[SEQ_DECL_SIZE];
};
struct tySequence__4eRCaZmrYLLw2k30GPTiMw {
  TGenericSeq Sup;
  tyTuple__QeWl6B6ffS4pU6WWrtcrDw data[SEQ_DECL_SIZE];
};
struct tySequence__SFipDZIkFtPcrLs0AGBBjQ {
  TGenericSeq Sup;
  tyTuple__8ZxhPt1NwfElsJs8zUSV9bg data[SEQ_DECL_SIZE];
};
struct tySequence__ZkxkVxJvB9aqet9cfVQmFTZw {
  TGenericSeq Sup;
  tyTuple__m8l9a4rYFktlUTIniXgnvog data[SEQ_DECL_SIZE];
};
struct tySequence__72hOjuY2LKiowAwLCg19a9bA {
  TGenericSeq Sup;
  tyTuple__r1NtfsBxxsYs1cV48P1DyA data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem__system_1727)(void* dest, void* source, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_LIB_PRIVATE N_NIMCALL(void, addQuoted__pureZos_457)(NimStringDesc** s, NimStringDesc* x);
N_LIB_PRIVATE N_NIMCALL(void, addQuoted__nimblepkgZpackageinfo_640)(NimStringDesc** s, NIM_BOOL x);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_3527)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void, addQuoted__nimble_3453)(NimStringDesc** s, tyObject_HashSet__CD8Dpv0WGmASelVaNSo6zg x);
N_LIB_PRIVATE N_NIMCALL(void, addQuoted__pureZhttpcore_2614)(NimStringDesc** s, tySequence__sM4lkSb7zS6F7OVMvW9cffQ* x);
N_LIB_PRIVATE N_NIMCALL(void, addQuoted__nimble_4063)(NimStringDesc** s, tySequence__kLwf9aGQcuduFr4gekUDa2w* x);
N_LIB_PRIVATE N_NIMCALL(void, addQuoted__nimble_4539)(NimStringDesc** s, tyObject_Table__Ji6x6JQ0gVMaFr8AIk18Ug x);
N_LIB_PRIVATE N_NIMCALL(void, addQuoted__nimble_5092)(NimStringDesc** s, tyTuple__BjxoJYFE5BulbiU15SM6nQ x);
N_LIB_PRIVATE N_NIMCALL(void, addQuoted__nimble_5426)(NimStringDesc** s, tyObject_OrderedTable__b2SAayIK9c6IoZnFt9cutJhQ* x);
N_LIB_PRIVATE N_NIMCALL(void, addQuoted__nimble_5134)(NimStringDesc** s, tyObject_Version__9bU0a4Oqtl9aJmGyzYi8ZnBA x);
N_LIB_PRIVATE N_NIMCALL(void, addQuoted__nimble_5147)(NimStringDesc** s, tyObject_Sha1Hash__zQwLVDNef3gJr9bhL9bRloJw x);
N_LIB_PRIVATE N_NIMCALL(void, addQuoted__nimble_5630)(NimStringDesc** s, tyEnum_DownloadMethod__IqkMKe5PGkzDG0ayIWPJ6w x);
N_LIB_PRIVATE N_NIMCALL(void, addQuoted__nimble_5689)(NimStringDesc** s, tyObject_Checksums__aZcxVfkZCt9bd29bg29aMe9aaA x);
N_LIB_PRIVATE N_NIMCALL(void, addQuoted__nimble_5955)(NimStringDesc** s, tyObject_PackageMetaData__EO1rPizWROcibmAlVzA30w* x);
N_LIB_PRIVATE N_NIMCALL(void, addQuoted__nimble_6119)(NimStringDesc** s, tyObject_HashSet__aCgx9aJWOlGNhL9b41LIC4Wg x);
STRING_LITERAL(TM__US7tUPSVHwyWbwv9cB5DrpQ_2, "(", 1);
STRING_LITERAL(TM__US7tUPSVHwyWbwv9cB5DrpQ_3, ", ", 2);
STRING_LITERAL(TM__US7tUPSVHwyWbwv9cB5DrpQ_4, "scheme", 6);
STRING_LITERAL(TM__US7tUPSVHwyWbwv9cB5DrpQ_5, ": ", 2);
STRING_LITERAL(TM__US7tUPSVHwyWbwv9cB5DrpQ_6, "username", 8);
STRING_LITERAL(TM__US7tUPSVHwyWbwv9cB5DrpQ_7, "password", 8);
STRING_LITERAL(TM__US7tUPSVHwyWbwv9cB5DrpQ_8, "hostname", 8);
STRING_LITERAL(TM__US7tUPSVHwyWbwv9cB5DrpQ_9, "port", 4);
STRING_LITERAL(TM__US7tUPSVHwyWbwv9cB5DrpQ_10, "path", 4);
STRING_LITERAL(TM__US7tUPSVHwyWbwv9cB5DrpQ_11, "query", 5);
STRING_LITERAL(TM__US7tUPSVHwyWbwv9cB5DrpQ_12, "anchor", 6);
STRING_LITERAL(TM__US7tUPSVHwyWbwv9cB5DrpQ_13, "opaque", 6);
STRING_LITERAL(TM__US7tUPSVHwyWbwv9cB5DrpQ_14, "isIpv6", 6);
STRING_LITERAL(TM__US7tUPSVHwyWbwv9cB5DrpQ_15, ")", 1);
STRING_LITERAL(TM__US7tUPSVHwyWbwv9cB5DrpQ_16, "myPath", 6);
STRING_LITERAL(TM__US7tUPSVHwyWbwv9cB5DrpQ_17, "isNimScript", 11);
STRING_LITERAL(TM__US7tUPSVHwyWbwv9cB5DrpQ_18, "isMinimal", 9);
STRING_LITERAL(TM__US7tUPSVHwyWbwv9cB5DrpQ_19, "isInstalled", 11);
STRING_LITERAL(TM__US7tUPSVHwyWbwv9cB5DrpQ_20, "nimbleTasks", 11);
STRING_LITERAL(TM__US7tUPSVHwyWbwv9cB5DrpQ_21, "postHooks", 9);
STRING_LITERAL(TM__US7tUPSVHwyWbwv9cB5DrpQ_22, "preHooks", 8);
STRING_LITERAL(TM__US7tUPSVHwyWbwv9cB5DrpQ_23, "author", 6);
STRING_LITERAL(TM__US7tUPSVHwyWbwv9cB5DrpQ_24, "description", 11);
STRING_LITERAL(TM__US7tUPSVHwyWbwv9cB5DrpQ_25, "license", 7);
STRING_LITERAL(TM__US7tUPSVHwyWbwv9cB5DrpQ_26, "skipDirs", 8);
STRING_LITERAL(TM__US7tUPSVHwyWbwv9cB5DrpQ_27, "skipFiles", 9);
STRING_LITERAL(TM__US7tUPSVHwyWbwv9cB5DrpQ_28, "skipExt", 7);
STRING_LITERAL(TM__US7tUPSVHwyWbwv9cB5DrpQ_29, "installDirs", 11);
STRING_LITERAL(TM__US7tUPSVHwyWbwv9cB5DrpQ_30, "installFiles", 12);
STRING_LITERAL(TM__US7tUPSVHwyWbwv9cB5DrpQ_31, "installExt", 10);
STRING_LITERAL(TM__US7tUPSVHwyWbwv9cB5DrpQ_32, "requires", 8);
STRING_LITERAL(TM__US7tUPSVHwyWbwv9cB5DrpQ_33, "bin", 3);
STRING_LITERAL(TM__US7tUPSVHwyWbwv9cB5DrpQ_34, "binDir", 6);
STRING_LITERAL(TM__US7tUPSVHwyWbwv9cB5DrpQ_35, "srcDir", 6);
STRING_LITERAL(TM__US7tUPSVHwyWbwv9cB5DrpQ_36, "backend", 7);
STRING_LITERAL(TM__US7tUPSVHwyWbwv9cB5DrpQ_37, "foreignDeps", 11);
STRING_LITERAL(TM__US7tUPSVHwyWbwv9cB5DrpQ_38, "basicInfo", 9);
STRING_LITERAL(TM__US7tUPSVHwyWbwv9cB5DrpQ_39, "lockedDeps", 10);
STRING_LITERAL(TM__US7tUPSVHwyWbwv9cB5DrpQ_40, "version", 7);
STRING_LITERAL(TM__US7tUPSVHwyWbwv9cB5DrpQ_41, "vcsRevision", 11);
STRING_LITERAL(TM__US7tUPSVHwyWbwv9cB5DrpQ_42, "url", 3);
STRING_LITERAL(TM__US7tUPSVHwyWbwv9cB5DrpQ_43, "downloadMethod", 14);
STRING_LITERAL(TM__US7tUPSVHwyWbwv9cB5DrpQ_44, "dependencies", 12);
STRING_LITERAL(TM__US7tUPSVHwyWbwv9cB5DrpQ_45, "checksums", 9);
STRING_LITERAL(TM__US7tUPSVHwyWbwv9cB5DrpQ_46, "sha1", 4);
STRING_LITERAL(TM__US7tUPSVHwyWbwv9cB5DrpQ_47, "metaData", 8);
STRING_LITERAL(TM__US7tUPSVHwyWbwv9cB5DrpQ_48, "files", 5);
STRING_LITERAL(TM__US7tUPSVHwyWbwv9cB5DrpQ_49, "binaries", 8);
STRING_LITERAL(TM__US7tUPSVHwyWbwv9cB5DrpQ_50, "specialVersions", 15);
STRING_LITERAL(TM__US7tUPSVHwyWbwv9cB5DrpQ_51, "isLink", 6);
extern NIM_THREADVAR TFrame* framePtr__system_3094;
extern NIM_THREADVAR TFrame* framePtr__system_3094;
extern NIM_THREADVAR TFrame* framePtr__system_3094;
extern NIM_THREADVAR TFrame* framePtr__system_3094;
extern NIM_THREADVAR TFrame* framePtr__system_3094;
extern NIM_THREADVAR TFrame* framePtr__system_3094;
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}
static N_INLINE(void, copyMem__system_1727)(void* dest, void* source, NI size) {
	nimCopyMem(dest, source, size);
}
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	{
		if (!!((src == ((NimStringDesc*) NIM_NIL)))) goto LA3_;
		copyMem__system_1727(((void*) ((&(*dest).data[(*dest).Sup.len]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
		(*dest).Sup.len += (*src).Sup.len;
	}
	LA3_: ;
}
static N_INLINE(void, nimFrame)(TFrame* s) {
	{
		if (!(framePtr__system_3094 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s).calldepth = ((NI16) 0);
	}
	goto LA1_;
	LA3_: ;
	{
		(*s).calldepth = (NI16)((*framePtr__system_3094).calldepth + ((NI16) 1));
	}
	LA1_: ;
	(*s).prev = framePtr__system_3094;
	framePtr__system_3094 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;
		callDepthLimitReached__system_3527();
	}
	LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_3094 = (*framePtr__system_3094).prev;
}
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar___nimblepkgZpackageinfo_527)(tyObject_Uri__j49bukNPrq747O1GRd4Ng9bQ* x) {
	NimStringDesc* result;
	NI countX60gensym12_;
	nimfr_("$", "/home/yyoncho/Sources/nim/Nim/lib/std/objectdollar.nim");
	result = NIM_NIL;
	nimln_(33, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = copyString(((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_2));
	nimln_(35, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	countX60gensym12_ = ((NI) 0);
	nimln_(37, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	{
		if (!(((NI) 0) < countX60gensym12_)) goto LA3_;
		result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_3));
	}
	LA3_: ;
	nimln_(39, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 6);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_4));
	nimln_(40, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_5));
	nimln_(41, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	countX60gensym12_ += ((NI) 1);
	nimln_(47, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	addQuoted__pureZos_457((&result), (*x).scheme);
	nimln_(37, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	{
		if (!(((NI) 0) < countX60gensym12_)) goto LA7_;
		result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_3));
	}
	LA7_: ;
	nimln_(39, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 8);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_6));
	nimln_(40, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_5));
	nimln_(41, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	countX60gensym12_ += ((NI) 1);
	nimln_(47, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	addQuoted__pureZos_457((&result), (*x).username);
	nimln_(37, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	{
		if (!(((NI) 0) < countX60gensym12_)) goto LA11_;
		result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_3));
	}
	LA11_: ;
	nimln_(39, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 8);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_7));
	nimln_(40, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_5));
	nimln_(41, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	countX60gensym12_ += ((NI) 1);
	nimln_(47, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	addQuoted__pureZos_457((&result), (*x).password);
	nimln_(37, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	{
		if (!(((NI) 0) < countX60gensym12_)) goto LA15_;
		result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_3));
	}
	LA15_: ;
	nimln_(39, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 8);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_8));
	nimln_(40, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_5));
	nimln_(41, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	countX60gensym12_ += ((NI) 1);
	nimln_(47, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	addQuoted__pureZos_457((&result), (*x).hostname);
	nimln_(37, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	{
		if (!(((NI) 0) < countX60gensym12_)) goto LA19_;
		result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_3));
	}
	LA19_: ;
	nimln_(39, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 4);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_9));
	nimln_(40, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_5));
	nimln_(41, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	countX60gensym12_ += ((NI) 1);
	nimln_(47, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	addQuoted__pureZos_457((&result), (*x).port);
	nimln_(37, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	{
		if (!(((NI) 0) < countX60gensym12_)) goto LA23_;
		result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_3));
	}
	LA23_: ;
	nimln_(39, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 4);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_10));
	nimln_(40, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_5));
	nimln_(41, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	countX60gensym12_ += ((NI) 1);
	nimln_(47, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	addQuoted__pureZos_457((&result), (*x).path);
	nimln_(37, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	{
		if (!(((NI) 0) < countX60gensym12_)) goto LA27_;
		result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_3));
	}
	LA27_: ;
	nimln_(39, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 5);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_11));
	nimln_(40, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_5));
	nimln_(41, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	countX60gensym12_ += ((NI) 1);
	nimln_(47, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	addQuoted__pureZos_457((&result), (*x).query);
	nimln_(37, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	{
		if (!(((NI) 0) < countX60gensym12_)) goto LA31_;
		result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_3));
	}
	LA31_: ;
	nimln_(39, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 6);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_12));
	nimln_(40, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_5));
	nimln_(41, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	countX60gensym12_ += ((NI) 1);
	nimln_(47, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	addQuoted__pureZos_457((&result), (*x).anchor);
	nimln_(37, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	{
		if (!(((NI) 0) < countX60gensym12_)) goto LA35_;
		result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_3));
	}
	LA35_: ;
	nimln_(39, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 6);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_13));
	nimln_(40, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_5));
	nimln_(41, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	countX60gensym12_ += ((NI) 1);
	nimln_(47, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	addQuoted__nimblepkgZpackageinfo_640((&result), (*x).opaque);
	nimln_(37, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	{
		if (!(((NI) 0) < countX60gensym12_)) goto LA39_;
		result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_3));
	}
	LA39_: ;
	nimln_(39, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 6);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_14));
	nimln_(40, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_5));
	nimln_(41, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	countX60gensym12_ += ((NI) 1);
	nimln_(47, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	addQuoted__nimblepkgZpackageinfo_640((&result), (*x).isIpv6);
	nimln_(53, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 1);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_15));
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar___nimble_5695)(tyObject_Checksums__aZcxVfkZCt9bd29bg29aMe9aaA x) {
	NimStringDesc* result;
	NI countX60gensym315_;
	nimfr_("$", "/home/yyoncho/Sources/nim/Nim/lib/std/objectdollar.nim");
	result = NIM_NIL;
	nimln_(33, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = copyString(((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_2));
	nimln_(35, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	countX60gensym315_ = ((NI) 0);
	nimln_(37, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	{
		if (!(((NI) 0) < countX60gensym315_)) goto LA3_;
		result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_3));
	}
	LA3_: ;
	nimln_(39, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 4);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_46));
	nimln_(40, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_5));
	nimln_(41, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	countX60gensym315_ += ((NI) 1);
	nimln_(47, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	addQuoted__nimble_5147((&result), x.sha1);
	nimln_(53, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 1);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_15));
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar___nimble_5569)(tyObject_LockFileDep__PkUOL8vzIvRRmF9bLOPRlhg* x) {
	NimStringDesc* result;
	NI countX60gensym289_;
	nimfr_("$", "/home/yyoncho/Sources/nim/Nim/lib/std/objectdollar.nim");
	result = NIM_NIL;
	nimln_(33, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = copyString(((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_2));
	nimln_(35, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	countX60gensym289_ = ((NI) 0);
	nimln_(37, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	{
		if (!(((NI) 0) < countX60gensym289_)) goto LA3_;
		result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_3));
	}
	LA3_: ;
	nimln_(39, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 7);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_40));
	nimln_(40, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_5));
	nimln_(41, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	countX60gensym289_ += ((NI) 1);
	nimln_(47, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	addQuoted__nimble_5134((&result), (*x).version);
	nimln_(37, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	{
		if (!(((NI) 0) < countX60gensym289_)) goto LA7_;
		result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_3));
	}
	LA7_: ;
	nimln_(39, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 11);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_41));
	nimln_(40, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_5));
	nimln_(41, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	countX60gensym289_ += ((NI) 1);
	nimln_(47, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	addQuoted__nimble_5147((&result), (*x).vcsRevision);
	nimln_(37, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	{
		if (!(((NI) 0) < countX60gensym289_)) goto LA11_;
		result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_3));
	}
	LA11_: ;
	nimln_(39, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 3);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_42));
	nimln_(40, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_5));
	nimln_(41, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	countX60gensym289_ += ((NI) 1);
	nimln_(47, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	addQuoted__pureZos_457((&result), (*x).url);
	nimln_(37, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	{
		if (!(((NI) 0) < countX60gensym289_)) goto LA15_;
		result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_3));
	}
	LA15_: ;
	nimln_(39, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 14);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_43));
	nimln_(40, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_5));
	nimln_(41, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	countX60gensym289_ += ((NI) 1);
	nimln_(47, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	addQuoted__nimble_5630((&result), (*x).downloadMethod);
	nimln_(37, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	{
		if (!(((NI) 0) < countX60gensym289_)) goto LA19_;
		result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_3));
	}
	LA19_: ;
	nimln_(39, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 12);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_44));
	nimln_(40, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_5));
	nimln_(41, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	countX60gensym289_ += ((NI) 1);
	nimln_(47, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	addQuoted__pureZhttpcore_2614((&result), (*x).dependencies);
	nimln_(37, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	{
		if (!(((NI) 0) < countX60gensym289_)) goto LA23_;
		result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_3));
	}
	LA23_: ;
	nimln_(39, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 9);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_45));
	nimln_(40, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_5));
	nimln_(41, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	countX60gensym289_ += ((NI) 1);
	nimln_(47, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	addQuoted__nimble_5689((&result), (*x).checksums);
	nimln_(53, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 1);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_15));
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar___nimble_5961)(tyObject_PackageMetaData__EO1rPizWROcibmAlVzA30w* x) {
	NimStringDesc* result;
	NI countX60gensym343_;
	nimfr_("$", "/home/yyoncho/Sources/nim/Nim/lib/std/objectdollar.nim");
	result = NIM_NIL;
	nimln_(33, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = copyString(((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_2));
	nimln_(35, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	countX60gensym343_ = ((NI) 0);
	nimln_(37, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	{
		if (!(((NI) 0) < countX60gensym343_)) goto LA3_;
		result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_3));
	}
	LA3_: ;
	nimln_(39, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 3);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_42));
	nimln_(40, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_5));
	nimln_(41, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	countX60gensym343_ += ((NI) 1);
	nimln_(47, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	addQuoted__pureZos_457((&result), (*x).url);
	nimln_(37, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	{
		if (!(((NI) 0) < countX60gensym343_)) goto LA7_;
		result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_3));
	}
	LA7_: ;
	nimln_(39, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 14);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_43));
	nimln_(40, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_5));
	nimln_(41, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	countX60gensym343_ += ((NI) 1);
	nimln_(47, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	addQuoted__nimble_5630((&result), (*x).downloadMethod);
	nimln_(37, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	{
		if (!(((NI) 0) < countX60gensym343_)) goto LA11_;
		result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_3));
	}
	LA11_: ;
	nimln_(39, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 11);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_41));
	nimln_(40, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_5));
	nimln_(41, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	countX60gensym343_ += ((NI) 1);
	nimln_(47, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	addQuoted__nimble_5147((&result), (*x).vcsRevision);
	nimln_(37, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	{
		if (!(((NI) 0) < countX60gensym343_)) goto LA15_;
		result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_3));
	}
	LA15_: ;
	nimln_(39, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 5);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_48));
	nimln_(40, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_5));
	nimln_(41, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	countX60gensym343_ += ((NI) 1);
	nimln_(47, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	addQuoted__pureZhttpcore_2614((&result), (*x).files);
	nimln_(37, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	{
		if (!(((NI) 0) < countX60gensym343_)) goto LA19_;
		result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_3));
	}
	LA19_: ;
	nimln_(39, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 8);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_49));
	nimln_(40, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_5));
	nimln_(41, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	countX60gensym343_ += ((NI) 1);
	nimln_(47, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	addQuoted__pureZhttpcore_2614((&result), (*x).binaries);
	nimln_(37, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	{
		if (!(((NI) 0) < countX60gensym343_)) goto LA23_;
		result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_3));
	}
	LA23_: ;
	nimln_(39, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 15);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_50));
	nimln_(40, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_5));
	nimln_(41, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	countX60gensym343_ += ((NI) 1);
	nimln_(47, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	addQuoted__nimble_6119((&result), (*x).specialVersions);
	nimln_(53, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 1);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_15));
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar___nimble_3071)(tyObject_PackageInfo__y9ahmwzrCcWrfsrJgR1q4lw* x) {
	NimStringDesc* result;
	NI countX60gensym154_;
	nimfr_("$", "/home/yyoncho/Sources/nim/Nim/lib/std/objectdollar.nim");
	result = NIM_NIL;
	nimln_(33, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = copyString(((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_2));
	nimln_(35, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	countX60gensym154_ = ((NI) 0);
	nimln_(37, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	{
		if (!(((NI) 0) < countX60gensym154_)) goto LA3_;
		result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_3));
	}
	LA3_: ;
	nimln_(39, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 6);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_16));
	nimln_(40, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_5));
	nimln_(41, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	countX60gensym154_ += ((NI) 1);
	nimln_(47, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	addQuoted__pureZos_457((&result), (*x).myPath);
	nimln_(37, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	{
		if (!(((NI) 0) < countX60gensym154_)) goto LA7_;
		result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_3));
	}
	LA7_: ;
	nimln_(39, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 11);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_17));
	nimln_(40, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_5));
	nimln_(41, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	countX60gensym154_ += ((NI) 1);
	nimln_(47, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	addQuoted__nimblepkgZpackageinfo_640((&result), (*x).isNimScript);
	nimln_(37, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	{
		if (!(((NI) 0) < countX60gensym154_)) goto LA11_;
		result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_3));
	}
	LA11_: ;
	nimln_(39, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 9);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_18));
	nimln_(40, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_5));
	nimln_(41, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	countX60gensym154_ += ((NI) 1);
	nimln_(47, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	addQuoted__nimblepkgZpackageinfo_640((&result), (*x).isMinimal);
	nimln_(37, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	{
		if (!(((NI) 0) < countX60gensym154_)) goto LA15_;
		result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_3));
	}
	LA15_: ;
	nimln_(39, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 11);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_19));
	nimln_(40, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_5));
	nimln_(41, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	countX60gensym154_ += ((NI) 1);
	nimln_(47, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	addQuoted__nimblepkgZpackageinfo_640((&result), (*x).isInstalled);
	nimln_(37, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	{
		if (!(((NI) 0) < countX60gensym154_)) goto LA19_;
		result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_3));
	}
	LA19_: ;
	nimln_(39, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 11);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_20));
	nimln_(40, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_5));
	nimln_(41, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	countX60gensym154_ += ((NI) 1);
	nimln_(47, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	addQuoted__nimble_3453((&result), (*x).nimbleTasks);
	nimln_(37, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	{
		if (!(((NI) 0) < countX60gensym154_)) goto LA23_;
		result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_3));
	}
	LA23_: ;
	nimln_(39, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 9);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_21));
	nimln_(40, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_5));
	nimln_(41, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	countX60gensym154_ += ((NI) 1);
	nimln_(47, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	addQuoted__nimble_3453((&result), (*x).postHooks);
	nimln_(37, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	{
		if (!(((NI) 0) < countX60gensym154_)) goto LA27_;
		result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_3));
	}
	LA27_: ;
	nimln_(39, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 8);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_22));
	nimln_(40, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_5));
	nimln_(41, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	countX60gensym154_ += ((NI) 1);
	nimln_(47, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	addQuoted__nimble_3453((&result), (*x).preHooks);
	nimln_(37, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	{
		if (!(((NI) 0) < countX60gensym154_)) goto LA31_;
		result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_3));
	}
	LA31_: ;
	nimln_(39, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 6);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_23));
	nimln_(40, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_5));
	nimln_(41, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	countX60gensym154_ += ((NI) 1);
	nimln_(47, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	addQuoted__pureZos_457((&result), (*x).author);
	nimln_(37, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	{
		if (!(((NI) 0) < countX60gensym154_)) goto LA35_;
		result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_3));
	}
	LA35_: ;
	nimln_(39, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 11);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_24));
	nimln_(40, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_5));
	nimln_(41, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	countX60gensym154_ += ((NI) 1);
	nimln_(47, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	addQuoted__pureZos_457((&result), (*x).description);
	nimln_(37, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	{
		if (!(((NI) 0) < countX60gensym154_)) goto LA39_;
		result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_3));
	}
	LA39_: ;
	nimln_(39, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 7);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_25));
	nimln_(40, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_5));
	nimln_(41, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	countX60gensym154_ += ((NI) 1);
	nimln_(47, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	addQuoted__pureZos_457((&result), (*x).license);
	nimln_(37, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	{
		if (!(((NI) 0) < countX60gensym154_)) goto LA43_;
		result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_3));
	}
	LA43_: ;
	nimln_(39, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 8);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_26));
	nimln_(40, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_5));
	nimln_(41, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	countX60gensym154_ += ((NI) 1);
	nimln_(47, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	addQuoted__pureZhttpcore_2614((&result), (*x).skipDirs);
	nimln_(37, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	{
		if (!(((NI) 0) < countX60gensym154_)) goto LA47_;
		result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_3));
	}
	LA47_: ;
	nimln_(39, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 9);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_27));
	nimln_(40, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_5));
	nimln_(41, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	countX60gensym154_ += ((NI) 1);
	nimln_(47, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	addQuoted__pureZhttpcore_2614((&result), (*x).skipFiles);
	nimln_(37, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	{
		if (!(((NI) 0) < countX60gensym154_)) goto LA51_;
		result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_3));
	}
	LA51_: ;
	nimln_(39, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 7);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_28));
	nimln_(40, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_5));
	nimln_(41, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	countX60gensym154_ += ((NI) 1);
	nimln_(47, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	addQuoted__pureZhttpcore_2614((&result), (*x).skipExt);
	nimln_(37, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	{
		if (!(((NI) 0) < countX60gensym154_)) goto LA55_;
		result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_3));
	}
	LA55_: ;
	nimln_(39, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 11);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_29));
	nimln_(40, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_5));
	nimln_(41, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	countX60gensym154_ += ((NI) 1);
	nimln_(47, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	addQuoted__pureZhttpcore_2614((&result), (*x).installDirs);
	nimln_(37, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	{
		if (!(((NI) 0) < countX60gensym154_)) goto LA59_;
		result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_3));
	}
	LA59_: ;
	nimln_(39, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 12);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_30));
	nimln_(40, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_5));
	nimln_(41, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	countX60gensym154_ += ((NI) 1);
	nimln_(47, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	addQuoted__pureZhttpcore_2614((&result), (*x).installFiles);
	nimln_(37, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	{
		if (!(((NI) 0) < countX60gensym154_)) goto LA63_;
		result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_3));
	}
	LA63_: ;
	nimln_(39, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 10);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_31));
	nimln_(40, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_5));
	nimln_(41, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	countX60gensym154_ += ((NI) 1);
	nimln_(47, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	addQuoted__pureZhttpcore_2614((&result), (*x).installExt);
	nimln_(37, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	{
		if (!(((NI) 0) < countX60gensym154_)) goto LA67_;
		result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_3));
	}
	LA67_: ;
	nimln_(39, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 8);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_32));
	nimln_(40, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_5));
	nimln_(41, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	countX60gensym154_ += ((NI) 1);
	nimln_(47, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	addQuoted__nimble_4063((&result), (*x).requires);
	nimln_(37, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	{
		if (!(((NI) 0) < countX60gensym154_)) goto LA71_;
		result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_3));
	}
	LA71_: ;
	nimln_(39, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 3);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_33));
	nimln_(40, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_5));
	nimln_(41, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	countX60gensym154_ += ((NI) 1);
	nimln_(47, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	addQuoted__nimble_4539((&result), (*x).bin);
	nimln_(37, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	{
		if (!(((NI) 0) < countX60gensym154_)) goto LA75_;
		result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_3));
	}
	LA75_: ;
	nimln_(39, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 6);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_34));
	nimln_(40, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_5));
	nimln_(41, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	countX60gensym154_ += ((NI) 1);
	nimln_(47, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	addQuoted__pureZos_457((&result), (*x).binDir);
	nimln_(37, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	{
		if (!(((NI) 0) < countX60gensym154_)) goto LA79_;
		result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_3));
	}
	LA79_: ;
	nimln_(39, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 6);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_35));
	nimln_(40, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_5));
	nimln_(41, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	countX60gensym154_ += ((NI) 1);
	nimln_(47, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	addQuoted__pureZos_457((&result), (*x).srcDir);
	nimln_(37, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	{
		if (!(((NI) 0) < countX60gensym154_)) goto LA83_;
		result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_3));
	}
	LA83_: ;
	nimln_(39, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 7);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_36));
	nimln_(40, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_5));
	nimln_(41, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	countX60gensym154_ += ((NI) 1);
	nimln_(47, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	addQuoted__pureZos_457((&result), (*x).backend);
	nimln_(37, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	{
		if (!(((NI) 0) < countX60gensym154_)) goto LA87_;
		result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_3));
	}
	LA87_: ;
	nimln_(39, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 11);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_37));
	nimln_(40, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_5));
	nimln_(41, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	countX60gensym154_ += ((NI) 1);
	nimln_(47, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	addQuoted__pureZhttpcore_2614((&result), (*x).foreignDeps);
	nimln_(37, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	{
		if (!(((NI) 0) < countX60gensym154_)) goto LA91_;
		result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_3));
	}
	LA91_: ;
	nimln_(39, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 9);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_38));
	nimln_(40, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_5));
	nimln_(41, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	countX60gensym154_ += ((NI) 1);
	nimln_(47, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	addQuoted__nimble_5092((&result), (*x).basicInfo);
	nimln_(37, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	{
		if (!(((NI) 0) < countX60gensym154_)) goto LA95_;
		result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_3));
	}
	LA95_: ;
	nimln_(39, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 10);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_39));
	nimln_(40, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_5));
	nimln_(41, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	countX60gensym154_ += ((NI) 1);
	nimln_(47, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	addQuoted__nimble_5426((&result), (&(*x).lockedDeps));
	nimln_(37, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	{
		if (!(((NI) 0) < countX60gensym154_)) goto LA99_;
		result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_3));
	}
	LA99_: ;
	nimln_(39, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 8);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_47));
	nimln_(40, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_5));
	nimln_(41, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	countX60gensym154_ += ((NI) 1);
	nimln_(47, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	addQuoted__nimble_5955((&result), (&(*x).metaData));
	nimln_(37, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	{
		if (!(((NI) 0) < countX60gensym154_)) goto LA103_;
		result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_3));
	}
	LA103_: ;
	nimln_(39, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 6);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_51));
	nimln_(40, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_5));
	nimln_(41, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	countX60gensym154_ += ((NI) 1);
	nimln_(47, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	addQuoted__nimblepkgZpackageinfo_640((&result), (*x).isLink);
	nimln_(53, "/home/yyoncho/Sources/nim/Nim/lib/std/private/miscdollars.nim");
	result = resizeString(result, 1);
appendString(result, ((NimStringDesc*) &TM__US7tUPSVHwyWbwv9cB5DrpQ_15));
	popFrame();
	return result;
}
