/* Generated by Nim Compiler v1.7.1 */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <stdio.h>
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NIM_CHAR tyArray__eVNFTutn6un5gcq48fQLdg[65];
N_LIB_PRIVATE N_NIMCALL(NI, writeFloatToBufferSprintf__stdZformatfloat_59)(NIM_CHAR* buf, NF value);
N_LIB_PRIVATE N_NIMCALL(void, writeToBuffer__stdZformatfloat_51)(NIM_CHAR* buf, NCSTRING value);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_3527)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void, addCstringN__stdZformatfloat_5)(NimStringDesc** result, NCSTRING buf, NI buflen);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, setLengthStr)(NimStringDesc* s, NI newLen);
N_LIB_PRIVATE N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
extern NIM_THREADVAR TFrame* framePtr__system_3094;
extern NIM_THREADVAR TFrame* framePtr__system_3094;
extern NIM_THREADVAR TFrame* framePtr__system_3094;
extern NIM_THREADVAR TFrame* framePtr__system_3094;
extern NIM_THREADVAR TFrame* framePtr__system_3094;
extern NIM_THREADVAR TFrame* framePtr__system_3094;
static N_INLINE(void, nimFrame)(TFrame* s) {
	{
		if (!(framePtr__system_3094 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s).calldepth = ((NI16) 0);
	}
	goto LA1_;
	LA3_: ;
	{
		(*s).calldepth = (NI16)((*framePtr__system_3094).calldepth + ((NI16) 1));
	}
	LA1_: ;
	(*s).prev = framePtr__system_3094;
	framePtr__system_3094 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;
		callDepthLimitReached__system_3527();
	}
	LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_3094 = (*framePtr__system_3094).prev;
}
N_LIB_PRIVATE N_NIMCALL(void, writeToBuffer__stdZformatfloat_51)(NIM_CHAR* buf, NCSTRING value) {
	NI i;
	nimfr_("writeToBuffer", "/home/yyoncho/Sources/nim/Nim/lib/std/formatfloat.nim");
	nimln_(42, "/home/yyoncho/Sources/nim/Nim/lib/std/formatfloat.nim");
	i = ((NI) 0);
	{
		nimln_(43, "/home/yyoncho/Sources/nim/Nim/lib/std/formatfloat.nim");
		while (1) {
			if (!!(((NU8)(value[i]) == (NU8)(0)))) goto LA2;
			nimln_(44, "/home/yyoncho/Sources/nim/Nim/lib/std/formatfloat.nim");
			buf[(i)- 0] = value[i];
			nimln_(45, "/home/yyoncho/Sources/nim/Nim/lib/std/formatfloat.nim");
			i += ((NI) 1);
		} LA2: ;
	}
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(NI, writeFloatToBufferSprintf__stdZformatfloat_59)(NIM_CHAR* buf, NF value) {
	NI result;
	NI n;
	int T1_;
	NIM_BOOL hasDot;
	nimfr_("writeFloatToBufferSprintf", "/home/yyoncho/Sources/nim/Nim/lib/std/formatfloat.nim");
	result = (NI)0;
	nimln_(52, "/home/yyoncho/Sources/nim/Nim/lib/std/formatfloat.nim");
	T1_ = (int)0;
	T1_ = sprintf(((NCSTRING) (buf)), "%.16g", value);
	n = ((NI) (T1_));
	nimln_(53, "/home/yyoncho/Sources/nim/Nim/lib/std/formatfloat.nim");
	hasDot = NIM_FALSE;
	{
		NI i;
		NI colontmp_;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		nimln_(54, "/home/yyoncho/Sources/nim/Nim/lib/std/formatfloat.nim");
		colontmp_ = (NI)(n - ((NI) 1));
		nimln_(90, "/home/yyoncho/Sources/nim/Nim/lib/system/iterators_1.nim");
		res = ((NI) 0);
		{
			nimln_(91, "/home/yyoncho/Sources/nim/Nim/lib/system/iterators_1.nim");
			while (1) {
				if (!(res <= colontmp_)) goto LA4;
				nimln_(54, "/home/yyoncho/Sources/nim/Nim/lib/std/formatfloat.nim");
				i = res;
				{
					nimln_(55, "/home/yyoncho/Sources/nim/Nim/lib/std/formatfloat.nim");
					if (!((NU8)(buf[(i)- 0]) == (NU8)(44))) goto LA7_;
					nimln_(56, "/home/yyoncho/Sources/nim/Nim/lib/std/formatfloat.nim");
					buf[(i)- 0] = 46;
					nimln_(57, "/home/yyoncho/Sources/nim/Nim/lib/std/formatfloat.nim");
					hasDot = NIM_TRUE;
				}
				goto LA5_;
				LA7_: ;
				{
					nimln_(58, "/home/yyoncho/Sources/nim/Nim/lib/std/formatfloat.nim");
					if (!(((NU8)(buf[(i)- 0])) >= ((NU8)(97)) && ((NU8)(buf[(i)- 0])) <= ((NU8)(122)) || ((NU8)(buf[(i)- 0])) >= ((NU8)(65)) && ((NU8)(buf[(i)- 0])) <= ((NU8)(90)) || ((NU8)(buf[(i)- 0])) == ((NU8)(46)))) goto LA10_;
					nimln_(59, "/home/yyoncho/Sources/nim/Nim/lib/std/formatfloat.nim");
					hasDot = NIM_TRUE;
				}
				goto LA5_;
				LA10_: ;
				LA5_: ;
				nimln_(93, "/home/yyoncho/Sources/nim/Nim/lib/system/iterators_1.nim");
				res += ((NI) 1);
			} LA4: ;
		}
	}
	nimln_(60, "/home/yyoncho/Sources/nim/Nim/lib/std/formatfloat.nim");
	{
		if (!!(hasDot)) goto LA14_;
		nimln_(61, "/home/yyoncho/Sources/nim/Nim/lib/std/formatfloat.nim");
		buf[(n)- 0] = 46;
		nimln_(62, "/home/yyoncho/Sources/nim/Nim/lib/std/formatfloat.nim");
		buf[((NI)(n + ((NI) 1)))- 0] = 48;
		nimln_(63, "/home/yyoncho/Sources/nim/Nim/lib/std/formatfloat.nim");
		buf[((NI)(n + ((NI) 2)))- 0] = 0;
		nimln_(64, "/home/yyoncho/Sources/nim/Nim/lib/std/formatfloat.nim");
		result = (NI)(n + ((NI) 2));
	}
	goto LA12_;
	LA14_: ;
	{
		nimln_(66, "/home/yyoncho/Sources/nim/Nim/lib/std/formatfloat.nim");
		result = n;
	}
	LA12_: ;
	nimln_(70, "/home/yyoncho/Sources/nim/Nim/lib/std/formatfloat.nim");
	{
		if (!(((NU8)(buf[((NI)(n - ((NI) 1)))- 0])) == ((NU8)(110)) || ((NU8)(buf[((NI)(n - ((NI) 1)))- 0])) == ((NU8)(78)) || ((NU8)(buf[((NI)(n - ((NI) 1)))- 0])) == ((NU8)(68)) || ((NU8)(buf[((NI)(n - ((NI) 1)))- 0])) == ((NU8)(100)) || ((NU8)(buf[((NI)(n - ((NI) 1)))- 0])) == ((NU8)(41)))) goto LA19_;
		nimln_(71, "/home/yyoncho/Sources/nim/Nim/lib/std/formatfloat.nim");
		writeToBuffer__stdZformatfloat_51(buf, "nan");
		nimln_(72, "/home/yyoncho/Sources/nim/Nim/lib/std/formatfloat.nim");
		result = ((NI) 3);
	}
	goto LA17_;
	LA19_: ;
	{
		nimln_(73, "/home/yyoncho/Sources/nim/Nim/lib/std/formatfloat.nim");
		if (!((NU8)(buf[((NI)(n - ((NI) 1)))- 0]) == (NU8)(70))) goto LA22_;
		nimln_(74, "/home/yyoncho/Sources/nim/Nim/lib/std/formatfloat.nim");
		{
			if (!((NU8)(buf[(((NI) 0))- 0]) == (NU8)(45))) goto LA26_;
			nimln_(75, "/home/yyoncho/Sources/nim/Nim/lib/std/formatfloat.nim");
			writeToBuffer__stdZformatfloat_51(buf, "-inf");
			nimln_(76, "/home/yyoncho/Sources/nim/Nim/lib/std/formatfloat.nim");
			result = ((NI) 4);
		}
		goto LA24_;
		LA26_: ;
		{
			nimln_(78, "/home/yyoncho/Sources/nim/Nim/lib/std/formatfloat.nim");
			writeToBuffer__stdZformatfloat_51(buf, "inf");
			nimln_(79, "/home/yyoncho/Sources/nim/Nim/lib/std/formatfloat.nim");
			result = ((NI) 3);
		}
		LA24_: ;
	}
	goto LA17_;
	LA22_: ;
	LA17_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, addCstringN__stdZformatfloat_5)(NimStringDesc** result, NCSTRING buf, NI buflen) {
	NI oldLen;
	NI newLen;
	void* T1_;
	nimfr_("addCstringN", "/home/yyoncho/Sources/nim/Nim/lib/std/formatfloat.nim");
	nimln_(19, "/home/yyoncho/Sources/nim/Nim/lib/std/formatfloat.nim");
	oldLen = ((*result) ? (*result)->Sup.len : 0);
	nimln_(20, "/home/yyoncho/Sources/nim/Nim/lib/std/formatfloat.nim");
	newLen = (NI)(oldLen + buflen);
	nimln_(21, "/home/yyoncho/Sources/nim/Nim/lib/std/formatfloat.nim");
	unsureAsgnRef((void**) (&(*result)), setLengthStr((*result), ((NI) (newLen))));
	nimln_(22, "/home/yyoncho/Sources/nim/Nim/lib/std/formatfloat.nim");
	T1_ = (void*)0;
	T1_ = memcpy(((void*) ((&(*result)->data[oldLen]))), ((void*) (buf)), ((size_t) (buflen)));
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, addFloatSprintf__stdZformatfloat_99)(NimStringDesc** result, NF x) {
	tyArray__eVNFTutn6un5gcq48fQLdg buffer;
	NI n;
	nimfr_("addFloatSprintf", "/home/yyoncho/Sources/nim/Nim/lib/std/formatfloat.nim");
	nimln_(100, "/home/yyoncho/Sources/nim/Nim/lib/std/formatfloat.nim");
	n = writeFloatToBufferSprintf__stdZformatfloat_59(buffer, x);
	nimln_(101, "/home/yyoncho/Sources/nim/Nim/lib/std/formatfloat.nim");
	addCstringN__stdZformatfloat_5(result, ((NCSTRING) ((&buffer[(((NI) 0))- 0]))), n);
	popFrame();
}
