/* Generated by Nim Compiler v1.7.1 */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <sys/types.h>
                          #include <pthread.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  typedef struct tyObject_SyncFile__QCQR8mK9aWVe5sIf5qaOAyw tyObject_SyncFile__QCQR8mK9aWVe5sIf5qaOAyw;
typedef struct tyObject_PackageInfo__y9ahmwzrCcWrfsrJgR1q4lw tyObject_PackageInfo__y9ahmwzrCcWrfsrJgR1q4lw;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyTuple__7q7q3E6Oj24ZNVJb9aonhAg tyTuple__7q7q3E6Oj24ZNVJb9aonhAg;
typedef struct tyObject_HashSet__CD8Dpv0WGmASelVaNSo6zg tyObject_HashSet__CD8Dpv0WGmASelVaNSo6zg;
typedef struct tySequence__4eRCaZmrYLLw2k30GPTiMw tySequence__4eRCaZmrYLLw2k30GPTiMw;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ tySequence__sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tySequence__kLwf9aGQcuduFr4gekUDa2w tySequence__kLwf9aGQcuduFr4gekUDa2w;
typedef struct tyObject_Table__Ji6x6JQ0gVMaFr8AIk18Ug tyObject_Table__Ji6x6JQ0gVMaFr8AIk18Ug;
typedef struct tySequence__SFipDZIkFtPcrLs0AGBBjQ tySequence__SFipDZIkFtPcrLs0AGBBjQ;
typedef struct tyTuple__BjxoJYFE5BulbiU15SM6nQ tyTuple__BjxoJYFE5BulbiU15SM6nQ;
typedef struct tyObject_Version__9bU0a4Oqtl9aJmGyzYi8ZnBA tyObject_Version__9bU0a4Oqtl9aJmGyzYi8ZnBA;
typedef struct tyObject_Sha1Hash__zQwLVDNef3gJr9bhL9bRloJw tyObject_Sha1Hash__zQwLVDNef3gJr9bhL9bRloJw;
typedef struct tyObject_OrderedTable__b2SAayIK9c6IoZnFt9cutJhQ tyObject_OrderedTable__b2SAayIK9c6IoZnFt9cutJhQ;
typedef struct tySequence__ZkxkVxJvB9aqet9cfVQmFTZw tySequence__ZkxkVxJvB9aqet9cfVQmFTZw;
typedef struct tyObject_PackageMetaData__EO1rPizWROcibmAlVzA30w tyObject_PackageMetaData__EO1rPizWROcibmAlVzA30w;
typedef struct tyObject_HashSet__aCgx9aJWOlGNhL9b41LIC4Wg tyObject_HashSet__aCgx9aJWOlGNhL9b41LIC4Wg;
typedef struct tySequence__72hOjuY2LKiowAwLCg19a9bA tySequence__72hOjuY2LKiowAwLCg19a9bA;
typedef struct tyObject_Table__VvMOAkURzpFunhIRpm9cltw tyObject_Table__VvMOAkURzpFunhIRpm9cltw;
typedef struct tySequence__STVJgEyfAvX2CARt9c1e3sQ tySequence__STVJgEyfAvX2CARt9c1e3sQ;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyTuple__EceTD9cyFJax4VWMFZt7qAg tyTuple__EceTD9cyFJax4VWMFZt7qAg;
typedef struct tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack__7fytPA5bBsob6See21YMRA tyObject_GcStack__7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple__ujsjpB2O9cjj3uDHsXbnSzg tyTuple__ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_SharedList__JI9cx34TL8n3aOKF6tSMBUw tyObject_SharedList__JI9cx34TL8n3aOKF6tSMBUw;
typedef struct tyObject_SharedListNodecolonObjectType___KGw0YAw6W9aSz3Sr9aXGu7zg tyObject_SharedListNodecolonObjectType___KGw0YAw6W9aSz3Sr9aXGu7zg;
typedef struct tyTuple__Ufuqy1K6JyDSHZP03DOtDA tyTuple__Ufuqy1K6JyDSHZP03DOtDA;
typedef struct tyObject_NimbleError__6rmfqzY5PO7blXdlEs8gjQ tyObject_NimbleError__6rmfqzY5PO7blXdlEs8gjQ;
typedef struct tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA tySequence__uB9b75OUPRENsBAu4AnoePA;
typedef struct tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q;
typedef struct tyObject_OrderedTable__ZZvSdVkA2s2sIyifu4cpkg tyObject_OrderedTable__ZZvSdVkA2s2sIyifu4cpkg;
typedef struct tySequence__MlAD6nAPq9bHKla9cWiIZP0g tySequence__MlAD6nAPq9bHKla9cWiIZP0g;
typedef struct tySequence__oLpBKXzW3hF9aCVMo5EymfQ tySequence__oLpBKXzW3hF9aCVMo5EymfQ;
typedef struct tyTuple__jq7X5k7hWG0tdTZTDkiyGQ tyTuple__jq7X5k7hWG0tdTZTDkiyGQ;
typedef struct tyTuple__QeWl6B6ffS4pU6WWrtcrDw tyTuple__QeWl6B6ffS4pU6WWrtcrDw;
typedef struct tyTuple__gDWaEqPfhOauJWKMBm8bzg tyTuple__gDWaEqPfhOauJWKMBm8bzg;
typedef struct tyObject_VersionRangeObj__FrJQzed5Yezqp6gCbEyg0w tyObject_VersionRangeObj__FrJQzed5Yezqp6gCbEyg0w;
typedef struct tyTuple__8ZxhPt1NwfElsJs8zUSV9bg tyTuple__8ZxhPt1NwfElsJs8zUSV9bg;
typedef struct tyTuple__m8l9a4rYFktlUTIniXgnvog tyTuple__m8l9a4rYFktlUTIniXgnvog;
typedef struct tyObject_LockFileDep__PkUOL8vzIvRRmF9bLOPRlhg tyObject_LockFileDep__PkUOL8vzIvRRmF9bLOPRlhg;
typedef struct tyObject_Checksums__aZcxVfkZCt9bd29bg29aMe9aaA tyObject_Checksums__aZcxVfkZCt9bd29bg29aMe9aaA;
typedef struct tyTuple__r1NtfsBxxsYs1cV48P1DyA tyTuple__r1NtfsBxxsYs1cV48P1DyA;
typedef struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA;
typedef struct tyTuple__awOivLjlO76sGdHY7nQUjQ tyTuple__awOivLjlO76sGdHY7nQUjQ;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyObject_HashSet__CD8Dpv0WGmASelVaNSo6zg {
tySequence__4eRCaZmrYLLw2k30GPTiMw* data;
NI counter;
};
struct tyObject_Table__Ji6x6JQ0gVMaFr8AIk18Ug {
tySequence__SFipDZIkFtPcrLs0AGBBjQ* data;
NI counter;
};
struct tyObject_Version__9bU0a4Oqtl9aJmGyzYi8ZnBA {
NimStringDesc* version;
};
struct tyObject_Sha1Hash__zQwLVDNef3gJr9bhL9bRloJw {
NimStringDesc* hashValue;
};
struct tyTuple__BjxoJYFE5BulbiU15SM6nQ {
NimStringDesc* Field0;
tyObject_Version__9bU0a4Oqtl9aJmGyzYi8ZnBA Field1;
tyObject_Sha1Hash__zQwLVDNef3gJr9bhL9bRloJw Field2;
};
struct tyObject_OrderedTable__b2SAayIK9c6IoZnFt9cutJhQ {
tySequence__ZkxkVxJvB9aqet9cfVQmFTZw* data;
NI counter;
NI first;
NI last;
};
typedef NU8 tyEnum_DownloadMethod__IqkMKe5PGkzDG0ayIWPJ6w;
struct tyObject_HashSet__aCgx9aJWOlGNhL9b41LIC4Wg {
tySequence__72hOjuY2LKiowAwLCg19a9bA* data;
NI counter;
};
struct tyObject_PackageMetaData__EO1rPizWROcibmAlVzA30w {
NimStringDesc* url;
tyEnum_DownloadMethod__IqkMKe5PGkzDG0ayIWPJ6w downloadMethod;
tyObject_Sha1Hash__zQwLVDNef3gJr9bhL9bRloJw vcsRevision;
tySequence__sM4lkSb7zS6F7OVMvW9cffQ* files;
tySequence__sM4lkSb7zS6F7OVMvW9cffQ* binaries;
tyObject_HashSet__aCgx9aJWOlGNhL9b41LIC4Wg specialVersions;
};
struct tyObject_PackageInfo__y9ahmwzrCcWrfsrJgR1q4lw {
NimStringDesc* myPath;
NIM_BOOL isNimScript;
NIM_BOOL isMinimal;
NIM_BOOL isInstalled;
tyObject_HashSet__CD8Dpv0WGmASelVaNSo6zg nimbleTasks;
tyObject_HashSet__CD8Dpv0WGmASelVaNSo6zg postHooks;
tyObject_HashSet__CD8Dpv0WGmASelVaNSo6zg preHooks;
NimStringDesc* author;
NimStringDesc* description;
NimStringDesc* license;
tySequence__sM4lkSb7zS6F7OVMvW9cffQ* skipDirs;
tySequence__sM4lkSb7zS6F7OVMvW9cffQ* skipFiles;
tySequence__sM4lkSb7zS6F7OVMvW9cffQ* skipExt;
tySequence__sM4lkSb7zS6F7OVMvW9cffQ* installDirs;
tySequence__sM4lkSb7zS6F7OVMvW9cffQ* installFiles;
tySequence__sM4lkSb7zS6F7OVMvW9cffQ* installExt;
tySequence__kLwf9aGQcuduFr4gekUDa2w* requires;
tyObject_Table__Ji6x6JQ0gVMaFr8AIk18Ug bin;
NimStringDesc* binDir;
NimStringDesc* srcDir;
NimStringDesc* backend;
tySequence__sM4lkSb7zS6F7OVMvW9cffQ* foreignDeps;
tyTuple__BjxoJYFE5BulbiU15SM6nQ basicInfo;
tyObject_OrderedTable__b2SAayIK9c6IoZnFt9cutJhQ lockedDeps;
tyObject_PackageMetaData__EO1rPizWROcibmAlVzA30w metaData;
NIM_BOOL isLink;
};
struct tyTuple__7q7q3E6Oj24ZNVJb9aonhAg {
NimStringDesc* Field0;
NimStringDesc* Field1;
NimStringDesc* Field2;
};
struct tyObject_Table__VvMOAkURzpFunhIRpm9cltw {
tySequence__STVJgEyfAvX2CARt9c1e3sQ* data;
NI counter;
};
struct tyObject_SyncFile__QCQR8mK9aWVe5sIf5qaOAyw {
NimStringDesc* path;
tyObject_Table__VvMOAkURzpFunhIRpm9cltw data;
};
typedef NU8 tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc__ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
NI align;
tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc__ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tyTuple__EceTD9cyFJax4VWMFZt7qAg {
NI Field0;
NimStringDesc* Field1;
tyObject_Sha1Hash__zQwLVDNef3gJr9bhL9bRloJw Field2;
};
typedef N_NIMCALL_PTR(void, tyProc__T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
struct tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack__7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ* tyArray__SPr7N6UKfuF549bNPiUvSRw[256];
typedef NU32 tyArray__BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg* tyArray__N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray__N1u1nqOgmuJN9cSZrnMHgOQ tyArray__B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw* tyArray__lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA {
tyArray__lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* tyArray__0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw {
tyArray__0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple__ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple__ujsjpB2O9cjj3uDHsXbnSzg tyArray__LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray__LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray__SPr7N6UKfuF549bNPiUvSRw freeSmallChunks;
NU32 flBitmap;
tyArray__BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray__B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg** data;
};
typedef long tyArray__xDUyu9aScDpt0JZLU6q9aEZQ[5];
struct tyObject_SharedList__JI9cx34TL8n3aOKF6tSMBUw {
tyObject_SharedListNodecolonObjectType___KGw0YAw6W9aSz3Sr9aXGu7zg* head;
tyObject_SharedListNodecolonObjectType___KGw0YAw6W9aSz3Sr9aXGu7zg* tail;
pthread_mutex_t lock;
};
struct tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack__7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
NI zctThreshold;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w additionalRoots;
tyObject_SharedList__JI9cx34TL8n3aOKF6tSMBUw toDispose;
NI gcThreadId;
};
typedef NU8 tyEnum_VcsType__9cvWH7gVtmHmofFRFC7AgKg;
struct tyTuple__Ufuqy1K6JyDSHZP03DOtDA {
tyEnum_VcsType__9cvWH7gVtmHmofFRFC7AgKg Field0;
NimStringDesc* Field1;
};
struct RootObj {
TNimType* m_type;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence__uB9b75OUPRENsBAu4AnoePA* trace;
Exception* up;
};
typedef NU8 tyEnum_JsonNodeKind__RUngo7nCHe6O8aBGIcrhtg;
struct tyObject_OrderedTable__ZZvSdVkA2s2sIyifu4cpkg {
tySequence__MlAD6nAPq9bHKla9cWiIZP0g* data;
NI counter;
NI first;
NI last;
};
struct tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q {
NIM_BOOL isUnquoted;
tyEnum_JsonNodeKind__RUngo7nCHe6O8aBGIcrhtg kind;
union{
struct {NimStringDesc* str;
} _kind_1;
struct {NI64 num;
} _kind_2;
struct {NF fnum;
} _kind_3;
struct {NIM_BOOL bval;
} _kind_4;
struct {tyObject_OrderedTable__ZZvSdVkA2s2sIyifu4cpkg fields;
} _kind_6;
struct {tySequence__oLpBKXzW3hF9aCVMo5EymfQ* elems;
} _kind_7;
};
};
struct tyTuple__jq7X5k7hWG0tdTZTDkiyGQ {
NimStringDesc* Field0;
tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* Field1;
};
typedef tyTuple__jq7X5k7hWG0tdTZTDkiyGQ tyArray__rnBfBeuXQMeTae3dUyC1Bw[2];
struct tyTuple__QeWl6B6ffS4pU6WWrtcrDw {
NI Field0;
NimStringDesc* Field1;
};
struct tyTuple__gDWaEqPfhOauJWKMBm8bzg {
NimStringDesc* Field0;
tyObject_VersionRangeObj__FrJQzed5Yezqp6gCbEyg0w* Field1;
};
struct tyTuple__8ZxhPt1NwfElsJs8zUSV9bg {
NI Field0;
NimStringDesc* Field1;
NimStringDesc* Field2;
};
struct tyObject_Checksums__aZcxVfkZCt9bd29bg29aMe9aaA {
tyObject_Sha1Hash__zQwLVDNef3gJr9bhL9bRloJw sha1;
};
struct tyObject_LockFileDep__PkUOL8vzIvRRmF9bLOPRlhg {
tyObject_Version__9bU0a4Oqtl9aJmGyzYi8ZnBA version;
tyObject_Sha1Hash__zQwLVDNef3gJr9bhL9bRloJw vcsRevision;
NimStringDesc* url;
tyEnum_DownloadMethod__IqkMKe5PGkzDG0ayIWPJ6w downloadMethod;
tySequence__sM4lkSb7zS6F7OVMvW9cffQ* dependencies;
tyObject_Checksums__aZcxVfkZCt9bd29bg29aMe9aaA checksums;
};
struct tyTuple__m8l9a4rYFktlUTIniXgnvog {
NI Field0;
NI Field1;
NimStringDesc* Field2;
tyObject_LockFileDep__PkUOL8vzIvRRmF9bLOPRlhg Field3;
};
struct tyTuple__r1NtfsBxxsYs1cV48P1DyA {
NI Field0;
tyObject_Version__9bU0a4Oqtl9aJmGyzYi8ZnBA Field1;
};
struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tyTuple__awOivLjlO76sGdHY7nQUjQ {
NI Field0;
NI Field1;
NimStringDesc* Field2;
tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* Field3;
};
struct tySequence__STVJgEyfAvX2CARt9c1e3sQ {
  TGenericSeq Sup;
  tyTuple__EceTD9cyFJax4VWMFZt7qAg data[SEQ_DECL_SIZE];
};
struct tySequence__4eRCaZmrYLLw2k30GPTiMw {
  TGenericSeq Sup;
  tyTuple__QeWl6B6ffS4pU6WWrtcrDw data[SEQ_DECL_SIZE];
};
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct tySequence__kLwf9aGQcuduFr4gekUDa2w {
  TGenericSeq Sup;
  tyTuple__gDWaEqPfhOauJWKMBm8bzg data[SEQ_DECL_SIZE];
};
struct tySequence__SFipDZIkFtPcrLs0AGBBjQ {
  TGenericSeq Sup;
  tyTuple__8ZxhPt1NwfElsJs8zUSV9bg data[SEQ_DECL_SIZE];
};
struct tySequence__ZkxkVxJvB9aqet9cfVQmFTZw {
  TGenericSeq Sup;
  tyTuple__m8l9a4rYFktlUTIniXgnvog data[SEQ_DECL_SIZE];
};
struct tySequence__72hOjuY2LKiowAwLCg19a9bA {
  TGenericSeq Sup;
  tyTuple__r1NtfsBxxsYs1cV48P1DyA data[SEQ_DECL_SIZE];
};
struct tySequence__uB9b75OUPRENsBAu4AnoePA {
  TGenericSeq Sup;
  tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};
struct tySequence__MlAD6nAPq9bHKla9cWiIZP0g {
  TGenericSeq Sup;
  tyTuple__awOivLjlO76sGdHY7nQUjQ data[SEQ_DECL_SIZE];
};
struct tySequence__oLpBKXzW3hF9aCVMo5EymfQ {
  TGenericSeq Sup;
  tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, getPkgDir__nimblepkgZsyncfile_28)(tyObject_PackageInfo__y9ahmwzrCcWrfsrJgR1q4lw* pkgInfo);
N_LIB_PRIVATE N_NIMCALL(void, nossplitFile)(NimStringDesc* path, tyTuple__7q7q3E6Oj24ZNVJb9aonhAg* Result);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_3527)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nosgetCurrentDir)(void);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(NIM_BOOL, equalMem__system_1735)(void* a, void* b, NI size);
static N_INLINE(int, nimCmpMem)(void* a, void* b, NI size);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__stdZassertions_56)(NimStringDesc* msg);
N_LIB_PRIVATE N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tySequence__STVJgEyfAvX2CARt9c1e3sQ)(void* p, NI op);
static N_NIMCALL(void, Marker_tyRef__BlUM5f9bGV5nhGHp3NWaILA)(void* p, NI op);
static N_NIMCALL(void, TM__x69btdbGiHm9an9b8Y9aIGrQzg_6)(void);
N_LIB_PRIVATE N_NIMCALL(void, nimRegisterGlobalMarker)(tyProc__T4eqaYlFJYZUv9aG9b1TV0bQ markerProc);
static N_INLINE(void, nimGCunrefRC1)(void* p);
static N_INLINE(void, decRef__system_5905)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(NI, minuspercent___system_716)(NI x, NI y);
static N_INLINE(NIM_BOOL, ltpercent___system_1005)(NI x, NI y);
static N_INLINE(void, rtlAddZCT__system_5903)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT__system_5854)(tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell__system_5860)(void* usr);
N_LIB_PRIVATE N_NOINLINE(void*, newObjRC1)(TNimType* typ, NI size);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, getSyncFilePath__nimblepkgZsyncfile_31)(tyObject_PackageInfo__y9ahmwzrCcWrfsrJgR1q4lw* pkgInfo);
N_LIB_PRIVATE N_NIMCALL(void, getVcsTypeAndSpecialDirPath__nimblepkgZvcstools_74)(NimStringDesc* dir, tyTuple__Ufuqy1K6JyDSHZP03DOtDA* Result);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, toPath__nimblepkgZpaths_5)(NimStringDesc* path);
N_LIB_PRIVATE N_NIMCALL(tyObject_NimbleError__6rmfqzY5PO7blXdlEs8gjQ*, nimbleError__nimblepkgZcommon_26)(NimStringDesc* msg, NimStringDesc* hint, tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA* details);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e, NCSTRING ename, NCSTRING procname, NCSTRING filename, NI line);
static N_INLINE(NimStringDesc*, slash___pureZos_121)(NimStringDesc* head, NimStringDesc* tail);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nosjoinPath)(NimStringDesc* head, NimStringDesc* tail);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem__system_1727)(void* dest, void* source, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_LIB_PRIVATE N_NIMCALL(void, load__nimblepkgZsyncfile_40)(tyObject_SyncFile__QCQR8mK9aWVe5sIf5qaOAyw* syncFile, NimStringDesc* path);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nosfileExists)(NimStringDesc* filename);
N_LIB_PRIVATE N_NIMCALL(void, to__nimblepkgZsyncfile_46)(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* node, tyObject_Table__VvMOAkURzpFunhIRpm9cltw* Result);
static N_INLINE(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q*, X5BX5D___pureZjson_3069)(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* node, NimStringDesc* name);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q**, X5BX5D___pureZjson_2663)(tyObject_OrderedTable__ZZvSdVkA2s2sIyifu4cpkg* t, NimStringDesc* key);
N_LIB_PRIVATE N_NOINLINE(void, raiseFieldError2)(NimStringDesc* f, NimStringDesc* discVal);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, reprDiscriminant)(NI e, TNimType* typ);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q*, parseFile__pureZjson_5297)(NimStringDesc* filename);
N_LIB_PRIVATE N_NIMCALL(void, clear__nimblepkgZsyncfile_2227)(tyObject_Table__VvMOAkURzpFunhIRpm9cltw* t);
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq___nimblepkgZsyncfile_1977)(tyObject_Table__VvMOAkURzpFunhIRpm9cltw* t, NimStringDesc* key, tyObject_Sha1Hash__zQwLVDNef3gJr9bhL9bRloJw val);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q*, percent___pureZjson_1831)(tyTuple__jq7X5k7hWG0tdTZTDkiyGQ* keyVals, NI keyValsLen_0);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q*, percent___pureZjson_1812)(NI n);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q*, percent___nimblepkgZsyncfile_1485)(tyObject_Table__VvMOAkURzpFunhIRpm9cltw table);
N_LIB_PRIVATE N_NIMCALL(void, writeFile__stdZsyncio_477)(NimStringDesc* filename, NimStringDesc* content);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, pretty__pureZjson_4514)(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* node, NI indent);
N_LIB_PRIVATE N_NIMCALL(void, getOrDefault__nimblepkgZsyncfile_1863)(tyObject_Table__VvMOAkURzpFunhIRpm9cltw t, NimStringDesc* key, tyObject_Sha1Hash__zQwLVDNef3gJr9bhL9bRloJw default_0, tyObject_Sha1Hash__zQwLVDNef3gJr9bhL9bRloJw* Result);
N_LIB_PRIVATE N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
STRING_LITERAL(TM__x69btdbGiHm9an9b8Y9aIGrQzg_2, "/home/yyoncho/Sources/nim/nimble/src/nimblepkg/syncfile.nim(72, 10) `pkgInfo.getPkgDir == getCurrentDir()` The package `pkgInfo` must be the current working directory package.", 175);
N_LIB_PRIVATE TNimType NTIsyncfile__QCQR8mK9aWVe5sIf5qaOAyw_;
extern TNimType NTIstring__77mFvmsOLKik79ci2hXkHEg_;
N_LIB_PRIVATE TNimType NTItable__VvMOAkURzpFunhIRpm9cltw_;
N_LIB_PRIVATE TNimType NTIkeyvaluepair__EceTD9cyFJax4VWMFZt7qAg_;
extern TNimType NTIint__rR5Bzr1D5krxoo1NcNyeMA_;
extern TNimType NTIsha49hash__zQwLVDNef3gJr9bhL9bRloJw_;
N_LIB_PRIVATE TNimType NTIkeyvaluepairseq__STVJgEyfAvX2CARt9c1e3sQ_;
N_LIB_PRIVATE TNimType NTIrefsyncfile__BlUM5f9bGV5nhGHp3NWaILA_;
STRING_LITERAL(TM__x69btdbGiHm9an9b8Y9aIGrQzg_7, "Sync file require current working directory to be under some supported type of version control.", 95);
STRING_LITERAL(TM__x69btdbGiHm9an9b8Y9aIGrQzg_8, "Put package\'s working directory under version control.", 54);
STRING_LITERAL(TM__x69btdbGiHm9an9b8Y9aIGrQzg_9, ".nimble.sync", 12);
STRING_LITERAL(TM__x69btdbGiHm9an9b8Y9aIGrQzg_10, "/home/yyoncho/Sources/nim/Nim/lib/pure/json.nim(512, 9) `not isNil(node)` ", 74);
STRING_LITERAL(TM__x69btdbGiHm9an9b8Y9aIGrQzg_11, "/home/yyoncho/Sources/nim/Nim/lib/pure/json.nim(513, 9) `node.kind == JObject` ", 79);
STRING_LITERAL(TM__x69btdbGiHm9an9b8Y9aIGrQzg_12, "field \'fields\' is not accessible for type \'JsonNodeObj\' using \'kind = ", 70);
extern TNimType NTIjsonnodekind__RUngo7nCHe6O8aBGIcrhtg_;
STRING_LITERAL(TM__x69btdbGiHm9an9b8Y9aIGrQzg_13, "data", 4);
STRING_LITERAL(TM__x69btdbGiHm9an9b8Y9aIGrQzg_14, "version", 7);
extern NIM_CONST tyObject_Sha1Hash__zQwLVDNef3gJr9bhL9bRloJw notSetSha1Hash__nimblepkgZsha49hashes_10;
extern NIM_THREADVAR TFrame* framePtr__system_3094;
extern NIM_THREADVAR TFrame* framePtr__system_3094;
extern NIM_THREADVAR TFrame* framePtr__system_3094;
extern NIM_THREADVAR TFrame* framePtr__system_3094;
extern NIM_THREADVAR TFrame* framePtr__system_3094;
extern NIM_THREADVAR TFrame* framePtr__system_3094;
N_LIB_PRIVATE tyObject_SyncFile__QCQR8mK9aWVe5sIf5qaOAyw* syncFile__nimblepkgZsyncfile_1435;
N_LIB_PRIVATE NIM_BOOL alreadyExecutedX60gensym22___nimblepkgZsyncfile_1437 = NIM_FALSE;
extern NIM_THREADVAR tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ gch__system_5793;
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a, v, ((size_t) (size)));
}
static N_INLINE(void, nimZeroMem)(void* p, NI size) {
	nimSetMem__systemZmemory_7(p, ((int) 0), size);
}
static N_INLINE(void, nimFrame)(TFrame* s) {
	{
		if (!(framePtr__system_3094 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s).calldepth = ((NI16) 0);
	}
	goto LA1_;
	LA3_: ;
	{
		(*s).calldepth = (NI16)((*framePtr__system_3094).calldepth + ((NI16) 1));
	}
	LA1_: ;
	(*s).prev = framePtr__system_3094;
	framePtr__system_3094 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;
		callDepthLimitReached__system_3527();
	}
	LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_3094 = (*framePtr__system_3094).prev;
}
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, getPkgDir__nimblepkgZsyncfile_28)(tyObject_PackageInfo__y9ahmwzrCcWrfsrJgR1q4lw* pkgInfo) {
	NimStringDesc* result;
	tyTuple__7q7q3E6Oj24ZNVJb9aonhAg T1_;
	nimfr_("getPkgDir", "/home/yyoncho/Sources/nim/nimble/src/nimblepkg/syncfile.nim");
	result = NIM_NIL;
	nimln_(35, "/home/yyoncho/Sources/nim/nimble/src/nimblepkg/syncfile.nim");
	nimZeroMem((void*)(&T1_), sizeof(tyTuple__7q7q3E6Oj24ZNVJb9aonhAg));
	nossplitFile((*pkgInfo).myPath, (&T1_));
	result = copyString(T1_.Field0);
	popFrame();
	return result;
}
static N_INLINE(int, nimCmpMem)(void* a, void* b, NI size) {
	int result;
	result = (int)0;
	result = memcmp(a, b, ((size_t) (size)));
	return result;
}
static N_INLINE(NIM_BOOL, equalMem__system_1735)(void* a, void* b, NI size) {
	NIM_BOOL result;
	int T1_;
	result = (NIM_BOOL)0;
	T1_ = (int)0;
	T1_ = nimCmpMem(a, b, size);
	result = (T1_ == ((NI32) 0));
	return result;
}
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NI alen;
	NI blen;
	nimfr_("eqStrings", "/home/yyoncho/Sources/nim/Nim/lib/system/strmantle.nim");
{	result = (NIM_BOOL)0;
	nimln_(27, "/home/yyoncho/Sources/nim/Nim/lib/system/strmantle.nim");
	alen = (a ? a->Sup.len : 0);
	nimln_(28, "/home/yyoncho/Sources/nim/Nim/lib/system/strmantle.nim");
	blen = (b ? b->Sup.len : 0);
	nimln_(29, "/home/yyoncho/Sources/nim/Nim/lib/system/strmantle.nim");
	{
		if (!(alen == blen)) goto LA3_;
		nimln_(30, "/home/yyoncho/Sources/nim/Nim/lib/system/strmantle.nim");
		{
			if (!(alen == ((NI) 0))) goto LA7_;
			result = NIM_TRUE;
			goto BeforeRet_;
		}
		LA7_: ;
		nimln_(31, "/home/yyoncho/Sources/nim/Nim/lib/system/strmantle.nim");
		result = equalMem__system_1735(((void*) ((&a->data[((NI) 0)]))), ((void*) ((&b->data[((NI) 0)]))), ((NI) (alen)));
		goto BeforeRet_;
	}
	LA3_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_NIMCALL(void, Marker_tySequence__STVJgEyfAvX2CARt9c1e3sQ)(void* p, NI op) {
	tySequence__STVJgEyfAvX2CARt9c1e3sQ* a;
	NI T1_;
	a = (tySequence__STVJgEyfAvX2CARt9c1e3sQ*)p;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < (a ? a->Sup.len : 0); T1_++) {
	nimGCvisit((void*)a->data[T1_].Field1, op);
	nimGCvisit((void*)a->data[T1_].Field2.hashValue, op);
	}
}
static N_NIMCALL(void, Marker_tyRef__BlUM5f9bGV5nhGHp3NWaILA)(void* p, NI op) {
	tyObject_SyncFile__QCQR8mK9aWVe5sIf5qaOAyw* a;
	a = (tyObject_SyncFile__QCQR8mK9aWVe5sIf5qaOAyw*)p;
	nimGCvisit((void*)(*a).path, op);
	nimGCvisit((void*)(*a).data.data, op);
}
static N_NIMCALL(void, TM__x69btdbGiHm9an9b8Y9aIGrQzg_6)(void) {
	nimGCvisit((void*)syncFile__nimblepkgZsyncfile_1435, 0);
}
static N_INLINE(NI, minuspercent___system_716)(NI x, NI y) {
	NI result;
	nimfr_("-%", "/home/yyoncho/Sources/nim/Nim/lib/system/arithmetics.nim");
	result = (NI)0;
	nimln_(414, "/home/yyoncho/Sources/nim/Nim/lib/system/arithmetics.nim");
	nimln_(418, "/home/yyoncho/Sources/nim/Nim/lib/system/arithmetics.nim");
	result = ((NI) ((NU)((NU64)(((NU) (x))) - (NU64)(((NU) (y))))));
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, ltpercent___system_1005)(NI x, NI y) {
	NIM_BOOL result;
	nimfr_("<%", "/home/yyoncho/Sources/nim/Nim/lib/system/comparisons.nim");
	result = (NIM_BOOL)0;
	nimln_(186, "/home/yyoncho/Sources/nim/Nim/lib/system/comparisons.nim");
	nimln_(188, "/home/yyoncho/Sources/nim/Nim/lib/system/comparisons.nim");
	result = ((NU64)(((NU) (x))) < (NU64)(((NU) (y))));
	popFrame();
	return result;
}
static N_INLINE(void, rtlAddZCT__system_5903)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "/home/yyoncho/Sources/nim/Nim/lib/system/gc.nim");
	nimln_(243, "/home/yyoncho/Sources/nim/Nim/lib/system/gc.nim");
	addZCT__system_5854((&gch__system_5793.zct), c);
	popFrame();
}
static N_INLINE(void, decRef__system_5905)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("decRef", "/home/yyoncho/Sources/nim/Nim/lib/system/gc.nim");
	nimln_(248, "/home/yyoncho/Sources/nim/Nim/lib/system/gc.nim");
	(*c).refcount = minuspercent___system_716((*c).refcount, ((NI) 8));
	nimln_(249, "/home/yyoncho/Sources/nim/Nim/lib/system/gc.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = ltpercent___system_1005((*c).refcount, ((NI) 8));
		if (!T3_) goto LA4_;
		nimln_(250, "/home/yyoncho/Sources/nim/Nim/lib/system/gc.nim");
		rtlAddZCT__system_5903(c);
	}
	LA4_: ;
	popFrame();
}
static N_INLINE(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell__system_5860)(void* usr) {
	tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* result;
	NI T1_;
	nimfr_("usrToCell", "/home/yyoncho/Sources/nim/Nim/lib/system/gc.nim");
	result = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(177, "/home/yyoncho/Sources/nim/Nim/lib/system/gc.nim");
	T1_ = (NI)0;
	T1_ = minuspercent___system_716(((NI) (ptrdiff_t) (usr)), ((NI) 16));
	result = ((tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*) (T1_));
	popFrame();
	return result;
}
static N_INLINE(void, nimGCunrefRC1)(void* p) {
	tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T1_;
	nimfr_("nimGCunrefRC1", "/home/yyoncho/Sources/nim/Nim/lib/system/gc.nim");
	nimln_(280, "/home/yyoncho/Sources/nim/Nim/lib/system/gc.nim");
	T1_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
	T1_ = usrToCell__system_5860(p);
	decRef__system_5905(T1_);
	popFrame();
}
static N_INLINE(NimStringDesc*, slash___pureZos_121)(NimStringDesc* head, NimStringDesc* tail) {
	NimStringDesc* result;
	nimfr_("/", "/home/yyoncho/Sources/nim/Nim/lib/pure/os.nim");
	result = NIM_NIL;
	nimln_(237, "/home/yyoncho/Sources/nim/Nim/lib/pure/os.nim");
	result = nosjoinPath(head, tail);
	popFrame();
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}
static N_INLINE(void, copyMem__system_1727)(void* dest, void* source, NI size) {
	nimCopyMem(dest, source, size);
}
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	{
		if (!!((src == ((NimStringDesc*) NIM_NIL)))) goto LA3_;
		copyMem__system_1727(((void*) ((&(*dest).data[(*dest).Sup.len]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
		(*dest).Sup.len += (*src).Sup.len;
	}
	LA3_: ;
}
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, getSyncFilePath__nimblepkgZsyncfile_31)(tyObject_PackageInfo__y9ahmwzrCcWrfsrJgR1q4lw* pkgInfo) {
	NimStringDesc* result;
	NimStringDesc* T1_;
	NimStringDesc* T2_;
	tyTuple__Ufuqy1K6JyDSHZP03DOtDA T3_;
	tyEnum_VcsType__9cvWH7gVtmHmofFRFC7AgKg vcsType;
	NimStringDesc* vcsSpecialDirPath;
	NimStringDesc* T9_;
	nimfr_("getSyncFilePath", "/home/yyoncho/Sources/nim/nimble/src/nimblepkg/syncfile.nim");
{	result = NIM_NIL;
	nimln_(40, "/home/yyoncho/Sources/nim/nimble/src/nimblepkg/syncfile.nim");
	nimln_(43, "/home/yyoncho/Sources/nim/nimble/src/nimblepkg/syncfile.nim");
	T1_ = NIM_NIL;
	T1_ = getPkgDir__nimblepkgZsyncfile_28(pkgInfo);
	T2_ = NIM_NIL;
	T2_ = toPath__nimblepkgZpaths_5(T1_);
	nimZeroMem((void*)(&T3_), sizeof(tyTuple__Ufuqy1K6JyDSHZP03DOtDA));
	getVcsTypeAndSpecialDirPath__nimblepkgZvcstools_74(T2_, (&T3_));
	vcsType = (tyEnum_VcsType__9cvWH7gVtmHmofFRFC7AgKg)0;
	vcsType = T3_.Field0;
	vcsSpecialDirPath = NIM_NIL;
	vcsSpecialDirPath = T3_.Field1;
	nimln_(45, "/home/yyoncho/Sources/nim/nimble/src/nimblepkg/syncfile.nim");
	{
		tyObject_NimbleError__6rmfqzY5PO7blXdlEs8gjQ* T8_;
		if (!(vcsType == ((tyEnum_VcsType__9cvWH7gVtmHmofFRFC7AgKg) 0))) goto LA6_;
		nimln_(48, "/home/yyoncho/Sources/nim/nimble/src/nimblepkg/syncfile.nim");
		T8_ = NIM_NIL;
		T8_ = nimbleError__nimblepkgZcommon_26(((NimStringDesc*) &TM__x69btdbGiHm9an9b8Y9aIGrQzg_7), ((NimStringDesc*) &TM__x69btdbGiHm9an9b8Y9aIGrQzg_8), ((tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA*) NIM_NIL));
		raiseExceptionEx((Exception*)T8_, "NimbleError", "getSyncFilePath", "/home/yyoncho/Sources/nim/nimble/src/nimblepkg/syncfile.nim", 48);
	}
	LA6_: ;
	nimln_(53, "/home/yyoncho/Sources/nim/nimble/src/nimblepkg/syncfile.nim");
	T9_ = NIM_NIL;
	T9_ = rawNewString(((*pkgInfo).basicInfo.Field0 ? (*pkgInfo).basicInfo.Field0->Sup.len : 0) + 12);
appendString(T9_, (*pkgInfo).basicInfo.Field0);
appendString(T9_, ((NimStringDesc*) &TM__x69btdbGiHm9an9b8Y9aIGrQzg_9));
	result = slash___pureZos_121(vcsSpecialDirPath, T9_);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T1_;
	nimfr_("nimGCunrefNoCycle", "/home/yyoncho/Sources/nim/Nim/lib/system/gc.nim");
	nimln_(276, "/home/yyoncho/Sources/nim/Nim/lib/system/gc.nim");
	T1_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
	T1_ = usrToCell__system_5860(p);
	decRef__system_5905(T1_);
	popFrame();
}
static N_INLINE(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q*, X5BX5D___pureZjson_3069)(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* node, NimStringDesc* name) {
	tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* result;
	tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q** T9_;
	nimfr_("[]", "/home/yyoncho/Sources/nim/Nim/lib/pure/json.nim");
	result = NIM_NIL;
	nimln_(512, "/home/yyoncho/Sources/nim/Nim/lib/pure/json.nim");
	{
		if (!!(!((node == 0)))) goto LA3_;
		failedAssertImpl__stdZassertions_56(((NimStringDesc*) &TM__x69btdbGiHm9an9b8Y9aIGrQzg_10));
	}
	LA3_: ;
	nimln_(513, "/home/yyoncho/Sources/nim/Nim/lib/pure/json.nim");
	{
		if (!!(((*node).kind == ((tyEnum_JsonNodeKind__RUngo7nCHe6O8aBGIcrhtg) 5)))) goto LA7_;
		failedAssertImpl__stdZassertions_56(((NimStringDesc*) &TM__x69btdbGiHm9an9b8Y9aIGrQzg_11));
	}
	LA7_: ;
	nimln_(516, "/home/yyoncho/Sources/nim/Nim/lib/pure/json.nim");
	if (!(((32 &((NU8)1<<((NU)((*node).kind)&7U)))!=0))) 	{ raiseFieldError2(((NimStringDesc*) &TM__x69btdbGiHm9an9b8Y9aIGrQzg_12), reprDiscriminant(((NI)(*node).kind) + (NI)IL64(0), (&NTIjsonnodekind__RUngo7nCHe6O8aBGIcrhtg_))); } 
	T9_ = (tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q**)0;
	T9_ = X5BX5D___pureZjson_2663((&(*node)._kind_6.fields), name);
	result = (*T9_);
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, load__nimblepkgZsyncfile_40)(tyObject_SyncFile__QCQR8mK9aWVe5sIf5qaOAyw* syncFile, NimStringDesc* path) {
	NimStringDesc* T1_;
	tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* T7_;
	tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* T8_;
	nimfr_("load", "/home/yyoncho/Sources/nim/nimble/src/nimblepkg/syncfile.nim");
{	nimln_(58, "/home/yyoncho/Sources/nim/nimble/src/nimblepkg/syncfile.nim");
	T1_ = NIM_NIL;
	T1_ = (*syncFile).path; (*syncFile).path = copyStringRC1(path);
	if (T1_) nimGCunrefNoCycle(T1_);
	nimln_(59, "/home/yyoncho/Sources/nim/nimble/src/nimblepkg/syncfile.nim");
	{
		NIM_BOOL T4_;
		T4_ = (NIM_BOOL)0;
		T4_ = nosfileExists(path);
		if (!!(T4_)) goto LA5_;
		nimln_(60, "/home/yyoncho/Sources/nim/nimble/src/nimblepkg/syncfile.nim");
		goto BeforeRet_;
	}
	LA5_: ;
	nimln_(64, "/home/yyoncho/Sources/nim/nimble/src/nimblepkg/syncfile.nim");
	T7_ = NIM_NIL;
	T7_ = parseFile__pureZjson_5297(path);
	T8_ = NIM_NIL;
	T8_ = X5BX5D___pureZjson_3069(T7_, ((NimStringDesc*) &TM__x69btdbGiHm9an9b8Y9aIGrQzg_13));
	to__nimblepkgZsyncfile_46(T8_, (&(*syncFile).data));
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SyncFile__QCQR8mK9aWVe5sIf5qaOAyw*, getSyncFile__nimblepkgZsyncfile_1427)(tyObject_PackageInfo__y9ahmwzrCcWrfsrJgR1q4lw* pkgInfo) {
	tyObject_SyncFile__QCQR8mK9aWVe5sIf5qaOAyw* result;
	nimfr_("getSyncFile", "/home/yyoncho/Sources/nim/nimble/src/nimblepkg/syncfile.nim");
{	result = NIM_NIL;
	nimln_(72, "/home/yyoncho/Sources/nim/nimble/src/nimblepkg/syncfile.nim");
	{
		NimStringDesc* T3_;
		NimStringDesc* T4_;
		T3_ = NIM_NIL;
		T3_ = getPkgDir__nimblepkgZsyncfile_28(pkgInfo);
		T4_ = NIM_NIL;
		T4_ = nosgetCurrentDir();
		if (!!(eqStrings(T3_, T4_))) goto LA5_;
		failedAssertImpl__stdZassertions_56(((NimStringDesc*) &TM__x69btdbGiHm9an9b8Y9aIGrQzg_2));
	}
	LA5_: ;
	nimln_(76, "/home/yyoncho/Sources/nim/nimble/src/nimblepkg/syncfile.nim");
	{
		NimStringDesc* path;
		nimln_(3059, "/home/yyoncho/Sources/nim/Nim/lib/system.nim");
		if (!!(alreadyExecutedX60gensym22___nimblepkgZsyncfile_1437)) goto LA9_;
		nimln_(3060, "/home/yyoncho/Sources/nim/Nim/lib/system.nim");
		alreadyExecutedX60gensym22___nimblepkgZsyncfile_1437 = NIM_TRUE;
		nimln_(77, "/home/yyoncho/Sources/nim/nimble/src/nimblepkg/syncfile.nim");
		if (syncFile__nimblepkgZsyncfile_1435) { nimGCunrefRC1(syncFile__nimblepkgZsyncfile_1435); syncFile__nimblepkgZsyncfile_1435 = NIM_NIL; }
		syncFile__nimblepkgZsyncfile_1435 = (tyObject_SyncFile__QCQR8mK9aWVe5sIf5qaOAyw*) newObjRC1((&NTIrefsyncfile__BlUM5f9bGV5nhGHp3NWaILA_), sizeof(tyObject_SyncFile__QCQR8mK9aWVe5sIf5qaOAyw));
		nimln_(78, "/home/yyoncho/Sources/nim/nimble/src/nimblepkg/syncfile.nim");
		path = getSyncFilePath__nimblepkgZsyncfile_31(pkgInfo);
		nimln_(79, "/home/yyoncho/Sources/nim/nimble/src/nimblepkg/syncfile.nim");
		load__nimblepkgZsyncfile_40(syncFile__nimblepkgZsyncfile_1435, path);
	}
	LA9_: ;
	nimln_(80, "/home/yyoncho/Sources/nim/nimble/src/nimblepkg/syncfile.nim");
	result = syncFile__nimblepkgZsyncfile_1435;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, clear__nimblepkgZsyncfile_2185)(tyObject_SyncFile__QCQR8mK9aWVe5sIf5qaOAyw* syncFile) {
	nimfr_("clear", "/home/yyoncho/Sources/nim/nimble/src/nimblepkg/syncfile.nim");
	nimln_(108, "/home/yyoncho/Sources/nim/nimble/src/nimblepkg/syncfile.nim");
	clear__nimblepkgZsyncfile_2227((&(*syncFile).data));
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, setDepVcsRevision__nimblepkgZsyncfile_1933)(tyObject_SyncFile__QCQR8mK9aWVe5sIf5qaOAyw* syncFile, NimStringDesc* depName, tyObject_Sha1Hash__zQwLVDNef3gJr9bhL9bRloJw vcsRevision) {
	nimfr_("setDepVcsRevision", "/home/yyoncho/Sources/nim/nimble/src/nimblepkg/syncfile.nim");
	nimln_(102, "/home/yyoncho/Sources/nim/nimble/src/nimblepkg/syncfile.nim");
	X5BX5Deq___nimblepkgZsyncfile_1977((&(*syncFile).data), depName, vcsRevision);
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, save__nimblepkgZsyncfile_1460)(tyObject_SyncFile__QCQR8mK9aWVe5sIf5qaOAyw* syncFile) {
	tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* jsonNode;
	tyArray__rnBfBeuXQMeTae3dUyC1Bw T1_;
	NimStringDesc* T2_;
	nimfr_("save", "/home/yyoncho/Sources/nim/nimble/src/nimblepkg/syncfile.nim");
	nimln_(85, "/home/yyoncho/Sources/nim/nimble/src/nimblepkg/syncfile.nim");
	nimZeroMem((void*)T1_, sizeof(tyArray__rnBfBeuXQMeTae3dUyC1Bw));
	T1_[0].Field0 = copyString(((NimStringDesc*) &TM__x69btdbGiHm9an9b8Y9aIGrQzg_14));
	nimln_(86, "/home/yyoncho/Sources/nim/nimble/src/nimblepkg/syncfile.nim");
	T1_[0].Field1 = percent___pureZjson_1812(((NI) 1));
	T1_[1].Field0 = copyString(((NimStringDesc*) &TM__x69btdbGiHm9an9b8Y9aIGrQzg_13));
	nimln_(87, "/home/yyoncho/Sources/nim/nimble/src/nimblepkg/syncfile.nim");
	T1_[1].Field1 = percent___nimblepkgZsyncfile_1485((*syncFile).data);
	nimln_(85, "/home/yyoncho/Sources/nim/nimble/src/nimblepkg/syncfile.nim");
	jsonNode = percent___pureZjson_1831(T1_, 2);
	nimln_(90, "/home/yyoncho/Sources/nim/nimble/src/nimblepkg/syncfile.nim");
	T2_ = NIM_NIL;
	T2_ = pretty__pureZjson_4514(jsonNode, ((NI) 2));
	writeFile__stdZsyncio_477((*syncFile).path, T2_);
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, getDepVcsRevision__nimblepkgZsyncfile_1793)(tyObject_SyncFile__QCQR8mK9aWVe5sIf5qaOAyw* syncFile, NimStringDesc* depName, tyObject_Sha1Hash__zQwLVDNef3gJr9bhL9bRloJw* Result) {
	tyObject_Sha1Hash__zQwLVDNef3gJr9bhL9bRloJw T1_;
	nimfr_("getDepVcsRevision", "/home/yyoncho/Sources/nim/nimble/src/nimblepkg/syncfile.nim");
	nimln_(93, "/home/yyoncho/Sources/nim/nimble/src/nimblepkg/syncfile.nim");
	nimln_(95, "/home/yyoncho/Sources/nim/nimble/src/nimblepkg/syncfile.nim");
	nimZeroMem((void*)(&T1_), sizeof(tyObject_Sha1Hash__zQwLVDNef3gJr9bhL9bRloJw));
	getOrDefault__nimblepkgZsyncfile_1863((*syncFile).data, depName, notSetSha1Hash__nimblepkgZsha49hashes_10, (&T1_));
	unsureAsgnRef((void**) (&(*Result).hashValue), T1_.hashValue);
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, atmnimblepkgatssyncfiledotnim_Init000)(void) {
{
	TFrame FR_; FR_.len = 0;

	nimRegisterGlobalMarker(TM__x69btdbGiHm9an9b8Y9aIGrQzg_6);

}/* preInitProc end */
{
}
}

N_LIB_PRIVATE N_NIMCALL(void, atmnimblepkgatssyncfiledotnim_DatInit000)(void) {
static TNimNode* TM__x69btdbGiHm9an9b8Y9aIGrQzg_3_2[2];
static TNimNode* TM__x69btdbGiHm9an9b8Y9aIGrQzg_4_2[2];
static TNimNode* TM__x69btdbGiHm9an9b8Y9aIGrQzg_5_3[3];
static TNimNode TM__x69btdbGiHm9an9b8Y9aIGrQzg_0[10];
NTIsyncfile__QCQR8mK9aWVe5sIf5qaOAyw_.size = sizeof(tyObject_SyncFile__QCQR8mK9aWVe5sIf5qaOAyw);
NTIsyncfile__QCQR8mK9aWVe5sIf5qaOAyw_.align = NIM_ALIGNOF(tyObject_SyncFile__QCQR8mK9aWVe5sIf5qaOAyw);
NTIsyncfile__QCQR8mK9aWVe5sIf5qaOAyw_.kind = 18;
NTIsyncfile__QCQR8mK9aWVe5sIf5qaOAyw_.base = 0;
TM__x69btdbGiHm9an9b8Y9aIGrQzg_3_2[0] = &TM__x69btdbGiHm9an9b8Y9aIGrQzg_0[1];
TM__x69btdbGiHm9an9b8Y9aIGrQzg_0[1].kind = 1;
TM__x69btdbGiHm9an9b8Y9aIGrQzg_0[1].offset = offsetof(tyObject_SyncFile__QCQR8mK9aWVe5sIf5qaOAyw, path);
TM__x69btdbGiHm9an9b8Y9aIGrQzg_0[1].typ = (&NTIstring__77mFvmsOLKik79ci2hXkHEg_);
TM__x69btdbGiHm9an9b8Y9aIGrQzg_0[1].name = "path";
TM__x69btdbGiHm9an9b8Y9aIGrQzg_3_2[1] = &TM__x69btdbGiHm9an9b8Y9aIGrQzg_0[2];
NTItable__VvMOAkURzpFunhIRpm9cltw_.size = sizeof(tyObject_Table__VvMOAkURzpFunhIRpm9cltw);
NTItable__VvMOAkURzpFunhIRpm9cltw_.align = NIM_ALIGNOF(tyObject_Table__VvMOAkURzpFunhIRpm9cltw);
NTItable__VvMOAkURzpFunhIRpm9cltw_.kind = 18;
NTItable__VvMOAkURzpFunhIRpm9cltw_.base = 0;
TM__x69btdbGiHm9an9b8Y9aIGrQzg_4_2[0] = &TM__x69btdbGiHm9an9b8Y9aIGrQzg_0[4];
NTIkeyvaluepair__EceTD9cyFJax4VWMFZt7qAg_.size = sizeof(tyTuple__EceTD9cyFJax4VWMFZt7qAg);
NTIkeyvaluepair__EceTD9cyFJax4VWMFZt7qAg_.align = NIM_ALIGNOF(tyTuple__EceTD9cyFJax4VWMFZt7qAg);
NTIkeyvaluepair__EceTD9cyFJax4VWMFZt7qAg_.kind = 18;
NTIkeyvaluepair__EceTD9cyFJax4VWMFZt7qAg_.base = 0;
TM__x69btdbGiHm9an9b8Y9aIGrQzg_5_3[0] = &TM__x69btdbGiHm9an9b8Y9aIGrQzg_0[6];
TM__x69btdbGiHm9an9b8Y9aIGrQzg_0[6].kind = 1;
TM__x69btdbGiHm9an9b8Y9aIGrQzg_0[6].offset = offsetof(tyTuple__EceTD9cyFJax4VWMFZt7qAg, Field0);
TM__x69btdbGiHm9an9b8Y9aIGrQzg_0[6].typ = (&NTIint__rR5Bzr1D5krxoo1NcNyeMA_);
TM__x69btdbGiHm9an9b8Y9aIGrQzg_0[6].name = "Field0";
TM__x69btdbGiHm9an9b8Y9aIGrQzg_5_3[1] = &TM__x69btdbGiHm9an9b8Y9aIGrQzg_0[7];
TM__x69btdbGiHm9an9b8Y9aIGrQzg_0[7].kind = 1;
TM__x69btdbGiHm9an9b8Y9aIGrQzg_0[7].offset = offsetof(tyTuple__EceTD9cyFJax4VWMFZt7qAg, Field1);
TM__x69btdbGiHm9an9b8Y9aIGrQzg_0[7].typ = (&NTIstring__77mFvmsOLKik79ci2hXkHEg_);
TM__x69btdbGiHm9an9b8Y9aIGrQzg_0[7].name = "Field1";
TM__x69btdbGiHm9an9b8Y9aIGrQzg_5_3[2] = &TM__x69btdbGiHm9an9b8Y9aIGrQzg_0[8];
TM__x69btdbGiHm9an9b8Y9aIGrQzg_0[8].kind = 1;
TM__x69btdbGiHm9an9b8Y9aIGrQzg_0[8].offset = offsetof(tyTuple__EceTD9cyFJax4VWMFZt7qAg, Field2);
TM__x69btdbGiHm9an9b8Y9aIGrQzg_0[8].typ = (&NTIsha49hash__zQwLVDNef3gJr9bhL9bRloJw_);
TM__x69btdbGiHm9an9b8Y9aIGrQzg_0[8].name = "Field2";
TM__x69btdbGiHm9an9b8Y9aIGrQzg_0[5].len = 3; TM__x69btdbGiHm9an9b8Y9aIGrQzg_0[5].kind = 2; TM__x69btdbGiHm9an9b8Y9aIGrQzg_0[5].sons = &TM__x69btdbGiHm9an9b8Y9aIGrQzg_5_3[0];
NTIkeyvaluepair__EceTD9cyFJax4VWMFZt7qAg_.node = &TM__x69btdbGiHm9an9b8Y9aIGrQzg_0[5];
NTIkeyvaluepairseq__STVJgEyfAvX2CARt9c1e3sQ_.size = sizeof(tySequence__STVJgEyfAvX2CARt9c1e3sQ*);
NTIkeyvaluepairseq__STVJgEyfAvX2CARt9c1e3sQ_.align = NIM_ALIGNOF(tySequence__STVJgEyfAvX2CARt9c1e3sQ*);
NTIkeyvaluepairseq__STVJgEyfAvX2CARt9c1e3sQ_.kind = 24;
NTIkeyvaluepairseq__STVJgEyfAvX2CARt9c1e3sQ_.base = (&NTIkeyvaluepair__EceTD9cyFJax4VWMFZt7qAg_);
NTIkeyvaluepairseq__STVJgEyfAvX2CARt9c1e3sQ_.marker = Marker_tySequence__STVJgEyfAvX2CARt9c1e3sQ;
TM__x69btdbGiHm9an9b8Y9aIGrQzg_0[4].kind = 1;
TM__x69btdbGiHm9an9b8Y9aIGrQzg_0[4].offset = offsetof(tyObject_Table__VvMOAkURzpFunhIRpm9cltw, data);
TM__x69btdbGiHm9an9b8Y9aIGrQzg_0[4].typ = (&NTIkeyvaluepairseq__STVJgEyfAvX2CARt9c1e3sQ_);
TM__x69btdbGiHm9an9b8Y9aIGrQzg_0[4].name = "data";
TM__x69btdbGiHm9an9b8Y9aIGrQzg_4_2[1] = &TM__x69btdbGiHm9an9b8Y9aIGrQzg_0[9];
TM__x69btdbGiHm9an9b8Y9aIGrQzg_0[9].kind = 1;
TM__x69btdbGiHm9an9b8Y9aIGrQzg_0[9].offset = offsetof(tyObject_Table__VvMOAkURzpFunhIRpm9cltw, counter);
TM__x69btdbGiHm9an9b8Y9aIGrQzg_0[9].typ = (&NTIint__rR5Bzr1D5krxoo1NcNyeMA_);
TM__x69btdbGiHm9an9b8Y9aIGrQzg_0[9].name = "counter";
TM__x69btdbGiHm9an9b8Y9aIGrQzg_0[3].len = 2; TM__x69btdbGiHm9an9b8Y9aIGrQzg_0[3].kind = 2; TM__x69btdbGiHm9an9b8Y9aIGrQzg_0[3].sons = &TM__x69btdbGiHm9an9b8Y9aIGrQzg_4_2[0];
NTItable__VvMOAkURzpFunhIRpm9cltw_.node = &TM__x69btdbGiHm9an9b8Y9aIGrQzg_0[3];
TM__x69btdbGiHm9an9b8Y9aIGrQzg_0[2].kind = 1;
TM__x69btdbGiHm9an9b8Y9aIGrQzg_0[2].offset = offsetof(tyObject_SyncFile__QCQR8mK9aWVe5sIf5qaOAyw, data);
TM__x69btdbGiHm9an9b8Y9aIGrQzg_0[2].typ = (&NTItable__VvMOAkURzpFunhIRpm9cltw_);
TM__x69btdbGiHm9an9b8Y9aIGrQzg_0[2].name = "data";
TM__x69btdbGiHm9an9b8Y9aIGrQzg_0[0].len = 2; TM__x69btdbGiHm9an9b8Y9aIGrQzg_0[0].kind = 2; TM__x69btdbGiHm9an9b8Y9aIGrQzg_0[0].sons = &TM__x69btdbGiHm9an9b8Y9aIGrQzg_3_2[0];
NTIsyncfile__QCQR8mK9aWVe5sIf5qaOAyw_.node = &TM__x69btdbGiHm9an9b8Y9aIGrQzg_0[0];
NTIrefsyncfile__BlUM5f9bGV5nhGHp3NWaILA_.size = sizeof(tyObject_SyncFile__QCQR8mK9aWVe5sIf5qaOAyw*);
NTIrefsyncfile__BlUM5f9bGV5nhGHp3NWaILA_.align = NIM_ALIGNOF(tyObject_SyncFile__QCQR8mK9aWVe5sIf5qaOAyw*);
NTIrefsyncfile__BlUM5f9bGV5nhGHp3NWaILA_.kind = 22;
NTIrefsyncfile__BlUM5f9bGV5nhGHp3NWaILA_.base = (&NTIsyncfile__QCQR8mK9aWVe5sIf5qaOAyw_);
NTIrefsyncfile__BlUM5f9bGV5nhGHp3NWaILA_.marker = Marker_tyRef__BlUM5f9bGV5nhGHp3NWaILA;
}

