/* Generated by Nim Compiler v1.7.1 */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <setjmp.h>
#include <windows.h>
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  typedef struct tyObject_SslStruct__hZKic6WnTBMq6Usbg49bnhw tyObject_SslStruct__hZKic6WnTBMq6Usbg49bnhw;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA tySequence__uB9b75OUPRENsBAu4AnoePA;
typedef struct TSafePoint TSafePoint;
typedef struct tyObject_LibraryError__x1muge9crz9aAVqWWUrEL9aXg tyObject_LibraryError__x1muge9crz9aAVqWWUrEL9aXg;
typedef struct tyObject_OSError__BeJgrOdDsczOwEWOZbRfKA tyObject_OSError__BeJgrOdDsczOwEWOZbRfKA;
typedef struct tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA;
typedef struct tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack__7fytPA5bBsob6See21YMRA tyObject_GcStack__7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple__ujsjpB2O9cjj3uDHsXbnSzg tyTuple__ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_SharedList__JI9cx34TL8n3aOKF6tSMBUw tyObject_SharedList__JI9cx34TL8n3aOKF6tSMBUw;
typedef struct tyObject_SharedListNodecolonObjectType___KGw0YAw6W9aSz3Sr9aXGu7zg tyObject_SharedListNodecolonObjectType___KGw0YAw6W9aSz3Sr9aXGu7zg;
typedef struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA;
struct tyObject_SslStruct__hZKic6WnTBMq6Usbg49bnhw {
char dummy;
};
typedef NU8 tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc__ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
NI align;
tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc__ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct RootObj {
TNimType* m_type;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence__uB9b75OUPRENsBAu4AnoePA* trace;
Exception* up;
};
struct TSafePoint {
TSafePoint* prev;
NI status;
jmp_buf context;
};
struct tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA {
  Exception Sup;
};
struct tyObject_OSError__BeJgrOdDsczOwEWOZbRfKA {
  tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA Sup;
NI32 errorCode;
};
struct tyObject_LibraryError__x1muge9crz9aAVqWWUrEL9aXg {
  tyObject_OSError__BeJgrOdDsczOwEWOZbRfKA Sup;
};
typedef NU8 tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack__7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ* tyArray__SPr7N6UKfuF549bNPiUvSRw[256];
typedef NU32 tyArray__BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg* tyArray__N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray__N1u1nqOgmuJN9cSZrnMHgOQ tyArray__B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw* tyArray__lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA {
tyArray__lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* tyArray__0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw {
tyArray__0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple__ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple__ujsjpB2O9cjj3uDHsXbnSzg tyArray__LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray__LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray__SPr7N6UKfuF549bNPiUvSRw freeSmallChunks;
NU32 flBitmap;
tyArray__BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray__B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_SharedList__JI9cx34TL8n3aOKF6tSMBUw {
tyObject_SharedListNodecolonObjectType___KGw0YAw6W9aSz3Sr9aXGu7zg* head;
tyObject_SharedListNodecolonObjectType___KGw0YAw6W9aSz3Sr9aXGu7zg* tail;
CRITICAL_SECTION lock;
};
struct tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack__7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
NI zctThreshold;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w additionalRoots;
tyObject_SharedList__JI9cx34TL8n3aOKF6tSMBUw toDispose;
NI gcThreadId;
};
typedef N_CDECL_PTR(tyObject_SslStruct__hZKic6WnTBMq6Usbg49bnhw*, tyProc__HXibadfWHwHwyhCwpIRD2A) (void);
typedef N_CDECL_PTR(unsigned long, tyProc__HBcM2Mt9bfW9bP8CkO25r0mA) (void);
typedef N_CDECL_PTR(NCSTRING, tyProc__ILGNrKdZ6rU9bHuzDylmHhA) (unsigned long e, NCSTRING buf);
typedef N_CDECL_PTR(tyObject_SslStruct__hZKic6WnTBMq6Usbg49bnhw*, tyProc__Rqjya8uauy9aPcyfGamaSrg) (tyObject_SslStruct__hZKic6WnTBMq6Usbg49bnhw* meth);
typedef N_CDECL_PTR(int, tyProc__2PA7CxitARKs0jpUW1gQ0g) (tyObject_SslStruct__hZKic6WnTBMq6Usbg49bnhw* s, NCSTRING ciphers);
typedef N_CDECL_PTR(void, tyProc__IX9aeaSWx4arDCJq04EsJjQ) (tyObject_SslStruct__hZKic6WnTBMq6Usbg49bnhw* ctx, NCSTRING str);
typedef N_CDECL_PTR(long, tyProc__J5jVzoevP749cPcyUg9cwPEA) (tyObject_SslStruct__hZKic6WnTBMq6Usbg49bnhw* ctx, int cmd, long larg, void* parg);
typedef N_CDECL_PTR(NI, tyProc__aF4y9aPKIi8D4VGrVvX011Q) (NI a, void* b);
typedef N_CDECL_PTR(void, tyProc__H5wL7jexPlRA7WCw9cqLm0A) (tyObject_SslStruct__hZKic6WnTBMq6Usbg49bnhw* s, NI mode, tyProc__aF4y9aPKIi8D4VGrVvX011Q cb);
typedef N_STDCALL_PTR(int, tyProc__tYatIIo0oRSB9bjHLep7yhQ) (tyObject_SslStruct__hZKic6WnTBMq6Usbg49bnhw* ctx, NCSTRING filename);
typedef N_CDECL_PTR(int, tyProc__xjxKRHVZXDqdWXw9bunoZ3w) (tyObject_SslStruct__hZKic6WnTBMq6Usbg49bnhw* ctx, NCSTRING filename, int typ);
typedef N_CDECL_PTR(int, tyProc__Vff1ipOwDPDGknaRJAdXjA) (tyObject_SslStruct__hZKic6WnTBMq6Usbg49bnhw* ctx);
typedef N_CDECL_PTR(int, tyProc__gZVmmOpGrWMJL1q0d9bMEZQ) (tyObject_SslStruct__hZKic6WnTBMq6Usbg49bnhw* ctx, NCSTRING CAfile, NCSTRING CApath);
typedef N_CDECL_PTR(void, tyProc__ln4kdL5W9bbX4a1xl8nnVXQ) (void);
typedef N_CDECL_PTR(int, tyProc__kxUw9cdxJbPtv0iPyoSbDBQ) (tyObject_SslStruct__hZKic6WnTBMq6Usbg49bnhw* s, int ret_code);
typedef N_CDECL_PTR(void, tyProc__e47RoMUolEGMiUlfiZt9abQ) (tyObject_SslStruct__hZKic6WnTBMq6Usbg49bnhw* ssl);
typedef N_CDECL_PTR(int, tyProc__EJ9cbYwLVOng2t4wnewGkmA) (tyObject_SslStruct__hZKic6WnTBMq6Usbg49bnhw* ssl, NI fd);
typedef N_CDECL_PTR(NI, tyProc__xGcw2zK9bzuUE9c8WzKW5hzw) (tyObject_SslStruct__hZKic6WnTBMq6Usbg49bnhw* ssl, int cmd, NI larg, void* parg);
typedef N_CDECL_PTR(int, tyProc__sG7rgqmtlgBaumPwwN3BfQ) (tyObject_SslStruct__hZKic6WnTBMq6Usbg49bnhw* ssl, NCSTRING buf, NI num);
typedef N_CDECL_PTR(int, tyProc__09aW01hZ1tSPafLaWVpBcXA) (tyObject_SslStruct__hZKic6WnTBMq6Usbg49bnhw* ssl, void* buf, NI num);
struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tySequence__uB9b75OUPRENsBAu4AnoePA {
  TGenericSeq Sup;
  tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(tyObject_SslStruct__hZKic6WnTBMq6Usbg49bnhw*, loadPSSLMethod__wrappersZopenssl_202)(NimStringDesc* method1, NimStringDesc* method2);
N_LIB_PRIVATE N_NIMCALL(void*, sslSymNullable__wrappersZopenssl_190)(NimStringDesc* name, NimStringDesc* alternativeName);
N_LIB_PRIVATE N_NIMCALL(void*, symNullable__wrappersZopenssl_184)(void* dll, NimStringDesc* name, NimStringDesc* alternativeName);
N_LIB_PRIVATE N_NIMCALL(void*, symAddr__pureZdynlib_30)(void* lib, NCSTRING name);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringDesc* s);
static N_INLINE(void*, thisModule__wrappersZopenssl_174)(void);
N_LIB_PRIVATE N_NIMCALL(void*, loadLib__pureZdynlib_6)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_3455)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void*, sslModule__wrappersZopenssl_177)(void);
static N_INLINE(void, pushSafePoint)(TSafePoint* s);
N_LIB_PRIVATE N_NIMCALL(void*, loadLibPattern__pureZdynlib_49)(NimStringDesc* pattern, NIM_BOOL globalSymbols);
static N_INLINE(void, popSafePoint)(void);
static N_INLINE(TFrame*, getFrame)(void);
static N_INLINE(void, setFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void*, newObj)(TNimType* typ, NI size);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(void, decRef__system_5886)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(NI, minuspercent___system_716)(NI x, NI y);
static N_INLINE(NIM_BOOL, ltpercent___system_1005)(NI x, NI y);
static N_INLINE(void, rtlAddZCT__system_5884)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT__system_5835)(tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell__system_5841)(void* usr);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef__system_5879)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(NI, pluspercent___system_696)(NI x, NI y);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e, NCSTRING ename, NCSTRING procname, NCSTRING filename, NI line);
static N_INLINE(void, popCurrentException)(void);
N_LIB_PRIVATE N_NIMCALL(void, reraiseException)(void);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem__system_1727)(void* dest, void* source, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_LIB_PRIVATE N_NIMCALL(void*, nimLoadLibrary)(NimStringDesc* path);
N_LIB_PRIVATE N_NIMCALL(void, nimLoadLibraryError)(NimStringDesc* path);
N_LIB_PRIVATE N_NIMCALL(void*, nimGetProcAddr)(void* lib, NCSTRING name);
N_LIB_PRIVATE N_NIMCALL(void*, utilSymNullable__wrappersZopenssl_198)(NimStringDesc* name, NimStringDesc* alternativeName);
static N_INLINE(void*, utilModule__wrappersZopenssl_181)(void);
N_LIB_PRIVATE N_NIMCALL(void*, sslSymThrows__wrappersZopenssl_194)(NimStringDesc* name, NimStringDesc* alternativeName);
N_LIB_PRIVATE N_NOINLINE(void, raiseInvalidLibrary__pureZdynlib_9)(NCSTRING name) __attribute__((noreturn));
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i, NI64 a, NI64 b);
N_LIB_PRIVATE TNimType NTIsslstruct__hZKic6WnTBMq6Usbg49bnhw_;
N_LIB_PRIVATE TNimType NTIsslctx__QQ33RYEe889cv60wm9bVkd8A_;
STRING_LITERAL(TM__SLGpYVEqpFQ7VaPsJH6HIA_3, "(libssl-1_1-x64|ssleay64|libssl64).dll", 38);
extern TNimType NTIreflibraryerror__HV2B9a6TW6WPpQna2mQFeQQ_;
extern TNimType NTIlibraryerror__x1muge9crz9aAVqWWUrEL9aXg_;
STRING_LITERAL(TM__SLGpYVEqpFQ7VaPsJH6HIA_4, "Could not load SSL using (libssl-1_1-x64|ssleay64|libssl64).dll", 63);
STRING_LITERAL(TM__SLGpYVEqpFQ7VaPsJH6HIA_5, "Could not load ", 15);
STRING_LITERAL(TM__SLGpYVEqpFQ7VaPsJH6HIA_6, " nor ", 5);
STRING_LITERAL(TM__SLGpYVEqpFQ7VaPsJH6HIA_7, "TLS_method", 10);
STRING_LITERAL(TM__SLGpYVEqpFQ7VaPsJH6HIA_8, "SSLv23_method", 13);
STRING_LITERAL(TM__SLGpYVEqpFQ7VaPsJH6HIA_11, "libcrypto-1_1-x64.dll", 21);
STRING_LITERAL(TM__SLGpYVEqpFQ7VaPsJH6HIA_13, "libeay64.dll", 12);
STRING_LITERAL(TM__SLGpYVEqpFQ7VaPsJH6HIA_14, "(libcrypto-1_1-x64|libeay64).dll", 32);
STRING_LITERAL(TM__SLGpYVEqpFQ7VaPsJH6HIA_21, "libssl-1_1-x64.dll", 18);
STRING_LITERAL(TM__SLGpYVEqpFQ7VaPsJH6HIA_23, "ssleay64.dll", 12);
STRING_LITERAL(TM__SLGpYVEqpFQ7VaPsJH6HIA_25, "libssl64.dll", 12);
STRING_LITERAL(TM__SLGpYVEqpFQ7VaPsJH6HIA_30, "OpenSSL_version_num", 19);
STRING_LITERAL(TM__SLGpYVEqpFQ7VaPsJH6HIA_31, "SSLeay", 6);
STRING_LITERAL(TM__SLGpYVEqpFQ7VaPsJH6HIA_32, "SSL_CTX_set_ciphersuites", 24);
STRING_LITERAL(TM__SLGpYVEqpFQ7VaPsJH6HIA_45, "SSL_in_init", 11);
STRING_LITERAL(TM__SLGpYVEqpFQ7VaPsJH6HIA_46, "SSL_state", 9);
N_LIB_PRIVATE void* thisMod__wrappersZopenssl_176;
extern NIM_THREADVAR TFrame* framePtr__system_3022;
extern NIM_THREADVAR TFrame* framePtr__system_3022;
extern NIM_THREADVAR TFrame* framePtr__system_3022;
extern NIM_THREADVAR TFrame* framePtr__system_3022;
extern NIM_THREADVAR TFrame* framePtr__system_3022;
extern NIM_THREADVAR TFrame* framePtr__system_3022;
N_LIB_PRIVATE void* sslMod__wrappersZopenssl_179;
extern NIM_THREADVAR TSafePoint* excHandler__system_3023;
extern NIM_THREADVAR TSafePoint* excHandler__system_3023;
extern NIM_THREADVAR TSafePoint* excHandler__system_3023;
extern NIM_THREADVAR TSafePoint* excHandler__system_3023;
extern NIM_THREADVAR TFrame* framePtr__system_3022;
extern NIM_THREADVAR TFrame* framePtr__system_3022;
extern NIM_THREADVAR tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ gch__system_5774;
extern NIM_THREADVAR Exception* currException__system_3024;
extern NIM_THREADVAR Exception* currException__system_3024;
static void* TM__SLGpYVEqpFQ7VaPsJH6HIA_9;
tyProc__HBcM2Mt9bfW9bP8CkO25r0mA Dl_2147484094_;
tyProc__ILGNrKdZ6rU9bHuzDylmHhA Dl_2147484090_;
static void* TM__SLGpYVEqpFQ7VaPsJH6HIA_19;
tyProc__Rqjya8uauy9aPcyfGamaSrg Dl_2147483981_;
tyProc__2PA7CxitARKs0jpUW1gQ0g Dl_2147483998_;
N_LIB_PRIVATE void* utilMod__wrappersZopenssl_183;
N_LIB_PRIVATE tyProc__IX9aeaSWx4arDCJq04EsJjQ theProc__wrappersZopenssl_301;
tyProc__J5jVzoevP749cPcyUg9cwPEA Dl_2147484155_;
tyProc__H5wL7jexPlRA7WCw9cqLm0A Dl_2147483989_;
tyProc__tYatIIo0oRSB9bjHLep7yhQ Dl_2147484005_;
tyProc__xjxKRHVZXDqdWXw9bunoZ3w Dl_2147484008_;
tyProc__Vff1ipOwDPDGknaRJAdXjA Dl_2147484012_;
tyProc__gZVmmOpGrWMJL1q0d9bMEZQ Dl_2147483983_;
N_LIB_PRIVATE tyProc__Vff1ipOwDPDGknaRJAdXjA theProc__wrappersZopenssl_275;
N_LIB_PRIVATE tyProc__Vff1ipOwDPDGknaRJAdXjA sslState__wrappersZopenssl_278;
tyProc__ln4kdL5W9bbX4a1xl8nnVXQ Dl_2147484260_;
tyProc__Vff1ipOwDPDGknaRJAdXjA Dl_2147484030_;
tyProc__kxUw9cdxJbPtv0iPyoSbDBQ Dl_2147484047_;
tyProc__e47RoMUolEGMiUlfiZt9abQ Dl_2147483968_;
tyProc__Rqjya8uauy9aPcyfGamaSrg Dl_2147483966_;
tyProc__EJ9cbYwLVOng2t4wnewGkmA Dl_2147484027_;
tyProc__xGcw2zK9bzuUE9c8WzKW5hzw Dl_2147484168_;
tyProc__Vff1ipOwDPDGknaRJAdXjA Dl_2147484037_;
tyProc__Vff1ipOwDPDGknaRJAdXjA Dl_2147484050_;
tyProc__sG7rgqmtlgBaumPwwN3BfQ Dl_2147484043_;
tyProc__Vff1ipOwDPDGknaRJAdXjA Dl_2147484052_;
tyProc__09aW01hZ1tSPafLaWVpBcXA Dl_2147484039_;
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringDesc* s) {
	NCSTRING result;
	result = (NCSTRING)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (s == ((NimStringDesc*) NIM_NIL));
		if (T3_) goto LA4_;
		T3_ = ((*s).Sup.len == ((NI) 0));
		LA4_: ;
		if (!T3_) goto LA5_;
		result = "";
	}
	goto LA1_;
	LA5_: ;
	{
		result = ((NCSTRING) ((*s).data));
	}
	LA1_: ;
	return result;
}
static N_INLINE(void, nimFrame)(TFrame* s) {
	{
		if (!(framePtr__system_3022 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s).calldepth = ((NI16) 0);
	}
	goto LA1_;
	LA3_: ;
	{
		(*s).calldepth = (NI16)((*framePtr__system_3022).calldepth + ((NI16) 1));
	}
	LA1_: ;
	(*s).prev = framePtr__system_3022;
	framePtr__system_3022 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;
		callDepthLimitReached__system_3455();
	}
	LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_3022 = (*framePtr__system_3022).prev;
}
static N_INLINE(void*, thisModule__wrappersZopenssl_174)(void) {
	void* result;
	nimfr_("thisModule", "/home/yyoncho/Sources/nim/Nim/lib/wrappers/openssl.nim");
	result = (void*)0;
	nimln_(307, "/home/yyoncho/Sources/nim/Nim/lib/wrappers/openssl.nim");
	{
		if (!(thisMod__wrappersZopenssl_176 == 0)) goto LA3_;
		thisMod__wrappersZopenssl_176 = loadLib__pureZdynlib_6();
	}
	LA3_: ;
	nimln_(309, "/home/yyoncho/Sources/nim/Nim/lib/wrappers/openssl.nim");
	result = thisMod__wrappersZopenssl_176;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void*, symNullable__wrappersZopenssl_184)(void* dll, NimStringDesc* name, NimStringDesc* alternativeName) {
	void* result;
	nimfr_("symNullable", "/home/yyoncho/Sources/nim/Nim/lib/wrappers/openssl.nim");
{	result = (void*)0;
	nimln_(328, "/home/yyoncho/Sources/nim/Nim/lib/wrappers/openssl.nim");
	{
		if (!!((dll == 0))) goto LA3_;
		nimln_(329, "/home/yyoncho/Sources/nim/Nim/lib/wrappers/openssl.nim");
		result = symAddr__pureZdynlib_30(dll, nimToCStringConv(name));
		nimln_(330, "/home/yyoncho/Sources/nim/Nim/lib/wrappers/openssl.nim");
		{
			NIM_BOOL T7_;
			T7_ = (NIM_BOOL)0;
			T7_ = (result == 0);
			if (!(T7_)) goto LA8_;
			T7_ = (((NI) 0) < (alternativeName ? alternativeName->Sup.len : 0));
			LA8_: ;
			if (!T7_) goto LA9_;
			nimln_(331, "/home/yyoncho/Sources/nim/Nim/lib/wrappers/openssl.nim");
			result = symAddr__pureZdynlib_30(dll, nimToCStringConv(alternativeName));
		}
		LA9_: ;
	}
	LA3_: ;
	nimln_(334, "/home/yyoncho/Sources/nim/Nim/lib/wrappers/openssl.nim");
	{
		void* thisDynlib;
		if (!(result == 0)) goto LA13_;
		nimln_(335, "/home/yyoncho/Sources/nim/Nim/lib/wrappers/openssl.nim");
		thisDynlib = thisModule__wrappersZopenssl_174();
		nimln_(336, "/home/yyoncho/Sources/nim/Nim/lib/wrappers/openssl.nim");
		{
			if (!(thisDynlib == 0)) goto LA17_;
			result = NIM_NIL;
			goto BeforeRet_;
		}
		LA17_: ;
		nimln_(337, "/home/yyoncho/Sources/nim/Nim/lib/wrappers/openssl.nim");
		result = symAddr__pureZdynlib_30(thisDynlib, nimToCStringConv(name));
		nimln_(338, "/home/yyoncho/Sources/nim/Nim/lib/wrappers/openssl.nim");
		{
			NIM_BOOL T21_;
			T21_ = (NIM_BOOL)0;
			T21_ = (result == 0);
			if (!(T21_)) goto LA22_;
			T21_ = (((NI) 0) < (alternativeName ? alternativeName->Sup.len : 0));
			LA22_: ;
			if (!T21_) goto LA23_;
			nimln_(339, "/home/yyoncho/Sources/nim/Nim/lib/wrappers/openssl.nim");
			result = symAddr__pureZdynlib_30(thisDynlib, nimToCStringConv(alternativeName));
		}
		LA23_: ;
	}
	LA13_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, pushSafePoint)(TSafePoint* s) {
	(*s).prev = excHandler__system_3023;
	excHandler__system_3023 = s;
}
static N_INLINE(void, popSafePoint)(void) {
	excHandler__system_3023 = (*excHandler__system_3023).prev;
}
static N_INLINE(TFrame*, getFrame)(void) {
	TFrame* result;
	result = (TFrame*)0;
	result = framePtr__system_3022;
	return result;
}
static N_INLINE(void, setFrame)(TFrame* s) {
	framePtr__system_3022 = s;
}
static N_INLINE(NI, minuspercent___system_716)(NI x, NI y) {
	NI result;
	nimfr_("-%", "/home/yyoncho/Sources/nim/Nim/lib/system/arithmetics.nim");
	result = (NI)0;
	nimln_(414, "/home/yyoncho/Sources/nim/Nim/lib/system/arithmetics.nim");
	nimln_(418, "/home/yyoncho/Sources/nim/Nim/lib/system/arithmetics.nim");
	result = ((NI) ((NU)((NU64)(((NU) (x))) - (NU64)(((NU) (y))))));
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, ltpercent___system_1005)(NI x, NI y) {
	NIM_BOOL result;
	nimfr_("<%", "/home/yyoncho/Sources/nim/Nim/lib/system/comparisons.nim");
	result = (NIM_BOOL)0;
	nimln_(186, "/home/yyoncho/Sources/nim/Nim/lib/system/comparisons.nim");
	nimln_(188, "/home/yyoncho/Sources/nim/Nim/lib/system/comparisons.nim");
	result = ((NU64)(((NU) (x))) < (NU64)(((NU) (y))));
	popFrame();
	return result;
}
static N_INLINE(void, rtlAddZCT__system_5884)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "/home/yyoncho/Sources/nim/Nim/lib/system/gc.nim");
	nimln_(243, "/home/yyoncho/Sources/nim/Nim/lib/system/gc.nim");
	addZCT__system_5835((&gch__system_5774.zct), c);
	popFrame();
}
static N_INLINE(void, decRef__system_5886)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("decRef", "/home/yyoncho/Sources/nim/Nim/lib/system/gc.nim");
	nimln_(248, "/home/yyoncho/Sources/nim/Nim/lib/system/gc.nim");
	(*c).refcount = minuspercent___system_716((*c).refcount, ((NI) 8));
	nimln_(249, "/home/yyoncho/Sources/nim/Nim/lib/system/gc.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = ltpercent___system_1005((*c).refcount, ((NI) 8));
		if (!T3_) goto LA4_;
		nimln_(250, "/home/yyoncho/Sources/nim/Nim/lib/system/gc.nim");
		rtlAddZCT__system_5884(c);
	}
	LA4_: ;
	popFrame();
}
static N_INLINE(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell__system_5841)(void* usr) {
	tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* result;
	NI T1_;
	nimfr_("usrToCell", "/home/yyoncho/Sources/nim/Nim/lib/system/gc.nim");
	result = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(177, "/home/yyoncho/Sources/nim/Nim/lib/system/gc.nim");
	T1_ = (NI)0;
	T1_ = minuspercent___system_716(((NI) (ptrdiff_t) (usr)), ((NI) 16));
	result = ((tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*) (T1_));
	popFrame();
	return result;
}
static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T1_;
	nimfr_("nimGCunrefNoCycle", "/home/yyoncho/Sources/nim/Nim/lib/system/gc.nim");
	nimln_(276, "/home/yyoncho/Sources/nim/Nim/lib/system/gc.nim");
	T1_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
	T1_ = usrToCell__system_5841(p);
	decRef__system_5886(T1_);
	popFrame();
}
static N_INLINE(NI, pluspercent___system_696)(NI x, NI y) {
	NI result;
	nimfr_("+%", "/home/yyoncho/Sources/nim/Nim/lib/system/arithmetics.nim");
	result = (NI)0;
	nimln_(403, "/home/yyoncho/Sources/nim/Nim/lib/system/arithmetics.nim");
	nimln_(407, "/home/yyoncho/Sources/nim/Nim/lib/system/arithmetics.nim");
	result = ((NI) ((NU)((NU64)(((NU) (x))) + (NU64)(((NU) (y))))));
	popFrame();
	return result;
}
static N_INLINE(void, incRef__system_5879)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("incRef", "/home/yyoncho/Sources/nim/Nim/lib/system/gc.nim");
	nimln_(231, "/home/yyoncho/Sources/nim/Nim/lib/system/gc.nim");
	(*c).refcount = pluspercent___system_696((*c).refcount, ((NI) 8));
	popFrame();
}
static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr_("asgnRef", "/home/yyoncho/Sources/nim/Nim/lib/system/gc.nim");
	nimln_(286, "/home/yyoncho/Sources/nim/Nim/lib/system/gc.nim");
	{
		tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell__system_5841(src);
		incRef__system_5879(T5_);
	}
	LA3_: ;
	nimln_(287, "/home/yyoncho/Sources/nim/Nim/lib/system/gc.nim");
	{
		tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell__system_5841((*dest));
		decRef__system_5886(T10_);
	}
	LA8_: ;
	nimln_(288, "/home/yyoncho/Sources/nim/Nim/lib/system/gc.nim");
	(*dest) = src;
	popFrame();
}
static N_INLINE(void, popCurrentException)(void) {
	asgnRef((void**) (&currException__system_3024), (*currException__system_3024).up);
}
static N_INLINE(void*, sslModule__wrappersZopenssl_177)(void) {
	void* result;
	TSafePoint TM__SLGpYVEqpFQ7VaPsJH6HIA_2;
	TFrame* _nimCurFrame;
	nimfr_("sslModule", "/home/yyoncho/Sources/nim/Nim/lib/wrappers/openssl.nim");
	_nimCurFrame = getFrame();
	result = (void*)0;
	nimln_(313, "/home/yyoncho/Sources/nim/Nim/lib/wrappers/openssl.nim");
	pushSafePoint(&TM__SLGpYVEqpFQ7VaPsJH6HIA_2);
	TM__SLGpYVEqpFQ7VaPsJH6HIA_2.status = _setjmp(TM__SLGpYVEqpFQ7VaPsJH6HIA_2.context, 0);
	if (TM__SLGpYVEqpFQ7VaPsJH6HIA_2.status == 0) {
	nimln_(314, "/home/yyoncho/Sources/nim/Nim/lib/wrappers/openssl.nim");
	{
		if (!(sslMod__wrappersZopenssl_179 == 0)) goto LA3_;
		sslMod__wrappersZopenssl_179 = loadLibPattern__pureZdynlib_49(((NimStringDesc*) &TM__SLGpYVEqpFQ7VaPsJH6HIA_3), NIM_FALSE);
	}
	LA3_: ;
	popSafePoint();
	}
	else {
		popSafePoint();
		setFrame(_nimCurFrame);
		{
			tyObject_LibraryError__x1muge9crz9aAVqWWUrEL9aXg* T7_;
			NimStringDesc* T8_;
			TM__SLGpYVEqpFQ7VaPsJH6HIA_2.status = 0;
			T7_ = NIM_NIL;
			T7_ = (tyObject_LibraryError__x1muge9crz9aAVqWWUrEL9aXg*) newObj((&NTIreflibraryerror__HV2B9a6TW6WPpQna2mQFeQQ_), sizeof(tyObject_LibraryError__x1muge9crz9aAVqWWUrEL9aXg));
			(*T7_).Sup.Sup.Sup.Sup.m_type = (&NTIlibraryerror__x1muge9crz9aAVqWWUrEL9aXg_);
			(*T7_).Sup.Sup.Sup.name = "LibraryError";
			T8_ = NIM_NIL;
			T8_ = (*T7_).Sup.Sup.Sup.message; (*T7_).Sup.Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TM__SLGpYVEqpFQ7VaPsJH6HIA_4));
			if (T8_) nimGCunrefNoCycle(T8_);
			asgnRef((void**) (&(*T7_).Sup.Sup.Sup.parent), ((Exception*) NIM_NIL));
			nimln_(316, "/home/yyoncho/Sources/nim/Nim/lib/wrappers/openssl.nim");
			raiseExceptionEx((Exception*)T7_, "LibraryError", "sslModule", "/home/yyoncho/Sources/nim/Nim/lib/wrappers/openssl.nim", 316);
			popCurrentException();
		}
	}
	if (TM__SLGpYVEqpFQ7VaPsJH6HIA_2.status != 0) reraiseException();
	nimln_(318, "/home/yyoncho/Sources/nim/Nim/lib/wrappers/openssl.nim");
	result = sslMod__wrappersZopenssl_179;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void*, sslSymNullable__wrappersZopenssl_190)(NimStringDesc* name, NimStringDesc* alternativeName) {
	void* result;
	void* T1_;
	nimfr_("sslSymNullable", "/home/yyoncho/Sources/nim/Nim/lib/wrappers/openssl.nim");
	result = (void*)0;
	nimln_(342, "/home/yyoncho/Sources/nim/Nim/lib/wrappers/openssl.nim");
	T1_ = (void*)0;
	T1_ = sslModule__wrappersZopenssl_177();
	result = symNullable__wrappersZopenssl_184(T1_, name, alternativeName);
	popFrame();
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}
static N_INLINE(void, copyMem__system_1727)(void* dest, void* source, NI size) {
	nimCopyMem(dest, source, size);
}
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	{
		if (!!((src == ((NimStringDesc*) NIM_NIL)))) goto LA3_;
		copyMem__system_1727(((void*) ((&(*dest).data[(*dest).Sup.len]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
		(*dest).Sup.len += (*src).Sup.len;
	}
	LA3_: ;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SslStruct__hZKic6WnTBMq6Usbg49bnhw*, loadPSSLMethod__wrappersZopenssl_202)(NimStringDesc* method1, NimStringDesc* method2) {
	tyObject_SslStruct__hZKic6WnTBMq6Usbg49bnhw* result;
	void* methodSym;
	tyProc__HXibadfWHwHwyhCwpIRD2A method2Proc;
	nimfr_("loadPSSLMethod", "/home/yyoncho/Sources/nim/Nim/lib/wrappers/openssl.nim");
{	result = (tyObject_SslStruct__hZKic6WnTBMq6Usbg49bnhw*)0;
	nimln_(354, "/home/yyoncho/Sources/nim/Nim/lib/wrappers/openssl.nim");
	methodSym = sslSymNullable__wrappersZopenssl_190(method1, method2);
	nimln_(355, "/home/yyoncho/Sources/nim/Nim/lib/wrappers/openssl.nim");
	{
		tyObject_LibraryError__x1muge9crz9aAVqWWUrEL9aXg* T5_;
		NimStringDesc* T6_;
		if (!(methodSym == 0)) goto LA3_;
		T5_ = NIM_NIL;
		T5_ = (tyObject_LibraryError__x1muge9crz9aAVqWWUrEL9aXg*) newObj((&NTIreflibraryerror__HV2B9a6TW6WPpQna2mQFeQQ_), sizeof(tyObject_LibraryError__x1muge9crz9aAVqWWUrEL9aXg));
		(*T5_).Sup.Sup.Sup.Sup.m_type = (&NTIlibraryerror__x1muge9crz9aAVqWWUrEL9aXg_);
		(*T5_).Sup.Sup.Sup.name = "LibraryError";
		nimln_(356, "/home/yyoncho/Sources/nim/Nim/lib/wrappers/openssl.nim");
		T6_ = NIM_NIL;
		T6_ = rawNewString((method1 ? method1->Sup.len : 0) + (method2 ? method2->Sup.len : 0) + 20);
appendString(T6_, ((NimStringDesc*) &TM__SLGpYVEqpFQ7VaPsJH6HIA_5));
appendString(T6_, method1);
appendString(T6_, ((NimStringDesc*) &TM__SLGpYVEqpFQ7VaPsJH6HIA_6));
appendString(T6_, method2);
		asgnRef((void**) (&(*T5_).Sup.Sup.Sup.message), T6_);
		asgnRef((void**) (&(*T5_).Sup.Sup.Sup.parent), ((Exception*) NIM_NIL));
		raiseExceptionEx((Exception*)T5_, "LibraryError", "loadPSSLMethod", "/home/yyoncho/Sources/nim/Nim/lib/wrappers/openssl.nim", 356);
	}
	LA3_: ;
	nimln_(358, "/home/yyoncho/Sources/nim/Nim/lib/wrappers/openssl.nim");
	method2Proc = ((tyProc__HXibadfWHwHwyhCwpIRD2A) (methodSym));
	nimln_(359, "/home/yyoncho/Sources/nim/Nim/lib/wrappers/openssl.nim");
	result = method2Proc();
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SslStruct__hZKic6WnTBMq6Usbg49bnhw*, TLS_method__wrappersZopenssl_245)(void) {
	tyObject_SslStruct__hZKic6WnTBMq6Usbg49bnhw* result;
	nimfr_("TLS_method", "/home/yyoncho/Sources/nim/Nim/lib/wrappers/openssl.nim");
	result = (tyObject_SslStruct__hZKic6WnTBMq6Usbg49bnhw*)0;
	nimln_(370, "/home/yyoncho/Sources/nim/Nim/lib/wrappers/openssl.nim");
	result = loadPSSLMethod__wrappersZopenssl_202(((NimStringDesc*) &TM__SLGpYVEqpFQ7VaPsJH6HIA_7), ((NimStringDesc*) &TM__SLGpYVEqpFQ7VaPsJH6HIA_8));
	popFrame();
	return result;
}
static N_INLINE(void*, utilModule__wrappersZopenssl_181)(void) {
	void* result;
	nimfr_("utilModule", "/home/yyoncho/Sources/nim/Nim/lib/wrappers/openssl.nim");
	result = (void*)0;
	nimln_(322, "/home/yyoncho/Sources/nim/Nim/lib/wrappers/openssl.nim");
	{
		if (!(utilMod__wrappersZopenssl_183 == 0)) goto LA3_;
		utilMod__wrappersZopenssl_183 = loadLibPattern__pureZdynlib_49(((NimStringDesc*) &TM__SLGpYVEqpFQ7VaPsJH6HIA_14), NIM_FALSE);
	}
	LA3_: ;
	nimln_(324, "/home/yyoncho/Sources/nim/Nim/lib/wrappers/openssl.nim");
	result = utilMod__wrappersZopenssl_183;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void*, utilSymNullable__wrappersZopenssl_198)(NimStringDesc* name, NimStringDesc* alternativeName) {
	void* result;
	void* T1_;
	nimfr_("utilSymNullable", "/home/yyoncho/Sources/nim/Nim/lib/wrappers/openssl.nim");
	result = (void*)0;
	nimln_(349, "/home/yyoncho/Sources/nim/Nim/lib/wrappers/openssl.nim");
	T1_ = (void*)0;
	T1_ = utilModule__wrappersZopenssl_181();
	result = symNullable__wrappersZopenssl_184(T1_, name, alternativeName);
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(unsigned long, getOpenSSLVersion__wrappersZopenssl_253)(void) {
	unsigned long result;
	tyProc__HBcM2Mt9bfW9bP8CkO25r0mA theProc;
	void* T1_;
	nimfr_("getOpenSSLVersion", "/home/yyoncho/Sources/nim/Nim/lib/wrappers/openssl.nim");
	result = (unsigned long)0;
	nimln_(379, "/home/yyoncho/Sources/nim/Nim/lib/wrappers/openssl.nim");
	T1_ = (void*)0;
	T1_ = utilSymNullable__wrappersZopenssl_198(((NimStringDesc*) &TM__SLGpYVEqpFQ7VaPsJH6HIA_30), ((NimStringDesc*) &TM__SLGpYVEqpFQ7VaPsJH6HIA_31));
	theProc = ((tyProc__HBcM2Mt9bfW9bP8CkO25r0mA) (T1_));
	nimln_(381, "/home/yyoncho/Sources/nim/Nim/lib/wrappers/openssl.nim");
	{
		if (!(theProc == 0)) goto LA4_;
		result = ((unsigned long) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		nimln_(382, "/home/yyoncho/Sources/nim/Nim/lib/wrappers/openssl.nim");
		result = theProc();
	}
	LA2_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void*, sslSymThrows__wrappersZopenssl_194)(NimStringDesc* name, NimStringDesc* alternativeName) {
	void* result;
	nimfr_("sslSymThrows", "/home/yyoncho/Sources/nim/Nim/lib/wrappers/openssl.nim");
	result = (void*)0;
	nimln_(345, "/home/yyoncho/Sources/nim/Nim/lib/wrappers/openssl.nim");
	result = sslSymNullable__wrappersZopenssl_190(name, alternativeName);
	nimln_(346, "/home/yyoncho/Sources/nim/Nim/lib/wrappers/openssl.nim");
	{
		if (!(result == 0)) goto LA3_;
		raiseInvalidLibrary__pureZdynlib_9(nimToCStringConv(name));
	}
	LA3_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(int, SSL_CTX_set_ciphersuites__wrappersZopenssl_294)(tyObject_SslStruct__hZKic6WnTBMq6Usbg49bnhw* ctx, NCSTRING str) {
	int result;
	nimfr_("SSL_CTX_set_ciphersuites", "/home/yyoncho/Sources/nim/Nim/lib/wrappers/openssl.nim");
	result = (int)0;
	nimln_(401, "/home/yyoncho/Sources/nim/Nim/lib/wrappers/openssl.nim");
	{
		void* T5_;
		if (!(theProc__wrappersZopenssl_301 == 0)) goto LA3_;
		nimln_(402, "/home/yyoncho/Sources/nim/Nim/lib/wrappers/openssl.nim");
		T5_ = (void*)0;
		T5_ = sslSymThrows__wrappersZopenssl_194(((NimStringDesc*) &TM__SLGpYVEqpFQ7VaPsJH6HIA_32), ((NimStringDesc*) NIM_NIL));
		theProc__wrappersZopenssl_301 = ((tyProc__IX9aeaSWx4arDCJq04EsJjQ) (T5_));
	}
	LA3_: ;
	nimln_(403, "/home/yyoncho/Sources/nim/Nim/lib/wrappers/openssl.nim");
	theProc__wrappersZopenssl_301(ctx, str);
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, SSLCTXSetMode__wrappersZopenssl_516)(tyObject_SslStruct__hZKic6WnTBMq6Usbg49bnhw* ctx, NI mode) {
	NI result;
	long T1_;
	nimfr_("SSLCTXSetMode", "/home/yyoncho/Sources/nim/Nim/lib/wrappers/openssl.nim");
	result = (NI)0;
	nimln_(538, "/home/yyoncho/Sources/nim/Nim/lib/wrappers/openssl.nim");
	if ((mode) < ((long) (-2147483647 -1)) || (mode) > ((long) 2147483647)){ raiseRangeErrorI(mode, ((long) (-2147483647 -1)), ((long) 2147483647)); }
	T1_ = (long)0;
	T1_ = Dl_2147484155_(ctx, ((int) 33), ((long) (mode)), NIM_NIL);
	result = ((NI) (T1_));
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(int, SSL_in_init__wrappersZopenssl_269)(tyObject_SslStruct__hZKic6WnTBMq6Usbg49bnhw* ssl) {
	int result;
	nimfr_("SSL_in_init", "/home/yyoncho/Sources/nim/Nim/lib/wrappers/openssl.nim");
	result = (int)0;
	nimln_(392, "/home/yyoncho/Sources/nim/Nim/lib/wrappers/openssl.nim");
	{
		if (!!((theProc__wrappersZopenssl_275 == 0))) goto LA3_;
		nimln_(393, "/home/yyoncho/Sources/nim/Nim/lib/wrappers/openssl.nim");
		result = theProc__wrappersZopenssl_275(ssl);
	}
	goto LA1_;
	LA3_: ;
	{
		int T8_;
		nimln_(394, "/home/yyoncho/Sources/nim/Nim/lib/wrappers/openssl.nim");
		if (!!((sslState__wrappersZopenssl_278 == 0))) goto LA6_;
		nimln_(395, "/home/yyoncho/Sources/nim/Nim/lib/wrappers/openssl.nim");
		T8_ = (int)0;
		T8_ = sslState__wrappersZopenssl_278(ssl);
		result = (NI32)(T8_ & ((NI32) 12288));
	}
	goto LA1_;
	LA6_: ;
	{
		nimln_(397, "/home/yyoncho/Sources/nim/Nim/lib/wrappers/openssl.nim");
		raiseInvalidLibrary__pureZdynlib_9("SSL_in_init");
	}
	LA1_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, SSL_set_tlsext_host_name__wrappersZopenssl_525)(tyObject_SslStruct__hZKic6WnTBMq6Usbg49bnhw* ssl, NCSTRING name) {
	NI result;
	nimfr_("SSL_set_tlsext_host_name", "/home/yyoncho/Sources/nim/Nim/lib/wrappers/openssl.nim");
	result = (NI)0;
	nimln_(546, "/home/yyoncho/Sources/nim/Nim/lib/wrappers/openssl.nim");
	result = Dl_2147484168_(ssl, ((int) 55), ((NI) 0), ((void*) (name)));
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsNimatslibatswrappersatsopenssldotnim_Init000)(void) {
{
	TFrame FR_; FR_.len = 0;
	void* T100001_;
	void* T100002_;
	nimln_(388, "/home/yyoncho/Sources/nim/Nim/lib/wrappers/openssl.nim");
	T100001_ = (void*)0;
	T100001_ = sslSymNullable__wrappersZopenssl_190(((NimStringDesc*) &TM__SLGpYVEqpFQ7VaPsJH6HIA_45), ((NimStringDesc*) NIM_NIL));
	theProc__wrappersZopenssl_275 = ((tyProc__Vff1ipOwDPDGknaRJAdXjA) (T100001_));
	nimln_(390, "/home/yyoncho/Sources/nim/Nim/lib/wrappers/openssl.nim");
	T100002_ = (void*)0;
	T100002_ = sslSymNullable__wrappersZopenssl_190(((NimStringDesc*) &TM__SLGpYVEqpFQ7VaPsJH6HIA_46), ((NimStringDesc*) NIM_NIL));
	sslState__wrappersZopenssl_278 = ((tyProc__Vff1ipOwDPDGknaRJAdXjA) (T100002_));
}/* preInitProc end */
{
}
}

N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsNimatslibatswrappersatsopenssldotnim_DatInit000)(void) {
static TNimNode TM__SLGpYVEqpFQ7VaPsJH6HIA_0[1];
NTIsslstruct__hZKic6WnTBMq6Usbg49bnhw_.size = sizeof(tyObject_SslStruct__hZKic6WnTBMq6Usbg49bnhw);
NTIsslstruct__hZKic6WnTBMq6Usbg49bnhw_.align = NIM_ALIGNOF(tyObject_SslStruct__hZKic6WnTBMq6Usbg49bnhw);
NTIsslstruct__hZKic6WnTBMq6Usbg49bnhw_.kind = 18;
NTIsslstruct__hZKic6WnTBMq6Usbg49bnhw_.base = 0;
NTIsslstruct__hZKic6WnTBMq6Usbg49bnhw_.flags = 1;
TM__SLGpYVEqpFQ7VaPsJH6HIA_0[0].len = 0; TM__SLGpYVEqpFQ7VaPsJH6HIA_0[0].kind = 2;
NTIsslstruct__hZKic6WnTBMq6Usbg49bnhw_.node = &TM__SLGpYVEqpFQ7VaPsJH6HIA_0[0];
NTIsslctx__QQ33RYEe889cv60wm9bVkd8A_.size = sizeof(tyObject_SslStruct__hZKic6WnTBMq6Usbg49bnhw*);
NTIsslctx__QQ33RYEe889cv60wm9bVkd8A_.align = NIM_ALIGNOF(tyObject_SslStruct__hZKic6WnTBMq6Usbg49bnhw*);
NTIsslctx__QQ33RYEe889cv60wm9bVkd8A_.kind = 21;
NTIsslctx__QQ33RYEe889cv60wm9bVkd8A_.base = (&NTIsslstruct__hZKic6WnTBMq6Usbg49bnhw_);
NTIsslctx__QQ33RYEe889cv60wm9bVkd8A_.flags = 3;
if (!((TM__SLGpYVEqpFQ7VaPsJH6HIA_9 = nimLoadLibrary(((NimStringDesc*) &TM__SLGpYVEqpFQ7VaPsJH6HIA_11)))
||(TM__SLGpYVEqpFQ7VaPsJH6HIA_9 = nimLoadLibrary(((NimStringDesc*) &TM__SLGpYVEqpFQ7VaPsJH6HIA_13)))
)) nimLoadLibraryError(((NimStringDesc*) &TM__SLGpYVEqpFQ7VaPsJH6HIA_14));
	Dl_2147484094_ = (tyProc__HBcM2Mt9bfW9bP8CkO25r0mA) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_9, "ERR_peek_last_error");
	Dl_2147484090_ = (tyProc__ILGNrKdZ6rU9bHuzDylmHhA) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_9, "ERR_error_string");
if (!((TM__SLGpYVEqpFQ7VaPsJH6HIA_19 = nimLoadLibrary(((NimStringDesc*) &TM__SLGpYVEqpFQ7VaPsJH6HIA_21)))
||(TM__SLGpYVEqpFQ7VaPsJH6HIA_19 = nimLoadLibrary(((NimStringDesc*) &TM__SLGpYVEqpFQ7VaPsJH6HIA_23)))
||(TM__SLGpYVEqpFQ7VaPsJH6HIA_19 = nimLoadLibrary(((NimStringDesc*) &TM__SLGpYVEqpFQ7VaPsJH6HIA_25)))
)) nimLoadLibraryError(((NimStringDesc*) &TM__SLGpYVEqpFQ7VaPsJH6HIA_3));
	Dl_2147483981_ = (tyProc__Rqjya8uauy9aPcyfGamaSrg) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_19, "SSL_CTX_new");
	Dl_2147483998_ = (tyProc__2PA7CxitARKs0jpUW1gQ0g) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_19, "SSL_CTX_set_cipher_list");
	Dl_2147484155_ = (tyProc__J5jVzoevP749cPcyUg9cwPEA) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_19, "SSL_CTX_ctrl");
	Dl_2147483989_ = (tyProc__H5wL7jexPlRA7WCw9cqLm0A) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_19, "SSL_CTX_set_verify");
	Dl_2147484005_ = (tyProc__tYatIIo0oRSB9bjHLep7yhQ) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_19, "SSL_CTX_use_certificate_chain_file");
	Dl_2147484008_ = (tyProc__xjxKRHVZXDqdWXw9bunoZ3w) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_19, "SSL_CTX_use_PrivateKey_file");
	Dl_2147484012_ = (tyProc__Vff1ipOwDPDGknaRJAdXjA) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_19, "SSL_CTX_check_private_key");
	Dl_2147483983_ = (tyProc__gZVmmOpGrWMJL1q0d9bMEZQ) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_19, "SSL_CTX_load_verify_locations");
	Dl_2147484260_ = (tyProc__ln4kdL5W9bbX4a1xl8nnVXQ) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_9, "ERR_clear_error");
	Dl_2147484030_ = (tyProc__Vff1ipOwDPDGknaRJAdXjA) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_19, "SSL_shutdown");
	Dl_2147484047_ = (tyProc__kxUw9cdxJbPtv0iPyoSbDBQ) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_19, "SSL_get_error");
	Dl_2147483968_ = (tyProc__e47RoMUolEGMiUlfiZt9abQ) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_19, "SSL_free");
	Dl_2147483966_ = (tyProc__Rqjya8uauy9aPcyfGamaSrg) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_19, "SSL_new");
	Dl_2147484027_ = (tyProc__EJ9cbYwLVOng2t4wnewGkmA) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_19, "SSL_set_fd");
	Dl_2147484168_ = (tyProc__xGcw2zK9bzuUE9c8WzKW5hzw) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_19, "SSL_ctrl");
	Dl_2147484037_ = (tyProc__Vff1ipOwDPDGknaRJAdXjA) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_19, "SSL_connect");
	Dl_2147484050_ = (tyProc__Vff1ipOwDPDGknaRJAdXjA) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_19, "SSL_accept");
	Dl_2147484043_ = (tyProc__sG7rgqmtlgBaumPwwN3BfQ) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_19, "SSL_write");
	Dl_2147484052_ = (tyProc__Vff1ipOwDPDGknaRJAdXjA) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_19, "SSL_pending");
	Dl_2147484039_ = (tyProc__09aW01hZ1tSPafLaWVpBcXA) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_19, "SSL_read");
}

