/* Generated by Nim Compiler v1.6.11 */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_OptParser__l9cyoK9aLLTUH7LBRIbLqETg tyObject_OptParser__l9cyoK9aLLTUH7LBRIbLqETg;
typedef struct RootObj RootObj;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ tySequence__sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack__7fytPA5bBsob6See21YMRA tyObject_GcStack__7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple__ujsjpB2O9cjj3uDHsXbnSzg tyTuple__ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg;
typedef NU8 tyEnum_CmdLineKind__XkdXq9atxjiuhkFFh0XYrSA;
typedef NU8 tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc__ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
NI align;
tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc__ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct RootObj {
TNimType* m_type;
};
typedef NU8 tySet_tyChar__nmiMWKVIe46vacnhAFrQvw[32];
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyObject_OptParser__l9cyoK9aLLTUH7LBRIbLqETg {
  RootObj Sup;
NI pos;
NIM_BOOL inShortState;
NIM_BOOL allowWhitespaceAfterColon;
tySet_tyChar__nmiMWKVIe46vacnhAFrQvw shortNoVal;
tySequence__sM4lkSb7zS6F7OVMvW9cffQ* longNoVal;
tySequence__sM4lkSb7zS6F7OVMvW9cffQ* cmds;
NI idx;
tyEnum_CmdLineKind__XkdXq9atxjiuhkFFh0XYrSA kind;
NimStringDesc* key;
NimStringDesc* val;
};
struct tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack__7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ* tyArray__SPr7N6UKfuF549bNPiUvSRw[256];
typedef NU32 tyArray__BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg* tyArray__N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray__N1u1nqOgmuJN9cSZrnMHgOQ tyArray__B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw* tyArray__lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA {
tyArray__lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* tyArray__0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw {
tyArray__0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple__ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple__ujsjpB2O9cjj3uDHsXbnSzg tyArray__LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray__LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray__SPr7N6UKfuF549bNPiUvSRw freeSmallChunks;
NU32 flBitmap;
tyArray__BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray__B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack__7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
NI zctThreshold;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
typedef NU8 tyArray__S8ib5N31oJbAkqOZTlNg5Q[8192];
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size);
N_LIB_PRIVATE N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size);
N_LIB_PRIVATE N_NIMCALL(void, genericSeqAssign)(void* dest, void* src, TNimType* mt);
N_LIB_PRIVATE N_NIMCALL(tySequence__sM4lkSb7zS6F7OVMvW9cffQ*, newSeq__systemZio_594)(NI len);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i, NI64 a, NI64 b);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i, NI n);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(void, decRef__system_5399)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(NI, minuspercent___system_716)(NI x, NI y);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_2999)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NIM_BOOL, ltpercent___system_1005)(NI x, NI y);
static N_INLINE(void, rtlAddZCT__system_5397)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT__system_5348)(tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell__system_5354)(void* usr);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(NI, nosparamCount)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nosparamStr)(NI i);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef__system_5392)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(NI, pluspercent___system_696)(NI x, NI y);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, setLengthStr)(NimStringDesc* s, NI newLen);
N_LIB_PRIVATE N_NIMCALL(void, handleShortOption__pureZparseopt_127)(tyObject_OptParser__l9cyoK9aLLTUH7LBRIbLqETg* p, NimStringDesc* cmd);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
static N_INLINE(NI, cardSet)(tyArray__S8ib5N31oJbAkqOZTlNg5Q s, NI len);
static N_INLINE(NI, countBits64)(NU64 n);
static N_INLINE(NI, countSetBitsImpl__systemZcountbits95impl_61)(NU64 x);
N_CDECL(int, __builtin_popcountll)(unsigned long long x);
static N_INLINE(NI, countBits32)(NU32 n);
static N_INLINE(NI, countSetBitsImpl__systemZcountbits95impl_26)(NU32 x);
N_CDECL(int, __builtin_popcount)(unsigned int x);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, substr__system_7857)(NimStringDesc* s, NI first);
N_LIB_PRIVATE N_NIMCALL(NI, parseWord__pureZparseopt_25)(NimStringDesc* s, NI i, NimStringDesc** w, tySet_tyChar__nmiMWKVIe46vacnhAFrQvw delim);
static N_INLINE(NIM_BOOL, contains__stdZenumutils_43)(NimStringDesc** a, NI aLen_0, NimStringDesc* item);
static N_INLINE(NI, find__stdZenumutils_48)(NimStringDesc** a, NI aLen_0, NimStringDesc* item);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(NIM_BOOL, equalMem__system_1735)(void* a, void* b, NI size);
static N_INLINE(int, nimCmpMem)(void* a, void* b, NI size);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_LIB_PRIVATE TNimType NTIcmdlinekind__XkdXq9atxjiuhkFFh0XYrSA_;
extern TNimType NTIrootobj__ytyiCJqK439aF9cIibuRVpAg_;
N_LIB_PRIVATE TNimType NTIoptparser__l9cyoK9aLLTUH7LBRIbLqETg_;
extern TNimType NTIint__rR5Bzr1D5krxoo1NcNyeMA_;
extern TNimType NTIbool__VaVACK0bpYmqIQ0mKcHfQQ_;
extern TNimType NTIchar__nmiMWKVIe46vacnhAFrQvw_;
N_LIB_PRIVATE TNimType NTIsetLcharT__HDqWPvEAxZK51ZcfaeQEdg_;
extern TNimType NTIseqLstringT__sM4lkSb7zS6F7OVMvW9cffQ_;
extern TNimType NTIstring__77mFvmsOLKik79ci2hXkHEg_;
static NIM_CONST tySet_tyChar__nmiMWKVIe46vacnhAFrQvw TM__GYgvYKeHVTEls0AcywABHQ_23 = {
0x00, 0x02, 0x00, 0x00, 0x01, 0x00, 0x00, 0x24,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
extern TFrame* framePtr__system_2566;
extern TFrame* framePtr__system_2566;
extern TFrame* framePtr__system_2566;
extern TFrame* framePtr__system_2566;
extern TFrame* framePtr__system_2566;
extern TFrame* framePtr__system_2566;
extern tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ gch__system_5301;
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a, v, ((size_t) (size)));
}
static N_INLINE(void, nimZeroMem)(void* p, NI size) {
	nimSetMem__systemZmemory_7(p, ((int) 0), size);
}
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}
static N_INLINE(void, nimFrame)(TFrame* s) {
	{
		if (!(framePtr__system_2566 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s).calldepth = ((NI16) 0);
	}
	goto LA1_;
	LA3_: ;
	{
		(*s).calldepth = (NI16)((*framePtr__system_2566).calldepth + ((NI16) 1));
	}
	LA1_: ;
	(*s).prev = framePtr__system_2566;
	framePtr__system_2566 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;
		callDepthLimitReached__system_2999();
	}
	LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_2566 = (*framePtr__system_2566).prev;
}
static N_INLINE(NI, minuspercent___system_716)(NI x, NI y) {
	NI result;
	nimfr_("-%", "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/arithmetics.nim");
	result = (NI)0;
	nimln_(414, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/arithmetics.nim");
	nimln_(418, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/arithmetics.nim");
	result = ((NI) ((NU)((NU64)(((NU) (x))) - (NU64)(((NU) (y))))));
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, ltpercent___system_1005)(NI x, NI y) {
	NIM_BOOL result;
	nimfr_("<%", "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/comparisons.nim");
	result = (NIM_BOOL)0;
	nimln_(186, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/comparisons.nim");
	nimln_(188, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/comparisons.nim");
	result = ((NU64)(((NU) (x))) < (NU64)(((NU) (y))));
	popFrame();
	return result;
}
static N_INLINE(void, rtlAddZCT__system_5397)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/gc.nim");
	nimln_(243, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/gc.nim");
	addZCT__system_5348((&gch__system_5301.zct), c);
	popFrame();
}
static N_INLINE(void, decRef__system_5399)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("decRef", "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/gc.nim");
	nimln_(248, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/gc.nim");
	(*c).refcount = minuspercent___system_716((*c).refcount, ((NI) 8));
	nimln_(249, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/gc.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = ltpercent___system_1005((*c).refcount, ((NI) 8));
		if (!T3_) goto LA4_;
		nimln_(250, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/gc.nim");
		rtlAddZCT__system_5397(c);
	}
	LA4_: ;
	popFrame();
}
static N_INLINE(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell__system_5354)(void* usr) {
	tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* result;
	NI T1_;
	nimfr_("usrToCell", "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/gc.nim");
	result = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(177, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/gc.nim");
	T1_ = (NI)0;
	T1_ = minuspercent___system_716(((NI) (ptrdiff_t) (usr)), ((NI) 16));
	result = ((tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*) (T1_));
	popFrame();
	return result;
}
static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T1_;
	nimfr_("nimGCunrefNoCycle", "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/gc.nim");
	nimln_(276, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/gc.nim");
	T1_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
	T1_ = usrToCell__system_5354(p);
	decRef__system_5399(T1_);
	popFrame();
}
static N_INLINE(NI, pluspercent___system_696)(NI x, NI y) {
	NI result;
	nimfr_("+%", "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/arithmetics.nim");
	result = (NI)0;
	nimln_(403, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/arithmetics.nim");
	nimln_(407, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/arithmetics.nim");
	result = ((NI) ((NU)((NU64)(((NU) (x))) + (NU64)(((NU) (y))))));
	popFrame();
	return result;
}
static N_INLINE(void, incRef__system_5392)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("incRef", "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/gc.nim");
	nimln_(231, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/gc.nim");
	(*c).refcount = pluspercent___system_696((*c).refcount, ((NI) 8));
	popFrame();
}
static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr_("asgnRef", "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/gc.nim");
	nimln_(286, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/gc.nim");
	{
		tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell__system_5354(src);
		incRef__system_5392(T5_);
	}
	LA3_: ;
	nimln_(287, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/gc.nim");
	{
		tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell__system_5354((*dest));
		decRef__system_5399(T10_);
	}
	LA8_: ;
	nimln_(288, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/gc.nim");
	(*dest) = src;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, initOptParser__pureZparseopt_83)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ* cmdline, tySet_tyChar__nmiMWKVIe46vacnhAFrQvw shortNoVal, tySequence__sM4lkSb7zS6F7OVMvW9cffQ* longNoVal, NIM_BOOL allowWhitespaceAfterColon, tyObject_OptParser__l9cyoK9aLLTUH7LBRIbLqETg* Result) {
	nimfr_("initOptParser", "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
	(*Result).pos = 0;
	(*Result).inShortState = 0;
	(*Result).allowWhitespaceAfterColon = 0;
	nimZeroMem((*Result).shortNoVal, sizeof(tySet_tyChar__nmiMWKVIe46vacnhAFrQvw));
	unsureAsgnRef((void**)&(*Result).longNoVal, NIM_NIL);
	unsureAsgnRef((void**)&(*Result).cmds, NIM_NIL);
	(*Result).idx = 0;
	(*Result).kind = 0;
	unsureAsgnRef((void**)&(*Result).key, NIM_NIL);
	unsureAsgnRef((void**)&(*Result).val, NIM_NIL);
	(*Result).Sup.m_type = (&NTIoptparser__l9cyoK9aLLTUH7LBRIbLqETg_);
	nimln_(260, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
	(*Result).pos = ((NI) 0);
	nimln_(261, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
	(*Result).idx = ((NI) 0);
	nimln_(262, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
	(*Result).inShortState = NIM_FALSE;
	nimln_(263, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
	nimCopyMem((void*)(*Result).shortNoVal, (NIM_CONST void*)shortNoVal, 32);
	nimln_(264, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
	genericSeqAssign((&(*Result).longNoVal), longNoVal, (&NTIseqLstringT__sM4lkSb7zS6F7OVMvW9cffQ_));
	nimln_(265, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
	(*Result).allowWhitespaceAfterColon = allowWhitespaceAfterColon;
	nimln_(266, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
	{
		NI T3_;
		NI T6_;
		T3_ = (cmdline ? cmdline->Sup.len : 0);
		if (!!((T3_ == ((NI) 0)))) goto LA4_;
		nimln_(267, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
		T6_ = (cmdline ? cmdline->Sup.len : 0);
		if ((T6_) < ((NI) 0) || (T6_) > ((NI) IL64(9223372036854775807))){ raiseRangeErrorI(T6_, ((NI) 0), ((NI) IL64(9223372036854775807))); }
		unsureAsgnRef((void**) (&(*Result).cmds), newSeq__systemZio_594(((NI) (T6_))));
		{
			NI i;
			NI colontmp_;
			NI T8_;
			NI i_2;
			i = (NI)0;
			colontmp_ = (NI)0;
			nimln_(268, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
			T8_ = (cmdline ? cmdline->Sup.len : 0);
			colontmp_ = T8_;
			nimln_(119, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/iterators_1.nim");
			i_2 = ((NI) 0);
			{
				nimln_(120, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/iterators_1.nim");
				while (1) {
					NimStringDesc* T11_;
					NI TM__GYgvYKeHVTEls0AcywABHQ_6;
					if (!(i_2 < colontmp_)) goto LA10;
					nimln_(268, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
					i = i_2;
					if (i < 0 || i >= ((*Result).cmds ? (*Result).cmds->Sup.len : 0)){ raiseIndexError2(i,((*Result).cmds ? (*Result).cmds->Sup.len : 0)-1); }
					if (i < 0 || i >= (cmdline ? cmdline->Sup.len : 0)){ raiseIndexError2(i,(cmdline ? cmdline->Sup.len : 0)-1); }
					T11_ = NIM_NIL;
					T11_ = (*Result).cmds->data[i]; (*Result).cmds->data[i] = copyStringRC1(cmdline->data[i]);
					if (T11_) nimGCunrefNoCycle(T11_);
					nimln_(122, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/iterators_1.nim");
					if (nimAddInt(i_2, ((NI) 1), &TM__GYgvYKeHVTEls0AcywABHQ_6)) { raiseOverflow(); };
					i_2 = (NI)(TM__GYgvYKeHVTEls0AcywABHQ_6);
				} LA10: ;
			}
		}
	}
	goto LA1_;
	LA4_: ;
	{
		NI T13_;
		nimln_(272, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
		T13_ = (NI)0;
		T13_ = nosparamCount();
		if ((T13_) < ((NI) 0) || (T13_) > ((NI) IL64(9223372036854775807))){ raiseRangeErrorI(T13_, ((NI) 0), ((NI) IL64(9223372036854775807))); }
		unsureAsgnRef((void**) (&(*Result).cmds), newSeq__systemZio_594(((NI) (T13_))));
		{
			NI i_3;
			NI colontmp__2;
			NI res;
			i_3 = (NI)0;
			colontmp__2 = (NI)0;
			nimln_(273, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
			colontmp__2 = nosparamCount();
			nimln_(65, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/iterators_1.nim");
			res = ((NI) 1);
			{
				nimln_(66, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/iterators_1.nim");
				while (1) {
					NI TM__GYgvYKeHVTEls0AcywABHQ_7;
					NI TM__GYgvYKeHVTEls0AcywABHQ_8;
					if (!(res <= colontmp__2)) goto LA16;
					nimln_(273, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
					i_3 = res;
					nimln_(274, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
					if (nimSubInt(i_3, ((NI) 1), &TM__GYgvYKeHVTEls0AcywABHQ_7)) { raiseOverflow(); };
					if ((NI)(TM__GYgvYKeHVTEls0AcywABHQ_7) < 0 || (NI)(TM__GYgvYKeHVTEls0AcywABHQ_7) >= ((*Result).cmds ? (*Result).cmds->Sup.len : 0)){ raiseIndexError2((NI)(TM__GYgvYKeHVTEls0AcywABHQ_7),((*Result).cmds ? (*Result).cmds->Sup.len : 0)-1); }
					nimln_(273, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
					asgnRef((void**) (&(*Result).cmds->data[(NI)(TM__GYgvYKeHVTEls0AcywABHQ_7)]), nosparamStr(i_3));
					nimln_(68, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/iterators_1.nim");
					if (nimAddInt(res, ((NI) 1), &TM__GYgvYKeHVTEls0AcywABHQ_8)) { raiseOverflow(); };
					res = (NI)(TM__GYgvYKeHVTEls0AcywABHQ_8);
				} LA16: ;
			}
		}
	}
	LA1_: ;
	nimln_(280, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
	(*Result).kind = ((tyEnum_CmdLineKind__XkdXq9atxjiuhkFFh0XYrSA) 0);
	nimln_(281, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
	unsureAsgnRef((void**) (&(*Result).key), ((NimStringDesc*) NIM_NIL));
	nimln_(282, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
	unsureAsgnRef((void**) (&(*Result).val), ((NimStringDesc*) NIM_NIL));
	popFrame();
}
static N_INLINE(NI, countSetBitsImpl__systemZcountbits95impl_61)(NU64 x) {
	NI result;
	int T1_;
	nimfr_("countSetBitsImpl", "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/countbits_impl.nim");
	result = (NI)0;
	nimln_(75, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/countbits_impl.nim");
	T1_ = (int)0;
	T1_ = __builtin_popcountll(x);
	result = ((NI) (T1_));
	popFrame();
	return result;
}
static N_INLINE(NI, countBits64)(NU64 n) {
	NI result;
	nimfr_("countBits64", "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/countbits_impl.nim");
	result = (NI)0;
	nimln_(95, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/countbits_impl.nim");
	result = countSetBitsImpl__systemZcountbits95impl_61(n);
	popFrame();
	return result;
}
static N_INLINE(NI, countSetBitsImpl__systemZcountbits95impl_26)(NU32 x) {
	NI result;
	int T1_;
	nimfr_("countSetBitsImpl", "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/countbits_impl.nim");
	result = (NI)0;
	nimln_(74, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/countbits_impl.nim");
	T1_ = (int)0;
	T1_ = __builtin_popcount(x);
	result = ((NI) (T1_));
	popFrame();
	return result;
}
static N_INLINE(NI, countBits32)(NU32 n) {
	NI result;
	nimfr_("countBits32", "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/countbits_impl.nim");
	result = (NI)0;
	nimln_(92, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/countbits_impl.nim");
	result = countSetBitsImpl__systemZcountbits95impl_26(n);
	popFrame();
	return result;
}
static N_INLINE(NI, cardSet)(tyArray__S8ib5N31oJbAkqOZTlNg5Q s, NI len) {
	NI result;
	NI i;
	nimfr_("cardSet", "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/sets.nim");
	result = (NI)0;
	nimln_(17, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/sets.nim");
	i = ((NI) 0);
	nimln_(18, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/sets.nim");
	result = ((NI) 0);
	{
		nimln_(20, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/sets.nim");
		while (1) {
			NI T3_;
			if (!(i < (NI)(len - ((NI) 8)))) goto LA2;
			nimln_(21, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/sets.nim");
			T3_ = (NI)0;
			T3_ = countBits64((*((NU64*) ((&s[(i)- 0])))));
			result += T3_;
			nimln_(22, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/sets.nim");
			i += ((NI) 8);
		} LA2: ;
	}
	{
		nimln_(24, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/sets.nim");
		while (1) {
			NI T6_;
			if (!(i < len)) goto LA5;
			nimln_(25, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/sets.nim");
			T6_ = (NI)0;
			T6_ = countBits32(((NU32) (s[(i)- 0])));
			result += T6_;
			nimln_(26, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/sets.nim");
			i += ((NI) 1);
		} LA5: ;
	}
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, handleShortOption__pureZparseopt_127)(tyObject_OptParser__l9cyoK9aLLTUH7LBRIbLqETg* p, NimStringDesc* cmd) {
	NI i;
	nimfr_("handleShortOption", "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
	nimln_(285, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
	i = (*p).pos;
	nimln_(286, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
	(*p).kind = ((tyEnum_CmdLineKind__XkdXq9atxjiuhkFFh0XYrSA) 3);
	nimln_(287, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
	{
		NI TM__GYgvYKeHVTEls0AcywABHQ_11;
		if (!(i < (cmd ? cmd->Sup.len : 0))) goto LA3_;
		nimln_(288, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
		if (i < 0 || i >= (cmd ? cmd->Sup.len : 0)){ raiseIndexError2(i,(cmd ? cmd->Sup.len : 0)-1); }
		unsureAsgnRef((void**) (&(*p).key), addChar((*p).key, cmd->data[i]));
		nimln_(289, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
		if (nimAddInt(i, ((NI) 1), &TM__GYgvYKeHVTEls0AcywABHQ_11)) { raiseOverflow(); };
		i = (NI)(TM__GYgvYKeHVTEls0AcywABHQ_11);
	}
	LA3_: ;
	nimln_(290, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
	(*p).inShortState = NIM_TRUE;
	{
		nimln_(291, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
		while (1) {
			NIM_BOOL T7_;
			NI TM__GYgvYKeHVTEls0AcywABHQ_12;
			T7_ = (NIM_BOOL)0;
			T7_ = (i < (cmd ? cmd->Sup.len : 0));
			if (!(T7_)) goto LA8_;
			if (i < 0 || i >= (cmd ? cmd->Sup.len : 0)){ raiseIndexError2(i,(cmd ? cmd->Sup.len : 0)-1); }
			T7_ = (((NU8)(cmd->data[i])) == ((NU8)(9)) || ((NU8)(cmd->data[i])) == ((NU8)(32)));
			LA8_: ;
			if (!T7_) goto LA6;
			nimln_(292, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
			if (nimAddInt(i, ((NI) 1), &TM__GYgvYKeHVTEls0AcywABHQ_12)) { raiseOverflow(); };
			i = (NI)(TM__GYgvYKeHVTEls0AcywABHQ_12);
			nimln_(293, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
			(*p).inShortState = NIM_FALSE;
		} LA6: ;
	}
	nimln_(294, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
	{
		NIM_BOOL T11_;
		NIM_BOOL T13_;
		NIM_BOOL T15_;
		NI TM__GYgvYKeHVTEls0AcywABHQ_15;
		T11_ = (NIM_BOOL)0;
		T11_ = (i < (cmd ? cmd->Sup.len : 0));
		if (!(T11_)) goto LA12_;
		T13_ = (NIM_BOOL)0;
		if (i < 0 || i >= (cmd ? cmd->Sup.len : 0)){ raiseIndexError2(i,(cmd ? cmd->Sup.len : 0)-1); }
		T13_ = (((NU8)(cmd->data[i])) == ((NU8)(58)) || ((NU8)(cmd->data[i])) == ((NU8)(61)));
		if (T13_) goto LA14_;
		nimln_(295, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
		T15_ = (NIM_BOOL)0;
		T15_ = (((NI) 0) < cardSet((*p).shortNoVal, 32));
		if (!(T15_)) goto LA16_;
		if (((NI) 0) < 0 || ((NI) 0) >= ((*p).key ? (*p).key->Sup.len : 0)){ raiseIndexError2(((NI) 0),((*p).key ? (*p).key->Sup.len : 0)-1); }
		T15_ = !((((*p).shortNoVal[(NU)(((NU8)((*p).key->data[((NI) 0)])))>>3] &(1U<<((NU)(((NU8)((*p).key->data[((NI) 0)])))&7U)))!=0));
		LA16_: ;
		T13_ = T15_;
		LA14_: ;
		T11_ = T13_;
		LA12_: ;
		if (!T11_) goto LA17_;
		nimln_(296, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
		{
			NIM_BOOL T21_;
			NI TM__GYgvYKeHVTEls0AcywABHQ_13;
			T21_ = (NIM_BOOL)0;
			T21_ = (i < (cmd ? cmd->Sup.len : 0));
			if (!(T21_)) goto LA22_;
			if (i < 0 || i >= (cmd ? cmd->Sup.len : 0)){ raiseIndexError2(i,(cmd ? cmd->Sup.len : 0)-1); }
			T21_ = (((NU8)(cmd->data[i])) == ((NU8)(58)) || ((NU8)(cmd->data[i])) == ((NU8)(61)));
			LA22_: ;
			if (!T21_) goto LA23_;
			nimln_(297, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
			if (nimAddInt(i, ((NI) 1), &TM__GYgvYKeHVTEls0AcywABHQ_13)) { raiseOverflow(); };
			i = (NI)(TM__GYgvYKeHVTEls0AcywABHQ_13);
		}
		LA23_: ;
		nimln_(298, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
		(*p).inShortState = NIM_FALSE;
		{
			nimln_(299, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
			while (1) {
				NIM_BOOL T27_;
				NI TM__GYgvYKeHVTEls0AcywABHQ_14;
				T27_ = (NIM_BOOL)0;
				T27_ = (i < (cmd ? cmd->Sup.len : 0));
				if (!(T27_)) goto LA28_;
				if (i < 0 || i >= (cmd ? cmd->Sup.len : 0)){ raiseIndexError2(i,(cmd ? cmd->Sup.len : 0)-1); }
				T27_ = (((NU8)(cmd->data[i])) == ((NU8)(9)) || ((NU8)(cmd->data[i])) == ((NU8)(32)));
				LA28_: ;
				if (!T27_) goto LA26;
				if (nimAddInt(i, ((NI) 1), &TM__GYgvYKeHVTEls0AcywABHQ_14)) { raiseOverflow(); };
				i = (NI)(TM__GYgvYKeHVTEls0AcywABHQ_14);
			} LA26: ;
		}
		nimln_(300, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
		unsureAsgnRef((void**) (&(*p).val), substr__system_7857(cmd, i));
		nimln_(301, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
		(*p).pos = ((NI) 0);
		nimln_(302, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
		if (nimAddInt((*p).idx, ((NI) 1), &TM__GYgvYKeHVTEls0AcywABHQ_15)) { raiseOverflow(); };
		(*p).idx = (NI)(TM__GYgvYKeHVTEls0AcywABHQ_15);
	}
	goto LA9_;
	LA17_: ;
	{
		nimln_(304, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
		(*p).pos = i;
	}
	LA9_: ;
	nimln_(305, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
	{
		NI TM__GYgvYKeHVTEls0AcywABHQ_16;
		if (!((cmd ? cmd->Sup.len : 0) <= i)) goto LA32_;
		nimln_(306, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
		(*p).inShortState = NIM_FALSE;
		nimln_(307, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
		(*p).pos = ((NI) 0);
		nimln_(308, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
		if (nimAddInt((*p).idx, ((NI) 1), &TM__GYgvYKeHVTEls0AcywABHQ_16)) { raiseOverflow(); };
		(*p).idx = (NI)(TM__GYgvYKeHVTEls0AcywABHQ_16);
	}
	LA32_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(NI, parseWord__pureZparseopt_25)(NimStringDesc* s, NI i, NimStringDesc** w, tySet_tyChar__nmiMWKVIe46vacnhAFrQvw delim) {
	NI result;
	nimfr_("parseWord", "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
	result = (NI)0;
	nimln_(181, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
	result = i;
	nimln_(182, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
	{
		NIM_BOOL T3_;
		NI TM__GYgvYKeHVTEls0AcywABHQ_19;
		T3_ = (NIM_BOOL)0;
		T3_ = (result < (s ? s->Sup.len : 0));
		if (!(T3_)) goto LA4_;
		if (result < 0 || result >= (s ? s->Sup.len : 0)){ raiseIndexError2(result,(s ? s->Sup.len : 0)-1); }
		T3_ = ((NU8)(s->data[result]) == (NU8)(34));
		LA4_: ;
		if (!T3_) goto LA5_;
		nimln_(183, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
		if (nimAddInt(result, ((NI) 1), &TM__GYgvYKeHVTEls0AcywABHQ_19)) { raiseOverflow(); };
		result = (NI)(TM__GYgvYKeHVTEls0AcywABHQ_19);
		{
			nimln_(184, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
			while (1) {
				NI TM__GYgvYKeHVTEls0AcywABHQ_21;
				if (!(result < (s ? s->Sup.len : 0))) goto LA8;
				nimln_(185, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
				{
					NI TM__GYgvYKeHVTEls0AcywABHQ_20;
					if (result < 0 || result >= (s ? s->Sup.len : 0)){ raiseIndexError2(result,(s ? s->Sup.len : 0)-1); }
					if (!((NU8)(s->data[result]) == (NU8)(34))) goto LA11_;
					nimln_(186, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
					if (nimAddInt(result, ((NI) 1), &TM__GYgvYKeHVTEls0AcywABHQ_20)) { raiseOverflow(); };
					result = (NI)(TM__GYgvYKeHVTEls0AcywABHQ_20);
					nimln_(187, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
					goto LA7;
				}
				LA11_: ;
				nimln_(188, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
				if (result < 0 || result >= (s ? s->Sup.len : 0)){ raiseIndexError2(result,(s ? s->Sup.len : 0)-1); }
				unsureAsgnRef((void**) (&(*w)), addChar((*w), s->data[result]));
				nimln_(189, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
				if (nimAddInt(result, ((NI) 1), &TM__GYgvYKeHVTEls0AcywABHQ_21)) { raiseOverflow(); };
				result = (NI)(TM__GYgvYKeHVTEls0AcywABHQ_21);
			} LA8: ;
		} LA7: ;
	}
	goto LA1_;
	LA5_: ;
	{
		{
			nimln_(191, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
			while (1) {
				NIM_BOOL T16_;
				NI TM__GYgvYKeHVTEls0AcywABHQ_22;
				T16_ = (NIM_BOOL)0;
				T16_ = (result < (s ? s->Sup.len : 0));
				if (!(T16_)) goto LA17_;
				if (result < 0 || result >= (s ? s->Sup.len : 0)){ raiseIndexError2(result,(s ? s->Sup.len : 0)-1); }
				T16_ = !(((delim[(NU)(((NU8)(s->data[result])))>>3] &(1U<<((NU)(((NU8)(s->data[result])))&7U)))!=0));
				LA17_: ;
				if (!T16_) goto LA15;
				nimln_(192, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
				if (result < 0 || result >= (s ? s->Sup.len : 0)){ raiseIndexError2(result,(s ? s->Sup.len : 0)-1); }
				unsureAsgnRef((void**) (&(*w)), addChar((*w), s->data[result]));
				nimln_(193, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
				if (nimAddInt(result, ((NI) 1), &TM__GYgvYKeHVTEls0AcywABHQ_22)) { raiseOverflow(); };
				result = (NI)(TM__GYgvYKeHVTEls0AcywABHQ_22);
			} LA15: ;
		}
	}
	LA1_: ;
	popFrame();
	return result;
}
static N_INLINE(int, nimCmpMem)(void* a, void* b, NI size) {
	int result;
	result = (int)0;
	result = memcmp(a, b, ((size_t) (size)));
	return result;
}
static N_INLINE(NIM_BOOL, equalMem__system_1735)(void* a, void* b, NI size) {
	NIM_BOOL result;
	int T1_;
	result = (NIM_BOOL)0;
	T1_ = (int)0;
	T1_ = nimCmpMem(a, b, size);
	result = (T1_ == ((NI32) 0));
	return result;
}
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NI alen;
	NI blen;
	nimfr_("eqStrings", "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/strmantle.nim");
{	result = (NIM_BOOL)0;
	nimln_(27, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/strmantle.nim");
	alen = (a ? a->Sup.len : 0);
	nimln_(28, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/strmantle.nim");
	blen = (b ? b->Sup.len : 0);
	nimln_(29, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/strmantle.nim");
	{
		if (!(alen == blen)) goto LA3_;
		nimln_(30, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/strmantle.nim");
		{
			if (!(alen == ((NI) 0))) goto LA7_;
			result = NIM_TRUE;
			goto BeforeRet_;
		}
		LA7_: ;
		nimln_(31, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/strmantle.nim");
		result = equalMem__system_1735(((void*) ((&a->data[((NI) 0)]))), ((void*) ((&b->data[((NI) 0)]))), ((NI) (alen)));
		goto BeforeRet_;
	}
	LA3_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NI, find__stdZenumutils_48)(NimStringDesc** a, NI aLen_0, NimStringDesc* item) {
	NI result;
	nimfr_("find", "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system.nim");
{	result = (NI)0;
	nimln_(1837, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system.nim");
	result = ((NI) 0);
	{
		NimStringDesc** i;
		NI i_2;
		i = (NimStringDesc**)0;
		nimln_(8, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/iterators.nim");
		i_2 = ((NI) 0);
		{
			nimln_(9, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/iterators.nim");
			while (1) {
				NI TM__GYgvYKeHVTEls0AcywABHQ_28;
				NI TM__GYgvYKeHVTEls0AcywABHQ_29;
				if (!(i_2 < aLen_0)) goto LA3;
				nimln_(1838, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system.nim");
				if (i_2 < 0 || i_2 >= aLen_0){ raiseIndexError2(i_2,aLen_0-1); }
				i = (&a[i_2]);
				{
					nimln_(1839, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system.nim");
					if (!eqStrings((*i), item)) goto LA6_;
					goto BeforeRet_;
				}
				LA6_: ;
				nimln_(1838, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system.nim");
				if (nimAddInt(result, ((NI) 1), &TM__GYgvYKeHVTEls0AcywABHQ_28)) { raiseOverflow(); };
				result = (NI)(TM__GYgvYKeHVTEls0AcywABHQ_28);
				nimln_(11, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/iterators.nim");
				if (nimAddInt(i_2, ((NI) 1), &TM__GYgvYKeHVTEls0AcywABHQ_29)) { raiseOverflow(); };
				i_2 = (NI)(TM__GYgvYKeHVTEls0AcywABHQ_29);
			} LA3: ;
		}
	}
	nimln_(1841, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system.nim");
	result = ((NI) -1);
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, contains__stdZenumutils_43)(NimStringDesc** a, NI aLen_0, NimStringDesc* item) {
	NIM_BOOL result;
	NI T1_;
	nimfr_("contains", "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system.nim");
{	result = (NIM_BOOL)0;
	nimln_(1855, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system.nim");
	T1_ = (NI)0;
	T1_ = find__stdZenumutils_48(a, aLen_0, item);
	result = (((NI) 0) <= T1_);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, nponext)(tyObject_OptParser__l9cyoK9aLLTUH7LBRIbLqETg* p) {
	NI i;
	nimfr_("next", "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
{	nimln_(326, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
	{
		NI T3_;
		T3_ = ((*p).cmds ? (*p).cmds->Sup.len : 0);
		if (!(T3_ <= (*p).idx)) goto LA4_;
		nimln_(327, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
		(*p).kind = ((tyEnum_CmdLineKind__XkdXq9atxjiuhkFFh0XYrSA) 0);
		nimln_(328, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
		goto BeforeRet_;
	}
	LA4_: ;
	nimln_(330, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
	i = (*p).pos;
	{
		nimln_(331, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
		while (1) {
			NIM_BOOL T8_;
			NI TM__GYgvYKeHVTEls0AcywABHQ_9;
			T8_ = (NIM_BOOL)0;
			if ((*p).idx < 0 || (*p).idx >= ((*p).cmds ? (*p).cmds->Sup.len : 0)){ raiseIndexError2((*p).idx,((*p).cmds ? (*p).cmds->Sup.len : 0)-1); }
			T8_ = (i < ((*p).cmds->data[(*p).idx] ? (*p).cmds->data[(*p).idx]->Sup.len : 0));
			if (!(T8_)) goto LA9_;
			if ((*p).idx < 0 || (*p).idx >= ((*p).cmds ? (*p).cmds->Sup.len : 0)){ raiseIndexError2((*p).idx,((*p).cmds ? (*p).cmds->Sup.len : 0)-1); }
			if (i < 0 || i >= ((*p).cmds->data[(*p).idx] ? (*p).cmds->data[(*p).idx]->Sup.len : 0)){ raiseIndexError2(i,((*p).cmds->data[(*p).idx] ? (*p).cmds->data[(*p).idx]->Sup.len : 0)-1); }
			T8_ = (((NU8)((*p).cmds->data[(*p).idx]->data[i])) == ((NU8)(9)) || ((NU8)((*p).cmds->data[(*p).idx]->data[i])) == ((NU8)(32)));
			LA9_: ;
			if (!T8_) goto LA7;
			if (nimAddInt(i, ((NI) 1), &TM__GYgvYKeHVTEls0AcywABHQ_9)) { raiseOverflow(); };
			i = (NI)(TM__GYgvYKeHVTEls0AcywABHQ_9);
		} LA7: ;
	}
	nimln_(332, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
	(*p).pos = i;
	nimln_(333, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
	unsureAsgnRef((void**) (&(*p).key), setLengthStr((*p).key, ((NI) 0)));
	nimln_(334, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
	unsureAsgnRef((void**) (&(*p).val), setLengthStr((*p).val, ((NI) 0)));
	nimln_(335, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
	{
		if (!(*p).inShortState) goto LA12_;
		nimln_(336, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
		(*p).inShortState = NIM_FALSE;
		nimln_(337, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
		{
			NI TM__GYgvYKeHVTEls0AcywABHQ_10;
			if ((*p).idx < 0 || (*p).idx >= ((*p).cmds ? (*p).cmds->Sup.len : 0)){ raiseIndexError2((*p).idx,((*p).cmds ? (*p).cmds->Sup.len : 0)-1); }
			if (!(((*p).cmds->data[(*p).idx] ? (*p).cmds->data[(*p).idx]->Sup.len : 0) <= i)) goto LA16_;
			nimln_(338, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
			if (nimAddInt((*p).idx, ((NI) 1), &TM__GYgvYKeHVTEls0AcywABHQ_10)) { raiseOverflow(); };
			(*p).idx = (NI)(TM__GYgvYKeHVTEls0AcywABHQ_10);
			nimln_(339, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
			(*p).pos = ((NI) 0);
			nimln_(340, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
			{
				NI T20_;
				T20_ = ((*p).cmds ? (*p).cmds->Sup.len : 0);
				if (!(T20_ <= (*p).idx)) goto LA21_;
				nimln_(341, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
				(*p).kind = ((tyEnum_CmdLineKind__XkdXq9atxjiuhkFFh0XYrSA) 0);
				nimln_(342, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
				goto BeforeRet_;
			}
			LA21_: ;
		}
		goto LA14_;
		LA16_: ;
		{
			nimln_(344, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
			if ((*p).idx < 0 || (*p).idx >= ((*p).cmds ? (*p).cmds->Sup.len : 0)){ raiseIndexError2((*p).idx,((*p).cmds ? (*p).cmds->Sup.len : 0)-1); }
			handleShortOption__pureZparseopt_127(p, (*p).cmds->data[(*p).idx]);
			nimln_(345, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
			goto BeforeRet_;
		}
		LA14_: ;
	}
	LA12_: ;
	nimln_(347, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
	{
		NIM_BOOL T26_;
		NI TM__GYgvYKeHVTEls0AcywABHQ_17;
		T26_ = (NIM_BOOL)0;
		if ((*p).idx < 0 || (*p).idx >= ((*p).cmds ? (*p).cmds->Sup.len : 0)){ raiseIndexError2((*p).idx,((*p).cmds ? (*p).cmds->Sup.len : 0)-1); }
		T26_ = (i < ((*p).cmds->data[(*p).idx] ? (*p).cmds->data[(*p).idx]->Sup.len : 0));
		if (!(T26_)) goto LA27_;
		if ((*p).idx < 0 || (*p).idx >= ((*p).cmds ? (*p).cmds->Sup.len : 0)){ raiseIndexError2((*p).idx,((*p).cmds ? (*p).cmds->Sup.len : 0)-1); }
		if (i < 0 || i >= ((*p).cmds->data[(*p).idx] ? (*p).cmds->data[(*p).idx]->Sup.len : 0)){ raiseIndexError2(i,((*p).cmds->data[(*p).idx] ? (*p).cmds->data[(*p).idx]->Sup.len : 0)-1); }
		T26_ = ((NU8)((*p).cmds->data[(*p).idx]->data[i]) == (NU8)(45));
		LA27_: ;
		if (!T26_) goto LA28_;
		nimln_(348, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
		if (nimAddInt(i, ((NI) 1), &TM__GYgvYKeHVTEls0AcywABHQ_17)) { raiseOverflow(); };
		i = (NI)(TM__GYgvYKeHVTEls0AcywABHQ_17);
		nimln_(349, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
		{
			NIM_BOOL T32_;
			NI TM__GYgvYKeHVTEls0AcywABHQ_18;
			NI TM__GYgvYKeHVTEls0AcywABHQ_33;
			T32_ = (NIM_BOOL)0;
			if ((*p).idx < 0 || (*p).idx >= ((*p).cmds ? (*p).cmds->Sup.len : 0)){ raiseIndexError2((*p).idx,((*p).cmds ? (*p).cmds->Sup.len : 0)-1); }
			T32_ = (i < ((*p).cmds->data[(*p).idx] ? (*p).cmds->data[(*p).idx]->Sup.len : 0));
			if (!(T32_)) goto LA33_;
			if ((*p).idx < 0 || (*p).idx >= ((*p).cmds ? (*p).cmds->Sup.len : 0)){ raiseIndexError2((*p).idx,((*p).cmds ? (*p).cmds->Sup.len : 0)-1); }
			if (i < 0 || i >= ((*p).cmds->data[(*p).idx] ? (*p).cmds->data[(*p).idx]->Sup.len : 0)){ raiseIndexError2(i,((*p).cmds->data[(*p).idx] ? (*p).cmds->data[(*p).idx]->Sup.len : 0)-1); }
			T32_ = ((NU8)((*p).cmds->data[(*p).idx]->data[i]) == (NU8)(45));
			LA33_: ;
			if (!T32_) goto LA34_;
			nimln_(350, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
			(*p).kind = ((tyEnum_CmdLineKind__XkdXq9atxjiuhkFFh0XYrSA) 2);
			nimln_(351, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
			if (nimAddInt(i, ((NI) 1), &TM__GYgvYKeHVTEls0AcywABHQ_18)) { raiseOverflow(); };
			i = (NI)(TM__GYgvYKeHVTEls0AcywABHQ_18);
			nimln_(352, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
			if ((*p).idx < 0 || (*p).idx >= ((*p).cmds ? (*p).cmds->Sup.len : 0)){ raiseIndexError2((*p).idx,((*p).cmds ? (*p).cmds->Sup.len : 0)-1); }
			i = parseWord__pureZparseopt_25((*p).cmds->data[(*p).idx], i, (&(*p).key), TM__GYgvYKeHVTEls0AcywABHQ_23);
			{
				nimln_(353, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
				while (1) {
					NIM_BOOL T38_;
					NI TM__GYgvYKeHVTEls0AcywABHQ_24;
					T38_ = (NIM_BOOL)0;
					if ((*p).idx < 0 || (*p).idx >= ((*p).cmds ? (*p).cmds->Sup.len : 0)){ raiseIndexError2((*p).idx,((*p).cmds ? (*p).cmds->Sup.len : 0)-1); }
					T38_ = (i < ((*p).cmds->data[(*p).idx] ? (*p).cmds->data[(*p).idx]->Sup.len : 0));
					if (!(T38_)) goto LA39_;
					if ((*p).idx < 0 || (*p).idx >= ((*p).cmds ? (*p).cmds->Sup.len : 0)){ raiseIndexError2((*p).idx,((*p).cmds ? (*p).cmds->Sup.len : 0)-1); }
					if (i < 0 || i >= ((*p).cmds->data[(*p).idx] ? (*p).cmds->data[(*p).idx]->Sup.len : 0)){ raiseIndexError2(i,((*p).cmds->data[(*p).idx] ? (*p).cmds->data[(*p).idx]->Sup.len : 0)-1); }
					T38_ = (((NU8)((*p).cmds->data[(*p).idx]->data[i])) == ((NU8)(9)) || ((NU8)((*p).cmds->data[(*p).idx]->data[i])) == ((NU8)(32)));
					LA39_: ;
					if (!T38_) goto LA37;
					if (nimAddInt(i, ((NI) 1), &TM__GYgvYKeHVTEls0AcywABHQ_24)) { raiseOverflow(); };
					i = (NI)(TM__GYgvYKeHVTEls0AcywABHQ_24);
				} LA37: ;
			}
			nimln_(354, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
			{
				NIM_BOOL T42_;
				NI TM__GYgvYKeHVTEls0AcywABHQ_25;
				T42_ = (NIM_BOOL)0;
				if ((*p).idx < 0 || (*p).idx >= ((*p).cmds ? (*p).cmds->Sup.len : 0)){ raiseIndexError2((*p).idx,((*p).cmds ? (*p).cmds->Sup.len : 0)-1); }
				T42_ = (i < ((*p).cmds->data[(*p).idx] ? (*p).cmds->data[(*p).idx]->Sup.len : 0));
				if (!(T42_)) goto LA43_;
				if ((*p).idx < 0 || (*p).idx >= ((*p).cmds ? (*p).cmds->Sup.len : 0)){ raiseIndexError2((*p).idx,((*p).cmds ? (*p).cmds->Sup.len : 0)-1); }
				if (i < 0 || i >= ((*p).cmds->data[(*p).idx] ? (*p).cmds->data[(*p).idx]->Sup.len : 0)){ raiseIndexError2(i,((*p).cmds->data[(*p).idx] ? (*p).cmds->data[(*p).idx]->Sup.len : 0)-1); }
				T42_ = (((NU8)((*p).cmds->data[(*p).idx]->data[i])) == ((NU8)(58)) || ((NU8)((*p).cmds->data[(*p).idx]->data[i])) == ((NU8)(61)));
				LA43_: ;
				if (!T42_) goto LA44_;
				nimln_(355, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
				if (nimAddInt(i, ((NI) 1), &TM__GYgvYKeHVTEls0AcywABHQ_25)) { raiseOverflow(); };
				i = (NI)(TM__GYgvYKeHVTEls0AcywABHQ_25);
				{
					nimln_(356, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
					while (1) {
						NIM_BOOL T48_;
						NI TM__GYgvYKeHVTEls0AcywABHQ_26;
						T48_ = (NIM_BOOL)0;
						if ((*p).idx < 0 || (*p).idx >= ((*p).cmds ? (*p).cmds->Sup.len : 0)){ raiseIndexError2((*p).idx,((*p).cmds ? (*p).cmds->Sup.len : 0)-1); }
						T48_ = (i < ((*p).cmds->data[(*p).idx] ? (*p).cmds->data[(*p).idx]->Sup.len : 0));
						if (!(T48_)) goto LA49_;
						if ((*p).idx < 0 || (*p).idx >= ((*p).cmds ? (*p).cmds->Sup.len : 0)){ raiseIndexError2((*p).idx,((*p).cmds ? (*p).cmds->Sup.len : 0)-1); }
						if (i < 0 || i >= ((*p).cmds->data[(*p).idx] ? (*p).cmds->data[(*p).idx]->Sup.len : 0)){ raiseIndexError2(i,((*p).cmds->data[(*p).idx] ? (*p).cmds->data[(*p).idx]->Sup.len : 0)-1); }
						T48_ = (((NU8)((*p).cmds->data[(*p).idx]->data[i])) == ((NU8)(9)) || ((NU8)((*p).cmds->data[(*p).idx]->data[i])) == ((NU8)(32)));
						LA49_: ;
						if (!T48_) goto LA47;
						if (nimAddInt(i, ((NI) 1), &TM__GYgvYKeHVTEls0AcywABHQ_26)) { raiseOverflow(); };
						i = (NI)(TM__GYgvYKeHVTEls0AcywABHQ_26);
					} LA47: ;
				}
				nimln_(358, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
				{
					NIM_BOOL T52_;
					NIM_BOOL T53_;
					NI T55_;
					NI TM__GYgvYKeHVTEls0AcywABHQ_27;
					T52_ = (NIM_BOOL)0;
					T53_ = (NIM_BOOL)0;
					if ((*p).idx < 0 || (*p).idx >= ((*p).cmds ? (*p).cmds->Sup.len : 0)){ raiseIndexError2((*p).idx,((*p).cmds ? (*p).cmds->Sup.len : 0)-1); }
					T53_ = (((*p).cmds->data[(*p).idx] ? (*p).cmds->data[(*p).idx]->Sup.len : 0) <= i);
					if (!(T53_)) goto LA54_;
					T55_ = ((*p).cmds ? (*p).cmds->Sup.len : 0);
					T53_ = ((*p).idx < T55_);
					LA54_: ;
					T52_ = T53_;
					if (!(T52_)) goto LA56_;
					T52_ = (*p).allowWhitespaceAfterColon;
					LA56_: ;
					if (!T52_) goto LA57_;
					nimln_(360, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
					if (nimAddInt((*p).idx, ((NI) 1), &TM__GYgvYKeHVTEls0AcywABHQ_27)) { raiseOverflow(); };
					(*p).idx = (NI)(TM__GYgvYKeHVTEls0AcywABHQ_27);
					nimln_(361, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
					i = ((NI) 0);
				}
				LA57_: ;
				nimln_(362, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
				{
					NI T61_;
					T61_ = ((*p).cmds ? (*p).cmds->Sup.len : 0);
					if (!((*p).idx < T61_)) goto LA62_;
					nimln_(363, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
					if ((*p).idx < 0 || (*p).idx >= ((*p).cmds ? (*p).cmds->Sup.len : 0)){ raiseIndexError2((*p).idx,((*p).cmds ? (*p).cmds->Sup.len : 0)-1); }
					unsureAsgnRef((void**) (&(*p).val), substr__system_7857((*p).cmds->data[(*p).idx], i));
				}
				LA62_: ;
			}
			goto LA40_;
			LA44_: ;
			{
				NIM_BOOL T65_;
				NIM_BOOL T66_;
				NI T67_;
				NIM_BOOL T69_;
				NI TM__GYgvYKeHVTEls0AcywABHQ_30;
				NI T71_;
				NI TM__GYgvYKeHVTEls0AcywABHQ_31;
				NI TM__GYgvYKeHVTEls0AcywABHQ_32;
				nimln_(364, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
				T65_ = (NIM_BOOL)0;
				T66_ = (NIM_BOOL)0;
				T67_ = ((*p).longNoVal ? (*p).longNoVal->Sup.len : 0);
				T66_ = (((NI) 0) < T67_);
				if (!(T66_)) goto LA68_;
				T69_ = (NIM_BOOL)0;
				T69_ = contains__stdZenumutils_43(((*p).longNoVal) ? ((*p).longNoVal->data) : NIM_NIL, ((*p).longNoVal ? (*p).longNoVal->Sup.len : 0), (*p).key);
				T66_ = !(T69_);
				LA68_: ;
				T65_ = T66_;
				if (!(T65_)) goto LA70_;
				if (nimAddInt((*p).idx, ((NI) 1), &TM__GYgvYKeHVTEls0AcywABHQ_30)) { raiseOverflow(); };
				T71_ = ((*p).cmds ? (*p).cmds->Sup.len : 0);
				T65_ = ((NI)(TM__GYgvYKeHVTEls0AcywABHQ_30) < T71_);
				LA70_: ;
				if (!T65_) goto LA72_;
				nimln_(365, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
				if (nimAddInt((*p).idx, ((NI) 1), &TM__GYgvYKeHVTEls0AcywABHQ_31)) { raiseOverflow(); };
				if ((NI)(TM__GYgvYKeHVTEls0AcywABHQ_31) < 0 || (NI)(TM__GYgvYKeHVTEls0AcywABHQ_31) >= ((*p).cmds ? (*p).cmds->Sup.len : 0)){ raiseIndexError2((NI)(TM__GYgvYKeHVTEls0AcywABHQ_31),((*p).cmds ? (*p).cmds->Sup.len : 0)-1); }
				unsureAsgnRef((void**) (&(*p).val), copyString((*p).cmds->data[(NI)(TM__GYgvYKeHVTEls0AcywABHQ_31)]));
				nimln_(366, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
				if (nimAddInt((*p).idx, ((NI) 1), &TM__GYgvYKeHVTEls0AcywABHQ_32)) { raiseOverflow(); };
				(*p).idx = (NI)(TM__GYgvYKeHVTEls0AcywABHQ_32);
			}
			goto LA40_;
			LA72_: ;
			{
				nimln_(368, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
				unsureAsgnRef((void**) (&(*p).val), ((NimStringDesc*) NIM_NIL));
			}
			LA40_: ;
			nimln_(369, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
			if (nimAddInt((*p).idx, ((NI) 1), &TM__GYgvYKeHVTEls0AcywABHQ_33)) { raiseOverflow(); };
			(*p).idx = (NI)(TM__GYgvYKeHVTEls0AcywABHQ_33);
			nimln_(370, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
			(*p).pos = ((NI) 0);
		}
		goto LA30_;
		LA34_: ;
		{
			nimln_(372, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
			(*p).pos = i;
			nimln_(373, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
			if ((*p).idx < 0 || (*p).idx >= ((*p).cmds ? (*p).cmds->Sup.len : 0)){ raiseIndexError2((*p).idx,((*p).cmds ? (*p).cmds->Sup.len : 0)-1); }
			handleShortOption__pureZparseopt_127(p, (*p).cmds->data[(*p).idx]);
		}
		LA30_: ;
	}
	goto LA24_;
	LA28_: ;
	{
		NI TM__GYgvYKeHVTEls0AcywABHQ_34;
		nimln_(375, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
		(*p).kind = ((tyEnum_CmdLineKind__XkdXq9atxjiuhkFFh0XYrSA) 1);
		nimln_(376, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
		if ((*p).idx < 0 || (*p).idx >= ((*p).cmds ? (*p).cmds->Sup.len : 0)){ raiseIndexError2((*p).idx,((*p).cmds ? (*p).cmds->Sup.len : 0)-1); }
		unsureAsgnRef((void**) (&(*p).key), copyString((*p).cmds->data[(*p).idx]));
		nimln_(377, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
		if (nimAddInt((*p).idx, ((NI) 1), &TM__GYgvYKeHVTEls0AcywABHQ_34)) { raiseOverflow(); };
		(*p).idx = (NI)(TM__GYgvYKeHVTEls0AcywABHQ_34);
		nimln_(378, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/pure/parseopt.nim");
		(*p).pos = ((NI) 0);
	}
	LA24_: ;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotdotatsdotdotatsdotchoosenimatstoolchainsatsnimminusathversionminus1minus6atslibatspureatsparseoptdotnim_DatInit000)(void) {
static TNimNode* TM__GYgvYKeHVTEls0AcywABHQ_2_4[4];
NI TM__GYgvYKeHVTEls0AcywABHQ_4;
static char* NIM_CONST TM__GYgvYKeHVTEls0AcywABHQ_3[4] = {
"cmdEnd", 
"cmdArgument", 
"cmdLongOption", 
"cmdShortOption"};
static TNimNode* TM__GYgvYKeHVTEls0AcywABHQ_5_10[10];
static TNimNode TM__GYgvYKeHVTEls0AcywABHQ_0[17];
NTIcmdlinekind__XkdXq9atxjiuhkFFh0XYrSA_.size = sizeof(tyEnum_CmdLineKind__XkdXq9atxjiuhkFFh0XYrSA);
NTIcmdlinekind__XkdXq9atxjiuhkFFh0XYrSA_.align = NIM_ALIGNOF(tyEnum_CmdLineKind__XkdXq9atxjiuhkFFh0XYrSA);
NTIcmdlinekind__XkdXq9atxjiuhkFFh0XYrSA_.kind = 14;
NTIcmdlinekind__XkdXq9atxjiuhkFFh0XYrSA_.base = 0;
NTIcmdlinekind__XkdXq9atxjiuhkFFh0XYrSA_.flags = 3;
for (TM__GYgvYKeHVTEls0AcywABHQ_4 = 0; TM__GYgvYKeHVTEls0AcywABHQ_4 < 4; TM__GYgvYKeHVTEls0AcywABHQ_4++) {
TM__GYgvYKeHVTEls0AcywABHQ_0[TM__GYgvYKeHVTEls0AcywABHQ_4+0].kind = 1;
TM__GYgvYKeHVTEls0AcywABHQ_0[TM__GYgvYKeHVTEls0AcywABHQ_4+0].offset = TM__GYgvYKeHVTEls0AcywABHQ_4;
TM__GYgvYKeHVTEls0AcywABHQ_0[TM__GYgvYKeHVTEls0AcywABHQ_4+0].name = TM__GYgvYKeHVTEls0AcywABHQ_3[TM__GYgvYKeHVTEls0AcywABHQ_4];
TM__GYgvYKeHVTEls0AcywABHQ_2_4[TM__GYgvYKeHVTEls0AcywABHQ_4] = &TM__GYgvYKeHVTEls0AcywABHQ_0[TM__GYgvYKeHVTEls0AcywABHQ_4+0];
}
TM__GYgvYKeHVTEls0AcywABHQ_0[4].len = 4; TM__GYgvYKeHVTEls0AcywABHQ_0[4].kind = 2; TM__GYgvYKeHVTEls0AcywABHQ_0[4].sons = &TM__GYgvYKeHVTEls0AcywABHQ_2_4[0];
NTIcmdlinekind__XkdXq9atxjiuhkFFh0XYrSA_.node = &TM__GYgvYKeHVTEls0AcywABHQ_0[4];
NTIoptparser__l9cyoK9aLLTUH7LBRIbLqETg_.size = sizeof(tyObject_OptParser__l9cyoK9aLLTUH7LBRIbLqETg);
NTIoptparser__l9cyoK9aLLTUH7LBRIbLqETg_.align = NIM_ALIGNOF(tyObject_OptParser__l9cyoK9aLLTUH7LBRIbLqETg);
NTIoptparser__l9cyoK9aLLTUH7LBRIbLqETg_.kind = 17;
NTIoptparser__l9cyoK9aLLTUH7LBRIbLqETg_.base = (&NTIrootobj__ytyiCJqK439aF9cIibuRVpAg_);
TM__GYgvYKeHVTEls0AcywABHQ_5_10[0] = &TM__GYgvYKeHVTEls0AcywABHQ_0[6];
TM__GYgvYKeHVTEls0AcywABHQ_0[6].kind = 1;
TM__GYgvYKeHVTEls0AcywABHQ_0[6].offset = offsetof(tyObject_OptParser__l9cyoK9aLLTUH7LBRIbLqETg, pos);
TM__GYgvYKeHVTEls0AcywABHQ_0[6].typ = (&NTIint__rR5Bzr1D5krxoo1NcNyeMA_);
TM__GYgvYKeHVTEls0AcywABHQ_0[6].name = "pos";
TM__GYgvYKeHVTEls0AcywABHQ_5_10[1] = &TM__GYgvYKeHVTEls0AcywABHQ_0[7];
TM__GYgvYKeHVTEls0AcywABHQ_0[7].kind = 1;
TM__GYgvYKeHVTEls0AcywABHQ_0[7].offset = offsetof(tyObject_OptParser__l9cyoK9aLLTUH7LBRIbLqETg, inShortState);
TM__GYgvYKeHVTEls0AcywABHQ_0[7].typ = (&NTIbool__VaVACK0bpYmqIQ0mKcHfQQ_);
TM__GYgvYKeHVTEls0AcywABHQ_0[7].name = "inShortState";
TM__GYgvYKeHVTEls0AcywABHQ_5_10[2] = &TM__GYgvYKeHVTEls0AcywABHQ_0[8];
TM__GYgvYKeHVTEls0AcywABHQ_0[8].kind = 1;
TM__GYgvYKeHVTEls0AcywABHQ_0[8].offset = offsetof(tyObject_OptParser__l9cyoK9aLLTUH7LBRIbLqETg, allowWhitespaceAfterColon);
TM__GYgvYKeHVTEls0AcywABHQ_0[8].typ = (&NTIbool__VaVACK0bpYmqIQ0mKcHfQQ_);
TM__GYgvYKeHVTEls0AcywABHQ_0[8].name = "allowWhitespaceAfterColon";
TM__GYgvYKeHVTEls0AcywABHQ_5_10[3] = &TM__GYgvYKeHVTEls0AcywABHQ_0[9];
NTIsetLcharT__HDqWPvEAxZK51ZcfaeQEdg_.size = sizeof(tySet_tyChar__nmiMWKVIe46vacnhAFrQvw);
NTIsetLcharT__HDqWPvEAxZK51ZcfaeQEdg_.align = NIM_ALIGNOF(tySet_tyChar__nmiMWKVIe46vacnhAFrQvw);
NTIsetLcharT__HDqWPvEAxZK51ZcfaeQEdg_.kind = 19;
NTIsetLcharT__HDqWPvEAxZK51ZcfaeQEdg_.base = (&NTIchar__nmiMWKVIe46vacnhAFrQvw_);
NTIsetLcharT__HDqWPvEAxZK51ZcfaeQEdg_.flags = 3;
TM__GYgvYKeHVTEls0AcywABHQ_0[10].len = 0; TM__GYgvYKeHVTEls0AcywABHQ_0[10].kind = 0;
NTIsetLcharT__HDqWPvEAxZK51ZcfaeQEdg_.node = &TM__GYgvYKeHVTEls0AcywABHQ_0[10];
TM__GYgvYKeHVTEls0AcywABHQ_0[9].kind = 1;
TM__GYgvYKeHVTEls0AcywABHQ_0[9].offset = offsetof(tyObject_OptParser__l9cyoK9aLLTUH7LBRIbLqETg, shortNoVal);
TM__GYgvYKeHVTEls0AcywABHQ_0[9].typ = (&NTIsetLcharT__HDqWPvEAxZK51ZcfaeQEdg_);
TM__GYgvYKeHVTEls0AcywABHQ_0[9].name = "shortNoVal";
TM__GYgvYKeHVTEls0AcywABHQ_5_10[4] = &TM__GYgvYKeHVTEls0AcywABHQ_0[11];
TM__GYgvYKeHVTEls0AcywABHQ_0[11].kind = 1;
TM__GYgvYKeHVTEls0AcywABHQ_0[11].offset = offsetof(tyObject_OptParser__l9cyoK9aLLTUH7LBRIbLqETg, longNoVal);
TM__GYgvYKeHVTEls0AcywABHQ_0[11].typ = (&NTIseqLstringT__sM4lkSb7zS6F7OVMvW9cffQ_);
TM__GYgvYKeHVTEls0AcywABHQ_0[11].name = "longNoVal";
TM__GYgvYKeHVTEls0AcywABHQ_5_10[5] = &TM__GYgvYKeHVTEls0AcywABHQ_0[12];
TM__GYgvYKeHVTEls0AcywABHQ_0[12].kind = 1;
TM__GYgvYKeHVTEls0AcywABHQ_0[12].offset = offsetof(tyObject_OptParser__l9cyoK9aLLTUH7LBRIbLqETg, cmds);
TM__GYgvYKeHVTEls0AcywABHQ_0[12].typ = (&NTIseqLstringT__sM4lkSb7zS6F7OVMvW9cffQ_);
TM__GYgvYKeHVTEls0AcywABHQ_0[12].name = "cmds";
TM__GYgvYKeHVTEls0AcywABHQ_5_10[6] = &TM__GYgvYKeHVTEls0AcywABHQ_0[13];
TM__GYgvYKeHVTEls0AcywABHQ_0[13].kind = 1;
TM__GYgvYKeHVTEls0AcywABHQ_0[13].offset = offsetof(tyObject_OptParser__l9cyoK9aLLTUH7LBRIbLqETg, idx);
TM__GYgvYKeHVTEls0AcywABHQ_0[13].typ = (&NTIint__rR5Bzr1D5krxoo1NcNyeMA_);
TM__GYgvYKeHVTEls0AcywABHQ_0[13].name = "idx";
TM__GYgvYKeHVTEls0AcywABHQ_5_10[7] = &TM__GYgvYKeHVTEls0AcywABHQ_0[14];
TM__GYgvYKeHVTEls0AcywABHQ_0[14].kind = 1;
TM__GYgvYKeHVTEls0AcywABHQ_0[14].offset = offsetof(tyObject_OptParser__l9cyoK9aLLTUH7LBRIbLqETg, kind);
TM__GYgvYKeHVTEls0AcywABHQ_0[14].typ = (&NTIcmdlinekind__XkdXq9atxjiuhkFFh0XYrSA_);
TM__GYgvYKeHVTEls0AcywABHQ_0[14].name = "kind";
TM__GYgvYKeHVTEls0AcywABHQ_5_10[8] = &TM__GYgvYKeHVTEls0AcywABHQ_0[15];
TM__GYgvYKeHVTEls0AcywABHQ_0[15].kind = 1;
TM__GYgvYKeHVTEls0AcywABHQ_0[15].offset = offsetof(tyObject_OptParser__l9cyoK9aLLTUH7LBRIbLqETg, key);
TM__GYgvYKeHVTEls0AcywABHQ_0[15].typ = (&NTIstring__77mFvmsOLKik79ci2hXkHEg_);
TM__GYgvYKeHVTEls0AcywABHQ_0[15].name = "key";
TM__GYgvYKeHVTEls0AcywABHQ_5_10[9] = &TM__GYgvYKeHVTEls0AcywABHQ_0[16];
TM__GYgvYKeHVTEls0AcywABHQ_0[16].kind = 1;
TM__GYgvYKeHVTEls0AcywABHQ_0[16].offset = offsetof(tyObject_OptParser__l9cyoK9aLLTUH7LBRIbLqETg, val);
TM__GYgvYKeHVTEls0AcywABHQ_0[16].typ = (&NTIstring__77mFvmsOLKik79ci2hXkHEg_);
TM__GYgvYKeHVTEls0AcywABHQ_0[16].name = "val";
TM__GYgvYKeHVTEls0AcywABHQ_0[5].len = 10; TM__GYgvYKeHVTEls0AcywABHQ_0[5].kind = 2; TM__GYgvYKeHVTEls0AcywABHQ_0[5].sons = &TM__GYgvYKeHVTEls0AcywABHQ_5_10[0];
NTIoptparser__l9cyoK9aLLTUH7LBRIbLqETg_.node = &TM__GYgvYKeHVTEls0AcywABHQ_0[5];
}

