/* Generated by Nim Compiler v1.6.11 */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc__ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
NI align;
tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc__ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef NI16 tyUncheckedArray__Tyd4y3haUOOHTj71TPIRag[1];
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar___systemZwidestrs_260)(NI16* w, NI estimate, NI replacement);
N_NIMCALL(NimStringDesc*, rawNewString)(NI cap);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i, NI64 a, NI64 b);
N_LIB_PRIVATE N_NIMCALL(NI, ord__systemZwidestrs_8)(NI16 arg);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_2999)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
static N_NIMCALL(void, Marker_tyRef__4HwedE75WPfqZSQ0Cq2OUg)(void* p, NI op);
N_LIB_PRIVATE N_NOINLINE(void*, newObj)(TNimType* typ, NI size);
N_LIB_PRIVATE N_NIMCALL(NI16*, newWideCString__systemZwidestrs_231)(NCSTRING source, NI L);
static N_INLINE(NI, nimCStrLen)(NCSTRING a);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringDesc* s);
extern TNimType NTIint4954__kDPg4wXyR8DDyA0MeEjIsw_;
N_LIB_PRIVATE TNimType NTIuncheckedarrayLutf4954charT__Tyd4y3haUOOHTj71TPIRag_;
N_LIB_PRIVATE TNimType NTIwidecstringobj__4HwedE75WPfqZSQ0Cq2OUg_;
extern TFrame* framePtr__system_2566;
extern TFrame* framePtr__system_2566;
extern TFrame* framePtr__system_2566;
extern TFrame* framePtr__system_2566;
extern TFrame* framePtr__system_2566;
extern TFrame* framePtr__system_2566;
static N_INLINE(void, nimFrame)(TFrame* s) {
	{
		if (!(framePtr__system_2566 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s).calldepth = ((NI16) 0);
	}
	goto LA1_;
	LA3_: ;
	{
		(*s).calldepth = (NI16)((*framePtr__system_2566).calldepth + ((NI16) 1));
	}
	LA1_: ;
	(*s).prev = framePtr__system_2566;
	framePtr__system_2566 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;
		callDepthLimitReached__system_2999();
	}
	LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_2566 = (*framePtr__system_2566).prev;
}
N_LIB_PRIVATE N_NIMCALL(NI, ord__systemZwidestrs_8)(NI16 arg) {
	NI result;
	nimfr_("ord", "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
	result = (NI)0;
	nimln_(66, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
	result = ((NI) (((NU16) (arg))));
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar___systemZwidestrs_260)(NI16* w, NI estimate, NI replacement) {
	NimStringDesc* result;
	NI TM__R8z9bzATizpQoD67YeHNTdg_2;
	NI i;
	nimfr_("$", "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
	result = NIM_NIL;
	nimln_(177, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
	if (nimAddInt(estimate, (NI)((NI64)(estimate) >> (NU64)(((NI) 2))), &TM__R8z9bzATizpQoD67YeHNTdg_2)) { raiseOverflow(); };
	if (((NI)(TM__R8z9bzATizpQoD67YeHNTdg_2)) < ((NI) 0) || ((NI)(TM__R8z9bzATizpQoD67YeHNTdg_2)) > ((NI) IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__R8z9bzATizpQoD67YeHNTdg_2), ((NI) 0), ((NI) IL64(9223372036854775807))); }
	result = rawNewString(((NI) ((NI)(TM__R8z9bzATizpQoD67YeHNTdg_2))));
	nimln_(179, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
	i = ((NI) 0);
	{
		nimln_(180, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
		while (1) {
			NI ch;
			NI TM__R8z9bzATizpQoD67YeHNTdg_3;
			if (!!((w[i] == ((NI16) 0)))) goto LA2;
			nimln_(181, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
			ch = ord__systemZwidestrs_8(w[i]);
			nimln_(182, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
			if (nimAddInt(i, ((NI) 1), &TM__R8z9bzATizpQoD67YeHNTdg_3)) { raiseOverflow(); };
			i = (NI)(TM__R8z9bzATizpQoD67YeHNTdg_3);
			nimln_(183, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
			{
				NIM_BOOL T5_;
				NI ch2;
				T5_ = (NIM_BOOL)0;
				T5_ = (((NI) 55296) <= ch);
				if (!(T5_)) goto LA6_;
				T5_ = (ch <= ((NI) 56319));
				LA6_: ;
				if (!T5_) goto LA7_;
				nimln_(185, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
				ch2 = ord__systemZwidestrs_8(w[i]);
				nimln_(188, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
				{
					NIM_BOOL T11_;
					NI TM__R8z9bzATizpQoD67YeHNTdg_4;
					NI TM__R8z9bzATizpQoD67YeHNTdg_5;
					NI TM__R8z9bzATizpQoD67YeHNTdg_6;
					T11_ = (NIM_BOOL)0;
					T11_ = (((NI) 56320) <= ch2);
					if (!(T11_)) goto LA12_;
					T11_ = (ch2 <= ((NI) 57343));
					LA12_: ;
					if (!T11_) goto LA13_;
					nimln_(189, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
					if (nimAddInt((NI)((NU64)((NI)(ch & ((NI) 1023))) << (NU64)(((NI) 10))), (NI)(ch2 & ((NI) 1023)), &TM__R8z9bzATizpQoD67YeHNTdg_4)) { raiseOverflow(); };
					if (nimAddInt((NI)(TM__R8z9bzATizpQoD67YeHNTdg_4), ((NI) 65536), &TM__R8z9bzATizpQoD67YeHNTdg_5)) { raiseOverflow(); };
					ch = (NI)(TM__R8z9bzATizpQoD67YeHNTdg_5);
					nimln_(190, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
					if (nimAddInt(i, ((NI) 1), &TM__R8z9bzATizpQoD67YeHNTdg_6)) { raiseOverflow(); };
					i = (NI)(TM__R8z9bzATizpQoD67YeHNTdg_6);
				}
				goto LA9_;
				LA13_: ;
				{
					nimln_(193, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
					ch = replacement;
				}
				LA9_: ;
			}
			goto LA3_;
			LA7_: ;
			{
				NIM_BOOL T17_;
				nimln_(194, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
				T17_ = (NIM_BOOL)0;
				T17_ = (((NI) 56320) <= ch);
				if (!(T17_)) goto LA18_;
				T17_ = (ch <= ((NI) 57343));
				LA18_: ;
				if (!T17_) goto LA19_;
				nimln_(196, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
				ch = replacement;
			}
			goto LA3_;
			LA19_: ;
			LA3_: ;
			nimln_(198, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
			{
				if (!(ch < ((NI) 128))) goto LA23_;
				nimln_(199, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
				if ((ch) < ((NI) 0) || (ch) > ((NI) 255)){ raiseRangeErrorI(ch, ((NI) 0), ((NI) 255)); }
				result = addChar(result, ((NIM_CHAR) (((NI) (ch)))));
			}
			goto LA21_;
			LA23_: ;
			{
				nimln_(200, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
				if (!(ch < ((NI) 2048))) goto LA26_;
				nimln_(201, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
				if (((NI)((NI)((NI64)(ch) >> (NU64)(((NI) 6))) | ((NI) 192))) < ((NI) 0) || ((NI)((NI)((NI64)(ch) >> (NU64)(((NI) 6))) | ((NI) 192))) > ((NI) 255)){ raiseRangeErrorI((NI)((NI)((NI64)(ch) >> (NU64)(((NI) 6))) | ((NI) 192)), ((NI) 0), ((NI) 255)); }
				result = addChar(result, ((NIM_CHAR) (((NI) ((NI)((NI)((NI64)(ch) >> (NU64)(((NI) 6))) | ((NI) 192)))))));
				nimln_(202, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
				if (((NI)((NI)(ch & ((NI) 63)) | ((NI) 128))) < ((NI) 0) || ((NI)((NI)(ch & ((NI) 63)) | ((NI) 128))) > ((NI) 255)){ raiseRangeErrorI((NI)((NI)(ch & ((NI) 63)) | ((NI) 128)), ((NI) 0), ((NI) 255)); }
				result = addChar(result, ((NIM_CHAR) (((NI) ((NI)((NI)(ch & ((NI) 63)) | ((NI) 128)))))));
			}
			goto LA21_;
			LA26_: ;
			{
				nimln_(203, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
				if (!(ch < ((NI) 65536))) goto LA29_;
				nimln_(204, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
				if (((NI)((NI)((NI64)(ch) >> (NU64)(((NI) 12))) | ((NI) 224))) < ((NI) 0) || ((NI)((NI)((NI64)(ch) >> (NU64)(((NI) 12))) | ((NI) 224))) > ((NI) 255)){ raiseRangeErrorI((NI)((NI)((NI64)(ch) >> (NU64)(((NI) 12))) | ((NI) 224)), ((NI) 0), ((NI) 255)); }
				result = addChar(result, ((NIM_CHAR) (((NI) ((NI)((NI)((NI64)(ch) >> (NU64)(((NI) 12))) | ((NI) 224)))))));
				nimln_(205, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
				if (((NI)((NI)((NI)((NI64)(ch) >> (NU64)(((NI) 6))) & ((NI) 63)) | ((NI) 128))) < ((NI) 0) || ((NI)((NI)((NI)((NI64)(ch) >> (NU64)(((NI) 6))) & ((NI) 63)) | ((NI) 128))) > ((NI) 255)){ raiseRangeErrorI((NI)((NI)((NI)((NI64)(ch) >> (NU64)(((NI) 6))) & ((NI) 63)) | ((NI) 128)), ((NI) 0), ((NI) 255)); }
				result = addChar(result, ((NIM_CHAR) (((NI) ((NI)((NI)((NI)((NI64)(ch) >> (NU64)(((NI) 6))) & ((NI) 63)) | ((NI) 128)))))));
				nimln_(206, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
				if (((NI)((NI)(ch & ((NI) 63)) | ((NI) 128))) < ((NI) 0) || ((NI)((NI)(ch & ((NI) 63)) | ((NI) 128))) > ((NI) 255)){ raiseRangeErrorI((NI)((NI)(ch & ((NI) 63)) | ((NI) 128)), ((NI) 0), ((NI) 255)); }
				result = addChar(result, ((NIM_CHAR) (((NI) ((NI)((NI)(ch & ((NI) 63)) | ((NI) 128)))))));
			}
			goto LA21_;
			LA29_: ;
			{
				nimln_(207, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
				if (!(ch <= ((NI) 1114111))) goto LA32_;
				nimln_(208, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
				if (((NI)((NI)((NI64)(ch) >> (NU64)(((NI) 18))) | ((NI) 240))) < ((NI) 0) || ((NI)((NI)((NI64)(ch) >> (NU64)(((NI) 18))) | ((NI) 240))) > ((NI) 255)){ raiseRangeErrorI((NI)((NI)((NI64)(ch) >> (NU64)(((NI) 18))) | ((NI) 240)), ((NI) 0), ((NI) 255)); }
				result = addChar(result, ((NIM_CHAR) (((NI) ((NI)((NI)((NI64)(ch) >> (NU64)(((NI) 18))) | ((NI) 240)))))));
				nimln_(209, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
				if (((NI)((NI)((NI)((NI64)(ch) >> (NU64)(((NI) 12))) & ((NI) 63)) | ((NI) 128))) < ((NI) 0) || ((NI)((NI)((NI)((NI64)(ch) >> (NU64)(((NI) 12))) & ((NI) 63)) | ((NI) 128))) > ((NI) 255)){ raiseRangeErrorI((NI)((NI)((NI)((NI64)(ch) >> (NU64)(((NI) 12))) & ((NI) 63)) | ((NI) 128)), ((NI) 0), ((NI) 255)); }
				result = addChar(result, ((NIM_CHAR) (((NI) ((NI)((NI)((NI)((NI64)(ch) >> (NU64)(((NI) 12))) & ((NI) 63)) | ((NI) 128)))))));
				nimln_(210, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
				if (((NI)((NI)((NI)((NI64)(ch) >> (NU64)(((NI) 6))) & ((NI) 63)) | ((NI) 128))) < ((NI) 0) || ((NI)((NI)((NI)((NI64)(ch) >> (NU64)(((NI) 6))) & ((NI) 63)) | ((NI) 128))) > ((NI) 255)){ raiseRangeErrorI((NI)((NI)((NI)((NI64)(ch) >> (NU64)(((NI) 6))) & ((NI) 63)) | ((NI) 128)), ((NI) 0), ((NI) 255)); }
				result = addChar(result, ((NIM_CHAR) (((NI) ((NI)((NI)((NI)((NI64)(ch) >> (NU64)(((NI) 6))) & ((NI) 63)) | ((NI) 128)))))));
				nimln_(211, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
				if (((NI)((NI)(ch & ((NI) 63)) | ((NI) 128))) < ((NI) 0) || ((NI)((NI)(ch & ((NI) 63)) | ((NI) 128))) > ((NI) 255)){ raiseRangeErrorI((NI)((NI)(ch & ((NI) 63)) | ((NI) 128)), ((NI) 0), ((NI) 255)); }
				result = addChar(result, ((NIM_CHAR) (((NI) ((NI)((NI)(ch & ((NI) 63)) | ((NI) 128)))))));
			}
			goto LA21_;
			LA32_: ;
			{
				nimln_(214, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
				result = addChar(result, 239);
				nimln_(215, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
				result = addChar(result, 191);
				nimln_(216, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
				result = addChar(result, 189);
			}
			LA21_: ;
		} LA2: ;
	}
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar___systemZwidestrs_324)(NI16* s) {
	NimStringDesc* result;
	nimfr_("$", "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
	result = NIM_NIL;
	nimln_(219, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
	result = dollar___systemZwidestrs_260(s, ((NI) 80), ((NI) 65533));
	popFrame();
	return result;
}
static N_NIMCALL(void, Marker_tyRef__4HwedE75WPfqZSQ0Cq2OUg)(void* p, NI op) {
	NI16* a;
	a = (NI16*)p;
}
N_LIB_PRIVATE N_NIMCALL(NI16*, newWideCString__systemZwidestrs_231)(NCSTRING source, NI L) {
	NI16* result;
	NI TM__R8z9bzATizpQoD67YeHNTdg_7;
	NI TM__R8z9bzATizpQoD67YeHNTdg_8;
	NI d;
	nimfr_("newWideCString", "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
	result = NIM_NIL;
	nimln_(149, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
	if (nimMulInt(L, ((NI) 2), &TM__R8z9bzATizpQoD67YeHNTdg_7)) { raiseOverflow(); };
	if (nimAddInt((NI)(TM__R8z9bzATizpQoD67YeHNTdg_7), ((NI) 2), &TM__R8z9bzATizpQoD67YeHNTdg_8)) { raiseOverflow(); };
	if (((NI)(TM__R8z9bzATizpQoD67YeHNTdg_8)) < ((NI) 0) || ((NI)(TM__R8z9bzATizpQoD67YeHNTdg_8)) > ((NI) IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__R8z9bzATizpQoD67YeHNTdg_8), ((NI) 0), ((NI) IL64(9223372036854775807))); }
	result = (NI16*) newObj((&NTIwidecstringobj__4HwedE75WPfqZSQ0Cq2OUg_), ((NI) ((NI)(TM__R8z9bzATizpQoD67YeHNTdg_8))));
	nimln_(150, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
	d = ((NI) 0);
	{
		NI ch;
		NI i;
		NI result_2;
		ch = (NI)0;
		nimln_(139, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
		i = ((NI) 0);
		result_2 = (NI)0;
		{
			nimln_(141, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
			while (1) {
				NI TM__R8z9bzATizpQoD67YeHNTdg_30;
				if (!(i < L)) goto LA3;
				nimln_(142, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
				{
					NI TM__R8z9bzATizpQoD67YeHNTdg_9;
					nimln_(98, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
					if (!(((NU8)(source[i])) <= ((NI) 127))) goto LA6_;
					nimln_(99, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
					result_2 = ((NU8)(source[i]));
					nimln_(100, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
					if (nimAddInt(i, ((NI) 1), &TM__R8z9bzATizpQoD67YeHNTdg_9)) { raiseOverflow(); };
					i = (NI)(TM__R8z9bzATizpQoD67YeHNTdg_9);
				}
				goto LA4_;
				LA6_: ;
				{
					nimln_(101, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
					if (!((NI)((NI64)(((NU8)(source[i]))) >> (NU64)(((NI) 5))) == ((NI) 6))) goto LA9_;
					nimln_(103, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
					{
						NI TM__R8z9bzATizpQoD67YeHNTdg_10;
						NI TM__R8z9bzATizpQoD67YeHNTdg_11;
						NI TM__R8z9bzATizpQoD67YeHNTdg_12;
						if (nimSubInt(L, ((NI) 2), &TM__R8z9bzATizpQoD67YeHNTdg_10)) { raiseOverflow(); };
						if (!(i <= (NI)(TM__R8z9bzATizpQoD67YeHNTdg_10))) goto LA13_;
						nimln_(104, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
						if (nimAddInt(i, ((NI) 1), &TM__R8z9bzATizpQoD67YeHNTdg_11)) { raiseOverflow(); };
						result_2 = (NI)((NI)((NU64)((NI)(((NU8)(source[i])) & ((NI) 31))) << (NU64)(((NI) 6))) | (NI)(((NU8)(source[(NI)(TM__R8z9bzATizpQoD67YeHNTdg_11)])) & ((NI) 63)));
						nimln_(105, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
						if (nimAddInt(i, ((NI) 2), &TM__R8z9bzATizpQoD67YeHNTdg_12)) { raiseOverflow(); };
						i = (NI)(TM__R8z9bzATizpQoD67YeHNTdg_12);
					}
					goto LA11_;
					LA13_: ;
					{
						NI TM__R8z9bzATizpQoD67YeHNTdg_13;
						nimln_(107, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
						result_2 = ((NI) 65533);
						nimln_(108, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
						if (nimAddInt(i, ((NI) 1), &TM__R8z9bzATizpQoD67YeHNTdg_13)) { raiseOverflow(); };
						i = (NI)(TM__R8z9bzATizpQoD67YeHNTdg_13);
					}
					LA11_: ;
				}
				goto LA4_;
				LA9_: ;
				{
					nimln_(109, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
					if (!((NI)((NI64)(((NU8)(source[i]))) >> (NU64)(((NI) 4))) == ((NI) 14))) goto LA17_;
					nimln_(110, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
					{
						NI TM__R8z9bzATizpQoD67YeHNTdg_14;
						NI TM__R8z9bzATizpQoD67YeHNTdg_15;
						NI TM__R8z9bzATizpQoD67YeHNTdg_16;
						NI TM__R8z9bzATizpQoD67YeHNTdg_17;
						if (nimSubInt(L, ((NI) 3), &TM__R8z9bzATizpQoD67YeHNTdg_14)) { raiseOverflow(); };
						if (!(i <= (NI)(TM__R8z9bzATizpQoD67YeHNTdg_14))) goto LA21_;
						nimln_(114, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
						nimln_(113, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
						nimln_(114, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
						if (nimAddInt(i, ((NI) 1), &TM__R8z9bzATizpQoD67YeHNTdg_15)) { raiseOverflow(); };
						nimln_(115, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
						if (nimAddInt(i, ((NI) 2), &TM__R8z9bzATizpQoD67YeHNTdg_16)) { raiseOverflow(); };
						result_2 = (NI)((NI)((NI)((NU64)((NI)(((NU8)(source[i])) & ((NI) 15))) << (NU64)(((NI) 12))) | (NI)((NU64)((NI)(((NU8)(source[(NI)(TM__R8z9bzATizpQoD67YeHNTdg_15)])) & ((NI) 63))) << (NU64)(((NI) 6)))) | (NI)(((NU8)(source[(NI)(TM__R8z9bzATizpQoD67YeHNTdg_16)])) & ((NI) 63)));
						nimln_(116, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
						if (nimAddInt(i, ((NI) 3), &TM__R8z9bzATizpQoD67YeHNTdg_17)) { raiseOverflow(); };
						i = (NI)(TM__R8z9bzATizpQoD67YeHNTdg_17);
					}
					goto LA19_;
					LA21_: ;
					{
						NI TM__R8z9bzATizpQoD67YeHNTdg_18;
						nimln_(118, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
						result_2 = ((NI) 65533);
						nimln_(119, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
						if (nimAddInt(i, ((NI) 1), &TM__R8z9bzATizpQoD67YeHNTdg_18)) { raiseOverflow(); };
						i = (NI)(TM__R8z9bzATizpQoD67YeHNTdg_18);
					}
					LA19_: ;
				}
				goto LA4_;
				LA17_: ;
				{
					nimln_(120, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
					if (!((NI)((NI64)(((NU8)(source[i]))) >> (NU64)(((NI) 3))) == ((NI) 30))) goto LA25_;
					nimln_(121, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
					{
						NI TM__R8z9bzATizpQoD67YeHNTdg_19;
						NI TM__R8z9bzATizpQoD67YeHNTdg_20;
						NI TM__R8z9bzATizpQoD67YeHNTdg_21;
						NI TM__R8z9bzATizpQoD67YeHNTdg_22;
						NI TM__R8z9bzATizpQoD67YeHNTdg_23;
						if (nimSubInt(L, ((NI) 4), &TM__R8z9bzATizpQoD67YeHNTdg_19)) { raiseOverflow(); };
						if (!(i <= (NI)(TM__R8z9bzATizpQoD67YeHNTdg_19))) goto LA29_;
						nimln_(127, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
						nimln_(126, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
						nimln_(125, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
						nimln_(126, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
						if (nimAddInt(i, ((NI) 1), &TM__R8z9bzATizpQoD67YeHNTdg_20)) { raiseOverflow(); };
						nimln_(127, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
						if (nimAddInt(i, ((NI) 2), &TM__R8z9bzATizpQoD67YeHNTdg_21)) { raiseOverflow(); };
						nimln_(128, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
						if (nimAddInt(i, ((NI) 3), &TM__R8z9bzATizpQoD67YeHNTdg_22)) { raiseOverflow(); };
						result_2 = (NI)((NI)((NI)((NI)((NU64)((NI)(((NU8)(source[i])) & ((NI) 7))) << (NU64)(((NI) 18))) | (NI)((NU64)((NI)(((NU8)(source[(NI)(TM__R8z9bzATizpQoD67YeHNTdg_20)])) & ((NI) 63))) << (NU64)(((NI) 12)))) | (NI)((NU64)((NI)(((NU8)(source[(NI)(TM__R8z9bzATizpQoD67YeHNTdg_21)])) & ((NI) 63))) << (NU64)(((NI) 6)))) | (NI)(((NU8)(source[(NI)(TM__R8z9bzATizpQoD67YeHNTdg_22)])) & ((NI) 63)));
						nimln_(129, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
						if (nimAddInt(i, ((NI) 4), &TM__R8z9bzATizpQoD67YeHNTdg_23)) { raiseOverflow(); };
						i = (NI)(TM__R8z9bzATizpQoD67YeHNTdg_23);
					}
					goto LA27_;
					LA29_: ;
					{
						NI TM__R8z9bzATizpQoD67YeHNTdg_24;
						nimln_(131, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
						result_2 = ((NI) 65533);
						nimln_(132, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
						if (nimAddInt(i, ((NI) 1), &TM__R8z9bzATizpQoD67YeHNTdg_24)) { raiseOverflow(); };
						i = (NI)(TM__R8z9bzATizpQoD67YeHNTdg_24);
					}
					LA27_: ;
				}
				goto LA4_;
				LA25_: ;
				{
					NI TM__R8z9bzATizpQoD67YeHNTdg_25;
					nimln_(134, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
					result_2 = ((NI) 65533);
					nimln_(135, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
					if (nimAddInt(i, ((NI) 1), &TM__R8z9bzATizpQoD67YeHNTdg_25)) { raiseOverflow(); };
					i = (NI)(TM__R8z9bzATizpQoD67YeHNTdg_25);
				}
				LA4_: ;
				nimln_(151, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
				ch = result_2;
				{
					nimln_(153, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
					if (!(ch <= ((NI) 65535))) goto LA35_;
					nimln_(154, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
					{
						NIM_BOOL T39_;
						T39_ = (NIM_BOOL)0;
						T39_ = (((NI) 55296) <= ch);
						if (!(T39_)) goto LA40_;
						T39_ = (ch <= ((NI) 57343));
						LA40_: ;
						if (!T39_) goto LA41_;
						nimln_(155, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
						result[d] = ((NI16) -3);
					}
					goto LA37_;
					LA41_: ;
					{
						nimln_(157, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
						result[d] = ((NI16) (((NU16) (ch))));
					}
					LA37_: ;
				}
				goto LA33_;
				LA35_: ;
				{
					nimln_(158, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
					if (!(((NI) 1114111) < ch)) goto LA45_;
					nimln_(159, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
					result[d] = ((NI16) -3);
				}
				goto LA33_;
				LA45_: ;
				{
					NI ch_2;
					NI TM__R8z9bzATizpQoD67YeHNTdg_26;
					NI TM__R8z9bzATizpQoD67YeHNTdg_27;
					NI TM__R8z9bzATizpQoD67YeHNTdg_28;
					NI TM__R8z9bzATizpQoD67YeHNTdg_29;
					nimln_(161, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
					if (nimSubInt(ch, ((NI) 65536), &TM__R8z9bzATizpQoD67YeHNTdg_26)) { raiseOverflow(); };
					ch_2 = (NI)(TM__R8z9bzATizpQoD67YeHNTdg_26);
					nimln_(162, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
					if (nimAddInt((NI)((NI64)(ch_2) >> (NU64)(((NI) 10))), ((NI) 55296), &TM__R8z9bzATizpQoD67YeHNTdg_27)) { raiseOverflow(); };
					result[d] = ((NI16) (((NU16) ((NI)(TM__R8z9bzATizpQoD67YeHNTdg_27)))));
					nimln_(163, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
					if (nimAddInt(d, ((NI) 1), &TM__R8z9bzATizpQoD67YeHNTdg_28)) { raiseOverflow(); };
					d = (NI)(TM__R8z9bzATizpQoD67YeHNTdg_28);
					nimln_(164, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
					if (nimAddInt((NI)(ch_2 & ((NI) 1023)), ((NI) 56320), &TM__R8z9bzATizpQoD67YeHNTdg_29)) { raiseOverflow(); };
					result[d] = ((NI16) (((NU16) ((NI)(TM__R8z9bzATizpQoD67YeHNTdg_29)))));
				}
				LA33_: ;
				nimln_(151, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
				if (nimAddInt(d, ((NI) 1), &TM__R8z9bzATizpQoD67YeHNTdg_30)) { raiseOverflow(); };
				d = (NI)(TM__R8z9bzATizpQoD67YeHNTdg_30);
			} LA3: ;
		}
	}
	nimln_(166, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
	result[d] = ((NI16) 0);
	popFrame();
	return result;
}
static N_INLINE(NI, nimCStrLen)(NCSTRING a) {
	NI result;
	size_t T1_;
	result = (NI)0;
	T1_ = (size_t)0;
	T1_ = strlen(a);
	result = ((NI) (T1_));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI16*, newWideCString__systemZwidestrs_254)(NCSTRING s) {
	NI16* result;
	nimfr_("newWideCString", "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
{	result = NIM_NIL;
	nimln_(169, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
	{
		if (!(s == 0)) goto LA3_;
		result = ((NI16*) NIM_NIL);
		goto BeforeRet_;
	}
	LA3_: ;
	nimln_(171, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
	result = newWideCString__systemZwidestrs_231(s, (s ? nimCStrLen(s) : 0));
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringDesc* s) {
	NCSTRING result;
	result = (NCSTRING)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (s == ((NimStringDesc*) NIM_NIL));
		if (T3_) goto LA4_;
		T3_ = ((*s).Sup.len == ((NI) 0));
		LA4_: ;
		if (!T3_) goto LA5_;
		result = "";
	}
	goto LA1_;
	LA5_: ;
	{
		result = ((NCSTRING) ((*s).data));
	}
	LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI16*, newWideCString__systemZwidestrs_257)(NimStringDesc* s) {
	NI16* result;
	nimfr_("newWideCString", "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
	result = NIM_NIL;
	nimln_(174, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
	result = newWideCString__systemZwidestrs_231(nimToCStringConv(s), (s ? s->Sup.len : 0));
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI16*, newWideCString__systemZwidestrs_206)(NI size) {
	NI16* result;
	NI TM__R8z9bzATizpQoD67YeHNTdg_31;
	NI TM__R8z9bzATizpQoD67YeHNTdg_32;
	nimfr_("newWideCString", "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
	result = NIM_NIL;
	nimln_(146, "/home/yyoncho/.choosenim/toolchains/nim-#version-1-6/lib/system/widestrs.nim");
	if (nimMulInt(size, ((NI) 2), &TM__R8z9bzATizpQoD67YeHNTdg_31)) { raiseOverflow(); };
	if (nimAddInt((NI)(TM__R8z9bzATizpQoD67YeHNTdg_31), ((NI) 2), &TM__R8z9bzATizpQoD67YeHNTdg_32)) { raiseOverflow(); };
	if (((NI)(TM__R8z9bzATizpQoD67YeHNTdg_32)) < ((NI) 0) || ((NI)(TM__R8z9bzATizpQoD67YeHNTdg_32)) > ((NI) IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__R8z9bzATizpQoD67YeHNTdg_32), ((NI) 0), ((NI) IL64(9223372036854775807))); }
	result = (NI16*) newObj((&NTIwidecstringobj__4HwedE75WPfqZSQ0Cq2OUg_), ((NI) ((NI)(TM__R8z9bzATizpQoD67YeHNTdg_32))));
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotdotatsdotdotatsdotchoosenimatstoolchainsatsnimminusathversionminus1minus6atslibatssystematswidestrsdotnim_DatInit000)(void) {
NTIuncheckedarrayLutf4954charT__Tyd4y3haUOOHTj71TPIRag_.size = sizeof(tyUncheckedArray__Tyd4y3haUOOHTj71TPIRag);
NTIuncheckedarrayLutf4954charT__Tyd4y3haUOOHTj71TPIRag_.align = NIM_ALIGNOF(tyUncheckedArray__Tyd4y3haUOOHTj71TPIRag);
NTIuncheckedarrayLutf4954charT__Tyd4y3haUOOHTj71TPIRag_.kind = 49;
NTIuncheckedarrayLutf4954charT__Tyd4y3haUOOHTj71TPIRag_.base = (&NTIint4954__kDPg4wXyR8DDyA0MeEjIsw_);
NTIuncheckedarrayLutf4954charT__Tyd4y3haUOOHTj71TPIRag_.flags = 3;
NTIwidecstringobj__4HwedE75WPfqZSQ0Cq2OUg_.size = sizeof(NI16*);
NTIwidecstringobj__4HwedE75WPfqZSQ0Cq2OUg_.align = NIM_ALIGNOF(NI16*);
NTIwidecstringobj__4HwedE75WPfqZSQ0Cq2OUg_.kind = 22;
NTIwidecstringobj__4HwedE75WPfqZSQ0Cq2OUg_.base = (&NTIuncheckedarrayLutf4954charT__Tyd4y3haUOOHTj71TPIRag_);
NTIwidecstringobj__4HwedE75WPfqZSQ0Cq2OUg_.marker = Marker_tyRef__4HwedE75WPfqZSQ0Cq2OUg;
}

