/* Generated by Nim Compiler v1.7.1 */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <windows.h>
#include <stdio.h>
#include <io.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  typedef struct tyObject_PTerminalcolonObjectType___EcU8GhMNGo9bGDXbfqZ82og tyObject_PTerminalcolonObjectType___EcU8GhMNGo9bGDXbfqZ82og;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_CONSOLE_SCREEN_BUFFER_INFO__r6d5R6U7A9aP1xHUbo2o04A tyObject_CONSOLE_SCREEN_BUFFER_INFO__r6d5R6U7A9aP1xHUbo2o04A;
typedef struct tyObject_COORD__38Oq1GgFPIYv2ksRi9c0fZA tyObject_COORD__38Oq1GgFPIYv2ksRi9c0fZA;
typedef struct tyObject_SMALL_RECT__GSDbaE1SdabWptSZYJG3XA tyObject_SMALL_RECT__GSDbaE1SdabWptSZYJG3XA;
typedef struct tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack__7fytPA5bBsob6See21YMRA tyObject_GcStack__7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple__ujsjpB2O9cjj3uDHsXbnSzg tyTuple__ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_SharedList__JI9cx34TL8n3aOKF6tSMBUw tyObject_SharedList__JI9cx34TL8n3aOKF6tSMBUw;
typedef struct tyObject_SharedListNodecolonObjectType___KGw0YAw6W9aSz3Sr9aXGu7zg tyObject_SharedListNodecolonObjectType___KGw0YAw6W9aSz3Sr9aXGu7zg;
typedef struct tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ;
typedef struct tyObject_CONSOLE_CURSOR_INFO__2bHqrjf9blMFjr48HNl45eA tyObject_CONSOLE_CURSOR_INFO__2bHqrjf9blMFjr48HNl45eA;
typedef struct tyObject_KEY_EVENT_RECORD__Ph22QYSbYUBAezvb9bd9cevA tyObject_KEY_EVENT_RECORD__Ph22QYSbYUBAezvb9bd9cevA;
struct tyObject_PTerminalcolonObjectType___EcU8GhMNGo9bGDXbfqZ82og {
NIM_BOOL trueColorIsSupported;
NIM_BOOL trueColorIsEnabled;
NIM_BOOL fgSetColor;
NI hStdout;
NI hStderr;
NI16 oldStdoutAttr;
NI16 oldStderrAttr;
};
typedef NU8 tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc__ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
NI align;
tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc__ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_NIMCALL_PTR(void, tyProc__T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
typedef NU8 tyEnum_ForegroundColor__ez9ah4IgQc0AbdW68acioDg;
typedef N_STDCALL_PTR(NI, tyProc__zP2zGemcuVRvOUE82f9a0Pw) (NI32 nStdHandle);
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_STDCALL_PTR(NI32, tyProc__oew1DfaGl5XhHmnBK0HYXQ) (NI hSourceProcessHandle, NI hSourceHandle, NI hTargetProcessHandle, NI* lpTargetHandle, NI32 dwDesiredAccess, NI32 bInheritHandle, NI32 dwOptions);
typedef N_STDCALL_PTR(NI, tyProc__uryidYWkntM7ddjZSyxvyQ) (void);
struct tyObject_COORD__38Oq1GgFPIYv2ksRi9c0fZA {
NI16 x;
NI16 y;
};
struct tyObject_SMALL_RECT__GSDbaE1SdabWptSZYJG3XA {
NI16 left;
NI16 top;
NI16 right;
NI16 bottom;
};
struct tyObject_CONSOLE_SCREEN_BUFFER_INFO__r6d5R6U7A9aP1xHUbo2o04A {
tyObject_COORD__38Oq1GgFPIYv2ksRi9c0fZA dwSize;
tyObject_COORD__38Oq1GgFPIYv2ksRi9c0fZA dwCursorPosition;
NI16 wAttributes;
tyObject_SMALL_RECT__GSDbaE1SdabWptSZYJG3XA srWindow;
tyObject_COORD__38Oq1GgFPIYv2ksRi9c0fZA dwMaximumWindowSize;
};
typedef N_STDCALL_PTR(NI32, tyProc__vjGHiWUJwFzOgSxDffBb6Q) (NI hConsoleOutput, tyObject_CONSOLE_SCREEN_BUFFER_INFO__r6d5R6U7A9aP1xHUbo2o04A* lpConsoleScreenBufferInfo);
struct tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack__7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ* tyArray__SPr7N6UKfuF549bNPiUvSRw[256];
typedef NU32 tyArray__BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg* tyArray__N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray__N1u1nqOgmuJN9cSZrnMHgOQ tyArray__B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw* tyArray__lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA {
tyArray__lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* tyArray__0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw {
tyArray__0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple__ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple__ujsjpB2O9cjj3uDHsXbnSzg tyArray__LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray__LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray__SPr7N6UKfuF549bNPiUvSRw freeSmallChunks;
NU32 flBitmap;
tyArray__BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray__B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_SharedList__JI9cx34TL8n3aOKF6tSMBUw {
tyObject_SharedListNodecolonObjectType___KGw0YAw6W9aSz3Sr9aXGu7zg* head;
tyObject_SharedListNodecolonObjectType___KGw0YAw6W9aSz3Sr9aXGu7zg* tail;
CRITICAL_SECTION lock;
};
struct tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack__7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
NI zctThreshold;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w additionalRoots;
tyObject_SharedList__JI9cx34TL8n3aOKF6tSMBUw toDispose;
NI gcThreadId;
};
typedef N_STDCALL_PTR(NI32, tyProc__oPCjp4xTgEl9a8fqSzOv8lw) (NI hConsoleOutput, NI16 wAttributes);
typedef NI tyArray__e7dTfxuKO1YfQGLA3anCHg[10];
typedef NU16 tySet_tyEnum_Style__NXKayqTLMsAibFwNceBlpA;
typedef NU8 tyEnum_Style__NXKayqTLMsAibFwNceBlpA;
struct tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ {
NI Field0;
NI Field1;
};
typedef N_STDCALL_PTR(NI32, tyProc__aqCTygSFeRmCMIAcNfrPcQ) (NI hConsoleOutput, tyObject_COORD__38Oq1GgFPIYv2ksRi9c0fZA dwCursorPosition);
struct tyObject_CONSOLE_CURSOR_INFO__2bHqrjf9blMFjr48HNl45eA {
NI32 dwSize;
NI32 bVisible;
};
typedef N_STDCALL_PTR(NI32, tyProc__Ag9bpoEvIZqYa8ny0e3IH9cw) (NI hConsoleOutput, tyObject_CONSOLE_CURSOR_INFO__2bHqrjf9blMFjr48HNl45eA* lpConsoleCursorInfo);
struct tyObject_KEY_EVENT_RECORD__Ph22QYSbYUBAezvb9bd9cevA {
NI16 eventType;
NI32 bKeyDown;
NI16 wRepeatCount;
NI16 wVirtualKeyCode;
NI16 wVirtualScanCode;
NI16 uChar;
NI32 dwControlKeyState;
};
typedef N_STDCALL_PTR(NI32, tyProc__FprzxJFfqQdWyyGxiUsmeQ) (NI hHandle, NI32 dwMilliseconds);
typedef N_STDCALL_PTR(int, tyProc__XG9bMafAwcENm7BYV2xEMUg) (NI hConsoleInput, void* lpBuffer, int nLength, int* lpNumberOfEventsRead);
typedef N_STDCALL_PTR(NI32, tyProc__U0n37n0G5WXtFwK5fJhDmg) (NI hConsoleOutput, NIM_CHAR cCharacter, NI32 nLength, tyObject_COORD__38Oq1GgFPIYv2ksRi9c0fZA dwWriteCoord, NI32* lpNumberOfCharsWritten);
typedef N_STDCALL_PTR(NI32, tyProc__pXMrjvyowjvaOKheIba8Fg) (NI hConsoleOutput, NI16 wAttribute, NI32 nLength, tyObject_COORD__38Oq1GgFPIYv2ksRi9c0fZA dwWriteCoord, NI32* lpNumberOfAttrsWritten);
static N_NIMCALL(void, Marker_tyRef__flNJLrANZti6Wiy5LTlGGA)(void* p, NI op);
N_LIB_PRIVATE N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, TM__CN3raB9atujkEiPpxYAdlgQ_3)(void);
N_LIB_PRIVATE N_NIMCALL(void, nimRegisterThreadLocalMarker)(tyProc__T4eqaYlFJYZUv9aG9b1TV0bQ markerProc);
static N_INLINE(tyObject_PTerminalcolonObjectType___EcU8GhMNGo9bGDXbfqZ82og*, getTerminal__pureZterminal_26)(void);
N_LIB_PRIVATE N_NIMCALL(tyObject_PTerminalcolonObjectType___EcU8GhMNGo9bGDXbfqZ82og*, newTerminal__pureZterminal_16)(void);
N_LIB_PRIVATE N_NOINLINE(void*, newObj)(TNimType* typ, NI size);
N_LIB_PRIVATE N_NIMCALL(void, initTerminal__pureZterminal_182)(tyObject_PTerminalcolonObjectType___EcU8GhMNGo9bGDXbfqZ82og* term);
N_LIB_PRIVATE N_NIMCALL(void*, nimLoadLibrary)(NimStringDesc* path);
N_LIB_PRIVATE N_NIMCALL(void, nimLoadLibraryError)(NimStringDesc* path);
N_LIB_PRIVATE N_NIMCALL(void*, nimGetProcAddr)(void* lib, NCSTRING name);
N_LIB_PRIVATE N_NIMCALL(NI16, getAttributes__pureZterminal_178)(NI h);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_3455)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef__system_5879)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(NI, pluspercent___system_696)(NI x, NI y);
static N_INLINE(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell__system_5841)(void* usr);
static N_INLINE(NI, minuspercent___system_716)(NI x, NI y);
static N_INLINE(void, decRef__system_5886)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(NIM_BOOL, ltpercent___system_1005)(NI x, NI y);
static N_INLINE(void, rtlAddZCT__system_5884)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT__system_5835)(tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NIMCALL(NI16, toU16__system_301)(NI x);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError3)(NI i, NI a, NI b);
N_LIB_PRIVATE N_NIMCALL(void, setStyle__pureZterminal_422)(FILE* f, tySet_tyEnum_Style__NXKayqTLMsAibFwNceBlpA style);
N_LIB_PRIVATE N_NIMCALL(void, write__stdZsyncio_220)(FILE* f, NimStringDesc* s);
N_LIB_PRIVATE N_NIMCALL(void, resetAttributes__pureZterminal_347)(FILE* f);
N_LIB_PRIVATE N_NIMCALL(int, getFileHandle__stdZsyncio_248)(FILE* f);
N_LIB_PRIVATE N_NIMCALL(tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ, getCursorPos__pureZterminal_158)(NI h);
N_LIB_PRIVATE N_NOINLINE(void, raiseOSError__pureZos_477)(NI32 errorCode, NimStringDesc* additionalInfo);
N_LIB_PRIVATE N_NIMCALL(NI32, osLastError__pureZos_480)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(void, setCursorPos__pureZterminal_164)(NI h, NI x, NI y);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i, NI64 a, NI64 b);
N_LIB_PRIVATE N_NIMCALL(void, setCursorVisibility__pureZterminal_193)(FILE* f, NIM_BOOL visible);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__stdZassertions_56)(NimStringDesc* msg);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorU)(NU64 i, NU64 a, NU64 b);
N_LIB_PRIVATE TNimType NTIpterminal58objecttype__EcU8GhMNGo9bGDXbfqZ82og_;
extern TNimType NTIbool__VaVACK0bpYmqIQ0mKcHfQQ_;
extern TNimType NTIint__rR5Bzr1D5krxoo1NcNyeMA_;
extern TNimType NTIint4954__kDPg4wXyR8DDyA0MeEjIsw_;
N_LIB_PRIVATE TNimType NTIpterminal__flNJLrANZti6Wiy5LTlGGA_;
STRING_LITERAL(TM__CN3raB9atujkEiPpxYAdlgQ_6, "kernel32", 8);
STRING_LITERAL(TM__CN3raB9atujkEiPpxYAdlgQ_7, "kernel32", 8);
N_LIB_PRIVATE NIM_CONST tyArray__e7dTfxuKO1YfQGLA3anCHg lookup__pureZterminal_498 = {((NI) 0),
((NI) 4),
((NI) 2),
((NI) 6),
((NI) 1),
((NI) 5),
((NI) 3),
((NI) 7),
((NI) 0),
((NI) 0)}
;
STRING_LITERAL(TM__CN3raB9atujkEiPpxYAdlgQ_26, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim(812, 15) `waitForSingleObject(fd, INFINITE) == WAIT_OBJECT_0` ", 114);
STRING_LITERAL(TM__CN3raB9atujkEiPpxYAdlgQ_27, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim(813, 15) `readConsoleInput(fd, addr(keyEvent), 1, addr(numRead)) != 0` ", 123);
N_LIB_PRIVATE NIM_THREADVAR tyObject_PTerminalcolonObjectType___EcU8GhMNGo9bGDXbfqZ82og* gTerm__pureZterminal_15;
N_LIB_PRIVATE NI16 defaultForegroundColor__pureZterminal_484 = ((NI16) -1);
N_LIB_PRIVATE NI16 defaultBackgroundColor__pureZterminal_485 = ((NI16) -1);
extern tyProc__zP2zGemcuVRvOUE82f9a0Pw Dl_1392509091_;
static void* TM__CN3raB9atujkEiPpxYAdlgQ_4;
tyProc__oew1DfaGl5XhHmnBK0HYXQ Dl_2432696387_;
tyProc__uryidYWkntM7ddjZSyxvyQ Dl_2432696395_;
tyProc__vjGHiWUJwFzOgSxDffBb6Q Dl_2432696396_;
extern NIM_THREADVAR TFrame* framePtr__system_3022;
extern NIM_THREADVAR TFrame* framePtr__system_3022;
extern NIM_THREADVAR TFrame* framePtr__system_3022;
extern NIM_THREADVAR TFrame* framePtr__system_3022;
extern NIM_THREADVAR TFrame* framePtr__system_3022;
extern NIM_THREADVAR TFrame* framePtr__system_3022;
extern NIM_THREADVAR tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ gch__system_5774;
tyProc__oPCjp4xTgEl9a8fqSzOv8lw Dl_2432696469_;
tyProc__aqCTygSFeRmCMIAcNfrPcQ Dl_2432696454_;
tyProc__Ag9bpoEvIZqYa8ny0e3IH9cw Dl_2432696399_;
tyProc__Ag9bpoEvIZqYa8ny0e3IH9cw Dl_2432696402_;
extern tyProc__FprzxJFfqQdWyyGxiUsmeQ Dl_1392509082_;
extern tyProc__XG9bMafAwcENm7BYV2xEMUg Dl_1392509985_;
tyProc__U0n37n0G5WXtFwK5fJhDmg Dl_2432696457_;
tyProc__pXMrjvyowjvaOKheIba8Fg Dl_2432696463_;
static N_NIMCALL(void, Marker_tyRef__flNJLrANZti6Wiy5LTlGGA)(void* p, NI op) {
	tyObject_PTerminalcolonObjectType___EcU8GhMNGo9bGDXbfqZ82og* a;
	a = (tyObject_PTerminalcolonObjectType___EcU8GhMNGo9bGDXbfqZ82og*)p;
}
static N_NIMCALL(void, TM__CN3raB9atujkEiPpxYAdlgQ_3)(void) {
	nimGCvisit((void*)gTerm__pureZterminal_15, 0);
}
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a, v, ((size_t) (size)));
}
static N_INLINE(void, nimZeroMem)(void* p, NI size) {
	nimSetMem__systemZmemory_7(p, ((int) 0), size);
}
static N_INLINE(void, nimFrame)(TFrame* s) {
	{
		if (!(framePtr__system_3022 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s).calldepth = ((NI16) 0);
	}
	goto LA1_;
	LA3_: ;
	{
		(*s).calldepth = (NI16)((*framePtr__system_3022).calldepth + ((NI16) 1));
	}
	LA1_: ;
	(*s).prev = framePtr__system_3022;
	framePtr__system_3022 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;
		callDepthLimitReached__system_3455();
	}
	LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_3022 = (*framePtr__system_3022).prev;
}
N_LIB_PRIVATE N_NIMCALL(NI16, getAttributes__pureZterminal_178)(NI h) {
	NI16 result;
	tyObject_CONSOLE_SCREEN_BUFFER_INFO__r6d5R6U7A9aP1xHUbo2o04A c;
	nimfr_("getAttributes", "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
{	result = (NI16)0;
	nimZeroMem((void*)(&c), sizeof(tyObject_CONSOLE_SCREEN_BUFFER_INFO__r6d5R6U7A9aP1xHUbo2o04A));
	nimln_(233, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	{
		NI32 T3_;
		T3_ = (NI32)0;
		T3_ = Dl_2432696396_(h, (&c));
		if (!!((T3_ == ((NI32) 0)))) goto LA4_;
		nimln_(234, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
		result = c.wAttributes;
		goto BeforeRet_;
	}
	LA4_: ;
	nimln_(235, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	result = ((NI16) 112);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, initTerminal__pureZterminal_182)(tyObject_PTerminalcolonObjectType___EcU8GhMNGo9bGDXbfqZ82og* term) {
	NI hStdoutTemp;
	NI hStderrTemp;
	nimfr_("initTerminal", "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	nimln_(238, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	hStdoutTemp = Dl_1392509091_(((NI32) -11));
	nimln_(239, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	{
		NI T3_;
		NI T4_;
		NI32 T5_;
		nimln_(240, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
		nimln_(239, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
		T3_ = (NI)0;
		T3_ = Dl_2432696395_();
		T4_ = (NI)0;
		T4_ = Dl_2432696395_();
		T5_ = (NI32)0;
		T5_ = Dl_2432696387_(T3_, hStdoutTemp, T4_, (&(*term).hStdout), ((NI32) 0), ((NI32) 1), ((NI32) 2));
		if (!(T5_ == ((NI32) 0))) goto LA6_;
	}
	LA6_: ;
	nimln_(243, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	hStderrTemp = Dl_1392509091_(((NI32) -12));
	nimln_(244, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	{
		NI T10_;
		NI T11_;
		NI32 T12_;
		nimln_(245, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
		nimln_(244, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
		T10_ = (NI)0;
		T10_ = Dl_2432696395_();
		T11_ = (NI)0;
		T11_ = Dl_2432696395_();
		T12_ = (NI32)0;
		T12_ = Dl_2432696387_(T10_, hStderrTemp, T11_, (&(*term).hStderr), ((NI32) 0), ((NI32) 1), ((NI32) 2));
		if (!(T12_ == ((NI32) 0))) goto LA13_;
	}
	LA13_: ;
	nimln_(248, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	(*term).oldStdoutAttr = getAttributes__pureZterminal_178((*term).hStdout);
	nimln_(249, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	(*term).oldStderrAttr = getAttributes__pureZterminal_178((*term).hStderr);
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(tyObject_PTerminalcolonObjectType___EcU8GhMNGo9bGDXbfqZ82og*, newTerminal__pureZterminal_16)(void) {
	tyObject_PTerminalcolonObjectType___EcU8GhMNGo9bGDXbfqZ82og* result;
	nimfr_("newTerminal", "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	result = NIM_NIL;
	nimln_(956, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	result = (tyObject_PTerminalcolonObjectType___EcU8GhMNGo9bGDXbfqZ82og*) newObj((&NTIpterminal__flNJLrANZti6Wiy5LTlGGA_), sizeof(tyObject_PTerminalcolonObjectType___EcU8GhMNGo9bGDXbfqZ82og));
	nimln_(958, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	initTerminal__pureZterminal_182(result);
	popFrame();
	return result;
}
static N_INLINE(NI, pluspercent___system_696)(NI x, NI y) {
	NI result;
	nimfr_("+%", "/home/yyoncho/Sources/nim/Nim/lib/system/arithmetics.nim");
	result = (NI)0;
	nimln_(403, "/home/yyoncho/Sources/nim/Nim/lib/system/arithmetics.nim");
	nimln_(407, "/home/yyoncho/Sources/nim/Nim/lib/system/arithmetics.nim");
	result = ((NI) ((NU)((NU64)(((NU) (x))) + (NU64)(((NU) (y))))));
	popFrame();
	return result;
}
static N_INLINE(void, incRef__system_5879)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("incRef", "/home/yyoncho/Sources/nim/Nim/lib/system/gc.nim");
	nimln_(231, "/home/yyoncho/Sources/nim/Nim/lib/system/gc.nim");
	(*c).refcount = pluspercent___system_696((*c).refcount, ((NI) 8));
	popFrame();
}
static N_INLINE(NI, minuspercent___system_716)(NI x, NI y) {
	NI result;
	nimfr_("-%", "/home/yyoncho/Sources/nim/Nim/lib/system/arithmetics.nim");
	result = (NI)0;
	nimln_(414, "/home/yyoncho/Sources/nim/Nim/lib/system/arithmetics.nim");
	nimln_(418, "/home/yyoncho/Sources/nim/Nim/lib/system/arithmetics.nim");
	result = ((NI) ((NU)((NU64)(((NU) (x))) - (NU64)(((NU) (y))))));
	popFrame();
	return result;
}
static N_INLINE(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell__system_5841)(void* usr) {
	tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* result;
	NI T1_;
	nimfr_("usrToCell", "/home/yyoncho/Sources/nim/Nim/lib/system/gc.nim");
	result = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(177, "/home/yyoncho/Sources/nim/Nim/lib/system/gc.nim");
	T1_ = (NI)0;
	T1_ = minuspercent___system_716(((NI) (ptrdiff_t) (usr)), ((NI) 16));
	result = ((tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*) (T1_));
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, ltpercent___system_1005)(NI x, NI y) {
	NIM_BOOL result;
	nimfr_("<%", "/home/yyoncho/Sources/nim/Nim/lib/system/comparisons.nim");
	result = (NIM_BOOL)0;
	nimln_(186, "/home/yyoncho/Sources/nim/Nim/lib/system/comparisons.nim");
	nimln_(188, "/home/yyoncho/Sources/nim/Nim/lib/system/comparisons.nim");
	result = ((NU64)(((NU) (x))) < (NU64)(((NU) (y))));
	popFrame();
	return result;
}
static N_INLINE(void, rtlAddZCT__system_5884)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "/home/yyoncho/Sources/nim/Nim/lib/system/gc.nim");
	nimln_(243, "/home/yyoncho/Sources/nim/Nim/lib/system/gc.nim");
	addZCT__system_5835((&gch__system_5774.zct), c);
	popFrame();
}
static N_INLINE(void, decRef__system_5886)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("decRef", "/home/yyoncho/Sources/nim/Nim/lib/system/gc.nim");
	nimln_(248, "/home/yyoncho/Sources/nim/Nim/lib/system/gc.nim");
	(*c).refcount = minuspercent___system_716((*c).refcount, ((NI) 8));
	nimln_(249, "/home/yyoncho/Sources/nim/Nim/lib/system/gc.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = ltpercent___system_1005((*c).refcount, ((NI) 8));
		if (!T3_) goto LA4_;
		nimln_(250, "/home/yyoncho/Sources/nim/Nim/lib/system/gc.nim");
		rtlAddZCT__system_5884(c);
	}
	LA4_: ;
	popFrame();
}
static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr_("asgnRef", "/home/yyoncho/Sources/nim/Nim/lib/system/gc.nim");
	nimln_(286, "/home/yyoncho/Sources/nim/Nim/lib/system/gc.nim");
	{
		tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell__system_5841(src);
		incRef__system_5879(T5_);
	}
	LA3_: ;
	nimln_(287, "/home/yyoncho/Sources/nim/Nim/lib/system/gc.nim");
	{
		tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell__system_5841((*dest));
		decRef__system_5886(T10_);
	}
	LA8_: ;
	nimln_(288, "/home/yyoncho/Sources/nim/Nim/lib/system/gc.nim");
	(*dest) = src;
	popFrame();
}
static N_INLINE(tyObject_PTerminalcolonObjectType___EcU8GhMNGo9bGDXbfqZ82og*, getTerminal__pureZterminal_26)(void) {
	tyObject_PTerminalcolonObjectType___EcU8GhMNGo9bGDXbfqZ82og* result;
	nimfr_("getTerminal", "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	result = NIM_NIL;
	nimln_(91, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	{
		if (!(gTerm__pureZterminal_15 == 0)) goto LA3_;
		nimln_(92, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
		asgnRef((void**) (&gTerm__pureZterminal_15), newTerminal__pureZterminal_16());
	}
	LA3_: ;
	nimln_(93, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	result = gTerm__pureZterminal_15;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, setForegroundColor__pureZterminal_486)(FILE* f, tyEnum_ForegroundColor__ez9ah4IgQc0AbdW68acioDg fg, NIM_BOOL bright) {
	NI h;
	tyObject_PTerminalcolonObjectType___EcU8GhMNGo9bGDXbfqZ82og* termX60gensym24_;
	NI16 old;
	NI16 T6_;
	nimfr_("setForegroundColor", "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	nimln_(629, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	nimln_(252, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	termX60gensym24_ = getTerminal__pureZterminal_26();
	nimln_(629, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	{
		nimln_(253, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
		if (!(f == stderr)) goto LA3_;
		h = (*termX60gensym24_).hStderr;
	}
	goto LA1_;
	LA3_: ;
	{
		h = (*termX60gensym24_).hStdout;
	}
	LA1_: ;
	nimln_(630, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	T6_ = (NI16)0;
	T6_ = getAttributes__pureZterminal_178(h);
	old = (NI16)(T6_ & ((NI16) -8));
	nimln_(631, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	{
		if (!(defaultForegroundColor__pureZterminal_484 == ((NI16) -1))) goto LA9_;
		nimln_(632, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
		defaultForegroundColor__pureZterminal_484 = old;
	}
	LA9_: ;
	nimln_(633, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	{
		if (!bright) goto LA13_;
		old = (NI16)(old | ((NI16) 8));
	}
	goto LA11_;
	LA13_: ;
	{
		nimln_(634, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
		old = (NI16)(old & ((NI16) -9));
	}
	LA11_: ;
	nimln_(646, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	{
		NI16 T20_;
		NI32 T21_;
		if (!(fg == ((tyEnum_ForegroundColor__ez9ah4IgQc0AbdW68acioDg) 39))) goto LA18_;
		nimln_(647, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
		T20_ = (NI16)0;
		T20_ = toU16__system_301(((NI) ((NI16)(old | defaultForegroundColor__pureZterminal_484))));
		T21_ = (NI32)0;
		T21_ = Dl_2432696469_(h, T20_);
		(void)(T21_);
	}
	goto LA16_;
	LA18_: ;
	{
		NI16 T23_;
		NI32 T24_;
		nimln_(649, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
		if (fg < 30 || fg > 39){ raiseIndexError3(fg, 30, 39); }
		T23_ = (NI16)0;
		T23_ = toU16__system_301((NI)(((NI) (old)) | lookup__pureZterminal_498[(fg)- 30]));
		T24_ = (NI32)0;
		T24_ = Dl_2432696469_(h, T23_);
		(void)(T24_);
	}
	LA16_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, setStyle__pureZterminal_422)(FILE* f, tySet_tyEnum_Style__NXKayqTLMsAibFwNceBlpA style) {
	NI h;
	tyObject_PTerminalcolonObjectType___EcU8GhMNGo9bGDXbfqZ82og* termX60gensym19_;
	NI16 old;
	NI16 T6_;
	NI16 a;
	NI32 T23_;
	nimfr_("setStyle", "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	nimln_(569, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	nimln_(252, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	termX60gensym19_ = getTerminal__pureZterminal_26();
	nimln_(569, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	{
		nimln_(253, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
		if (!(f == stderr)) goto LA3_;
		h = (*termX60gensym19_).hStderr;
	}
	goto LA1_;
	LA3_: ;
	{
		h = (*termX60gensym19_).hStdout;
	}
	LA1_: ;
	nimln_(570, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	T6_ = (NI16)0;
	T6_ = getAttributes__pureZterminal_178(h);
	old = (NI16)(T6_ & ((NI16) 119));
	nimln_(571, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	a = ((NI16) 0);
	nimln_(572, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	{
		if (!((style &((NU16)1<<((NU)((((tyEnum_Style__NXKayqTLMsAibFwNceBlpA) 1)- 1))&15U)))!=0)) goto LA9_;
		a = (NI16)(a | ((NI16) 8));
	}
	LA9_: ;
	nimln_(573, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	{
		if (!((style &((NU16)1<<((NU)((((tyEnum_Style__NXKayqTLMsAibFwNceBlpA) 5)- 1))&15U)))!=0)) goto LA13_;
		a = (NI16)(a | ((NI16) 128));
	}
	LA13_: ;
	nimln_(574, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	{
		if (!((style &((NU16)1<<((NU)((((tyEnum_Style__NXKayqTLMsAibFwNceBlpA) 7)- 1))&15U)))!=0)) goto LA17_;
		a = (NI16)(a | ((NI16) 16384));
	}
	LA17_: ;
	nimln_(575, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	{
		if (!((style &((NU16)1<<((NU)((((tyEnum_Style__NXKayqTLMsAibFwNceBlpA) 4)- 1))&15U)))!=0)) goto LA21_;
		a = (NI16)(a | ((NI16) -32768));
	}
	LA21_: ;
	nimln_(576, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	T23_ = (NI32)0;
	T23_ = Dl_2432696469_(h, (NI16)(old | a));
	(void)(T23_);
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, writeStyled__pureZterminal_451)(NimStringDesc* txt, tySet_tyEnum_Style__NXKayqTLMsAibFwNceBlpA style) {
	tyObject_PTerminalcolonObjectType___EcU8GhMNGo9bGDXbfqZ82og* term;
	NI16 old;
	NI32 T1_;
	nimfr_("writeStyled", "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	nimln_(584, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	term = getTerminal__pureZterminal_26();
	nimln_(585, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	old = getAttributes__pureZterminal_178((*term).hStdout);
	nimln_(586, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	setStyle__pureZterminal_422(stdout, style);
	nimln_(587, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	write__stdZsyncio_220(stdout, txt);
	nimln_(588, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	T1_ = (NI32)0;
	T1_ = Dl_2432696469_((*term).hStdout, old);
	(void)(T1_);
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, resetAttributes__pureZterminal_347)(FILE* f) {
	tyObject_PTerminalcolonObjectType___EcU8GhMNGo9bGDXbfqZ82og* term;
	nimfr_("resetAttributes", "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	nimln_(534, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	term = getTerminal__pureZterminal_26();
	nimln_(535, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	{
		NI32 T5_;
		if (!(f == stderr)) goto LA3_;
		nimln_(536, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
		T5_ = (NI32)0;
		T5_ = Dl_2432696469_((*term).hStderr, (*term).oldStderrAttr);
		(void)(T5_);
	}
	goto LA1_;
	LA3_: ;
	{
		NI32 T7_;
		nimln_(538, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
		T7_ = (NI32)0;
		T7_ = Dl_2432696469_((*term).hStdout, (*term).oldStdoutAttr);
		(void)(T7_);
	}
	LA1_: ;
	popFrame();
}
N_LIB_PRIVATE N_NOCONV(void, resetAttributes__pureZterminal_782)(void) {
	nimfr_("resetAttributes", "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	nimln_(899, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	resetAttributes__pureZterminal_347(stdout);
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isatty__pureZterminal_632)(FILE* f) {
	NIM_BOOL result;
	int T1_;
	int T2_;
	nimfr_("isatty", "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	result = (NIM_BOOL)0;
	nimln_(737, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	T1_ = (int)0;
	T1_ = getFileHandle__stdZsyncio_248(f);
	T2_ = (int)0;
	T2_ = _isatty(T1_);
	result = !((T2_ == ((NI32) 0)));
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ, getCursorPos__pureZterminal_158)(NI h) {
	tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ result;
	tyObject_CONSOLE_SCREEN_BUFFER_INFO__r6d5R6U7A9aP1xHUbo2o04A c;
	NI colontmp_;
	NI colontmp__2;
	nimfr_("getCursorPos", "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
{	nimZeroMem((void*)(&result), sizeof(tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ));
	nimZeroMem((void*)(&c), sizeof(tyObject_CONSOLE_SCREEN_BUFFER_INFO__r6d5R6U7A9aP1xHUbo2o04A));
	nimln_(219, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	{
		NI32 T3_;
		NI32 T6_;
		T3_ = (NI32)0;
		T3_ = Dl_2432696396_(h, (&c));
		if (!(T3_ == ((NI32) 0))) goto LA4_;
		nimln_(220, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
		T6_ = (NI32)0;
		T6_ = osLastError__pureZos_480();
		raiseOSError__pureZos_477(T6_, ((NimStringDesc*) NIM_NIL));
	}
	LA4_: ;
	nimln_(221, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	colontmp_ = ((NI) (c.dwCursorPosition.x));
	colontmp__2 = ((NI) (c.dwCursorPosition.y));
	result.Field0 = colontmp_;
	result.Field1 = colontmp__2;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, setCursorPos__pureZterminal_164)(NI h, NI x, NI y) {
	tyObject_COORD__38Oq1GgFPIYv2ksRi9c0fZA c;
	nimfr_("setCursorPos", "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	nimZeroMem((void*)(&c), sizeof(tyObject_COORD__38Oq1GgFPIYv2ksRi9c0fZA));
	nimln_(225, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	if ((x) < ((NI16) -32768) || (x) > ((NI16) 32767)){ raiseRangeErrorI(x, ((NI16) -32768), ((NI16) 32767)); }
	c.x = ((NI16) (x));
	nimln_(226, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	if ((y) < ((NI16) -32768) || (y) > ((NI16) 32767)){ raiseRangeErrorI(y, ((NI16) -32768), ((NI16) 32767)); }
	c.y = ((NI16) (y));
	nimln_(227, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	{
		NI32 T3_;
		NI32 T6_;
		T3_ = (NI32)0;
		T3_ = Dl_2432696454_(h, c);
		if (!(T3_ == ((NI32) 0))) goto LA4_;
		nimln_(228, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
		T6_ = (NI32)0;
		T6_ = osLastError__pureZos_480();
		raiseOSError__pureZos_477(T6_, ((NimStringDesc*) NIM_NIL));
	}
	LA4_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, cursorUp__pureZterminal_261)(FILE* f, NI count) {
	NI h;
	tyObject_PTerminalcolonObjectType___EcU8GhMNGo9bGDXbfqZ82og* termX60gensym9_;
	tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ p;
	NI TM__CN3raB9atujkEiPpxYAdlgQ_16;
	nimfr_("cursorUp", "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	nimln_(401, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	nimln_(252, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	termX60gensym9_ = getTerminal__pureZterminal_26();
	nimln_(401, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	{
		nimln_(253, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
		if (!(f == stderr)) goto LA3_;
		h = (*termX60gensym9_).hStderr;
	}
	goto LA1_;
	LA3_: ;
	{
		h = (*termX60gensym9_).hStdout;
	}
	LA1_: ;
	nimln_(402, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	p = getCursorPos__pureZterminal_158(h);
	nimln_(403, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	if (nimSubInt(p.Field1, count, &TM__CN3raB9atujkEiPpxYAdlgQ_16)) { raiseOverflow(); };
	p.Field1 = (NI)(TM__CN3raB9atujkEiPpxYAdlgQ_16);
	nimln_(404, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	setCursorPos__pureZterminal_164(h, p.Field0, p.Field1);
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, cursorForward__pureZterminal_291)(FILE* f, NI count) {
	NI h;
	tyObject_PTerminalcolonObjectType___EcU8GhMNGo9bGDXbfqZ82og* termX60gensym11_;
	tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ p;
	NI TM__CN3raB9atujkEiPpxYAdlgQ_19;
	nimfr_("cursorForward", "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	nimln_(427, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	nimln_(252, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	termX60gensym11_ = getTerminal__pureZterminal_26();
	nimln_(427, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	{
		nimln_(253, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
		if (!(f == stderr)) goto LA3_;
		h = (*termX60gensym11_).hStderr;
	}
	goto LA1_;
	LA3_: ;
	{
		h = (*termX60gensym11_).hStdout;
	}
	LA1_: ;
	nimln_(428, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	p = getCursorPos__pureZterminal_158(h);
	nimln_(429, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	if (nimAddInt(p.Field0, count, &TM__CN3raB9atujkEiPpxYAdlgQ_19)) { raiseOverflow(); };
	p.Field0 = (NI)(TM__CN3raB9atujkEiPpxYAdlgQ_19);
	nimln_(430, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	setCursorPos__pureZterminal_164(h, p.Field0, p.Field1);
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, setCursorVisibility__pureZterminal_193)(FILE* f, NIM_BOOL visible) {
	tyObject_CONSOLE_CURSOR_INFO__2bHqrjf9blMFjr48HNl45eA ccsi;
	NI h;
	tyObject_PTerminalcolonObjectType___EcU8GhMNGo9bGDXbfqZ82og* termX60gensym5_;
	nimfr_("setCursorVisibility", "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	nimZeroMem((void*)(&ccsi), sizeof(tyObject_CONSOLE_CURSOR_INFO__2bHqrjf9blMFjr48HNl45eA));
	nimln_(333, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	nimln_(252, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	termX60gensym5_ = getTerminal__pureZterminal_26();
	nimln_(333, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	{
		nimln_(253, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
		if (!(f == stderr)) goto LA3_;
		h = (*termX60gensym5_).hStderr;
	}
	goto LA1_;
	LA3_: ;
	{
		h = (*termX60gensym5_).hStdout;
	}
	LA1_: ;
	nimln_(334, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	{
		NI32 T8_;
		NI32 T11_;
		T8_ = (NI32)0;
		T8_ = Dl_2432696399_(h, (&ccsi));
		if (!(T8_ == ((NI32) 0))) goto LA9_;
		nimln_(335, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
		T11_ = (NI32)0;
		T11_ = osLastError__pureZos_480();
		raiseOSError__pureZos_477(T11_, ((NimStringDesc*) NIM_NIL));
	}
	LA9_: ;
	nimln_(336, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	{
		if (!visible) goto LA14_;
		ccsi.bVisible = ((NI32) 1);
	}
	goto LA12_;
	LA14_: ;
	{
		ccsi.bVisible = ((NI32) 0);
	}
	LA12_: ;
	nimln_(337, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	{
		NI32 T19_;
		NI32 T22_;
		T19_ = (NI32)0;
		T19_ = Dl_2432696402_(h, (&ccsi));
		if (!(T19_ == ((NI32) 0))) goto LA20_;
		nimln_(338, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
		T22_ = (NI32)0;
		T22_ = osLastError__pureZos_480();
		raiseOSError__pureZos_477(T22_, ((NimStringDesc*) NIM_NIL));
	}
	LA20_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, hideCursor__pureZterminal_222)(FILE* f) {
	nimfr_("hideCursor", "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	nimln_(343, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	setCursorVisibility__pureZterminal_193(f, NIM_FALSE);
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, cursorBackward__pureZterminal_306)(FILE* f, NI count) {
	NI h;
	tyObject_PTerminalcolonObjectType___EcU8GhMNGo9bGDXbfqZ82og* termX60gensym12_;
	tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ p;
	NI TM__CN3raB9atujkEiPpxYAdlgQ_24;
	nimfr_("cursorBackward", "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	nimln_(440, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	nimln_(252, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	termX60gensym12_ = getTerminal__pureZterminal_26();
	nimln_(440, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	{
		nimln_(253, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
		if (!(f == stderr)) goto LA3_;
		h = (*termX60gensym12_).hStderr;
	}
	goto LA1_;
	LA3_: ;
	{
		h = (*termX60gensym12_).hStdout;
	}
	LA1_: ;
	nimln_(441, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	p = getCursorPos__pureZterminal_158(h);
	nimln_(442, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	if (nimSubInt(p.Field0, count, &TM__CN3raB9atujkEiPpxYAdlgQ_24)) { raiseOverflow(); };
	p.Field0 = (NI)(TM__CN3raB9atujkEiPpxYAdlgQ_24);
	nimln_(443, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	setCursorPos__pureZterminal_164(h, p.Field0, p.Field1);
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, cursorDown__pureZterminal_276)(FILE* f, NI count) {
	NI h;
	tyObject_PTerminalcolonObjectType___EcU8GhMNGo9bGDXbfqZ82og* termX60gensym10_;
	tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ p;
	NI TM__CN3raB9atujkEiPpxYAdlgQ_25;
	nimfr_("cursorDown", "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	nimln_(414, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	nimln_(252, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	termX60gensym10_ = getTerminal__pureZterminal_26();
	nimln_(414, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	{
		nimln_(253, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
		if (!(f == stderr)) goto LA3_;
		h = (*termX60gensym10_).hStderr;
	}
	goto LA1_;
	LA3_: ;
	{
		h = (*termX60gensym10_).hStdout;
	}
	LA1_: ;
	nimln_(415, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	p = getCursorPos__pureZterminal_158(h);
	nimln_(416, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	if (nimAddInt(p.Field1, count, &TM__CN3raB9atujkEiPpxYAdlgQ_25)) { raiseOverflow(); };
	p.Field1 = (NI)(TM__CN3raB9atujkEiPpxYAdlgQ_25);
	nimln_(417, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	setCursorPos__pureZterminal_164(h, p.Field0, p.Field1);
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(NIM_CHAR, getch__pureZterminal_706)(void) {
	NIM_CHAR result;
	NI fd;
	tyObject_KEY_EVENT_RECORD__Ph22QYSbYUBAezvb9bd9cevA keyEvent;
	int numRead;
	nimfr_("getch", "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
{	result = (NIM_CHAR)0;
	nimln_(807, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	fd = Dl_1392509091_(((NI32) -10));
	nimln_(808, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	nimZeroMem((void*)(&keyEvent), sizeof(tyObject_KEY_EVENT_RECORD__Ph22QYSbYUBAezvb9bd9cevA));
	numRead = (int)0;
	{
		nimln_(810, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
		while (1) {
			{
				nimln_(812, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
				{
					NI32 T6_;
					T6_ = (NI32)0;
					T6_ = Dl_1392509082_(fd, ((NI32) -1));
					if (!!((T6_ == ((NI32) 0)))) goto LA7_;
					failedAssertImpl__stdZassertions_56(((NimStringDesc*) &TM__CN3raB9atujkEiPpxYAdlgQ_26));
				}
				LA7_: ;
				nimln_(813, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
				{
					int T11_;
					T11_ = (int)0;
					T11_ = Dl_1392509985_(fd, ((void*) ((&keyEvent))), ((int) 1), (&numRead));
					if (!!(!((T11_ == ((NI32) 0))))) goto LA12_;
					failedAssertImpl__stdZassertions_56(((NimStringDesc*) &TM__CN3raB9atujkEiPpxYAdlgQ_27));
				}
				LA12_: ;
				nimln_(814, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
				{
					NIM_BOOL T16_;
					NIM_BOOL T17_;
					T16_ = (NIM_BOOL)0;
					T17_ = (NIM_BOOL)0;
					T17_ = (numRead == ((NI32) 0));
					if (T17_) goto LA18_;
					T17_ = !((keyEvent.eventType == ((NI16) 1)));
					LA18_: ;
					T16_ = T17_;
					if (T16_) goto LA19_;
					T16_ = (keyEvent.bKeyDown == ((NI32) 0));
					LA19_: ;
					if (!T16_) goto LA20_;
					nimln_(815, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
					goto LA3;
				}
				LA20_: ;
				nimln_(816, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
				if ((keyEvent.uChar) < 0 || (keyEvent.uChar) > 255){ raiseRangeErrorU(keyEvent.uChar, 0, 255); }
				result = ((NIM_CHAR) (keyEvent.uChar));
				goto BeforeRet_;
			} LA3: ;
		}
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, showCursor__pureZterminal_224)(FILE* f) {
	nimfr_("showCursor", "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	nimln_(350, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	setCursorVisibility__pureZterminal_193(f, NIM_TRUE);
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, eraseLine__pureZterminal_321)(FILE* f) {
	NI h;
	tyObject_PTerminalcolonObjectType___EcU8GhMNGo9bGDXbfqZ82og* termX60gensym13_;
	tyObject_CONSOLE_SCREEN_BUFFER_INFO__r6d5R6U7A9aP1xHUbo2o04A scrbuf;
	NI32 numwrote;
	tyObject_COORD__38Oq1GgFPIYv2ksRi9c0fZA origin;
	NI32 wt;
	NI TM__CN3raB9atujkEiPpxYAdlgQ_28;
	nimfr_("eraseLine", "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	nimln_(484, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	nimln_(252, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	termX60gensym13_ = getTerminal__pureZterminal_26();
	nimln_(484, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	{
		nimln_(253, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
		if (!(f == stderr)) goto LA3_;
		h = (*termX60gensym13_).hStderr;
	}
	goto LA1_;
	LA3_: ;
	{
		h = (*termX60gensym13_).hStdout;
	}
	LA1_: ;
	nimZeroMem((void*)(&scrbuf), sizeof(tyObject_CONSOLE_SCREEN_BUFFER_INFO__r6d5R6U7A9aP1xHUbo2o04A));
	numwrote = (NI32)0;
	nimln_(487, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	{
		NI32 T8_;
		NI32 T11_;
		T8_ = (NI32)0;
		T8_ = Dl_2432696396_(h, (&scrbuf));
		if (!(T8_ == ((NI32) 0))) goto LA9_;
		nimln_(488, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
		T11_ = (NI32)0;
		T11_ = osLastError__pureZos_480();
		raiseOSError__pureZos_477(T11_, ((NimStringDesc*) NIM_NIL));
	}
	LA9_: ;
	nimln_(489, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	origin = scrbuf.dwCursorPosition;
	nimln_(490, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	origin.x = ((NI16) 0);
	nimln_(491, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	{
		NI32 T14_;
		NI32 T17_;
		T14_ = (NI32)0;
		T14_ = Dl_2432696454_(h, origin);
		if (!(T14_ == ((NI32) 0))) goto LA15_;
		nimln_(492, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
		T17_ = (NI32)0;
		T17_ = osLastError__pureZos_480();
		raiseOSError__pureZos_477(T17_, ((NimStringDesc*) NIM_NIL));
	}
	LA15_: ;
	nimln_(493, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	if (nimSubInt(scrbuf.dwSize.x, origin.x, &TM__CN3raB9atujkEiPpxYAdlgQ_28)) { raiseOverflow(); };
	if (TM__CN3raB9atujkEiPpxYAdlgQ_28 < -32768 || TM__CN3raB9atujkEiPpxYAdlgQ_28 > 32767){ raiseOverflow(); }
	wt = ((NI32) ((NI16)(TM__CN3raB9atujkEiPpxYAdlgQ_28)));
	nimln_(494, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	{
		NI32 T20_;
		NI32 T23_;
		nimln_(495, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
		nimln_(494, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
		T20_ = (NI32)0;
		T20_ = Dl_2432696457_(h, 32, wt, origin, (&numwrote));
		if (!(T20_ == ((NI32) 0))) goto LA21_;
		nimln_(496, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
		T23_ = (NI32)0;
		T23_ = osLastError__pureZos_480();
		raiseOSError__pureZos_477(T23_, ((NimStringDesc*) NIM_NIL));
	}
	LA21_: ;
	nimln_(497, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
	{
		NI32 T26_;
		NI32 T29_;
		nimln_(498, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
		nimln_(497, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
		T26_ = (NI32)0;
		T26_ = Dl_2432696463_(h, scrbuf.wAttributes, wt, scrbuf.dwCursorPosition, (&numwrote));
		if (!(T26_ == ((NI32) 0))) goto LA27_;
		nimln_(499, "/home/yyoncho/Sources/nim/Nim/lib/pure/terminal.nim");
		T29_ = (NI32)0;
		T29_ = osLastError__pureZos_480();
		raiseOSError__pureZos_477(T29_, ((NimStringDesc*) NIM_NIL));
	}
	LA27_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsNimatslibatspureatsterminaldotnim_Init000)(void) {
{
	TFrame FR_; FR_.len = 0;

	nimRegisterThreadLocalMarker(TM__CN3raB9atujkEiPpxYAdlgQ_3);

}/* preInitProc end */
{
}
}

N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsNimatslibatspureatsterminaldotnim_DatInit000)(void) {
static TNimNode* TM__CN3raB9atujkEiPpxYAdlgQ_2_7[7];
static TNimNode TM__CN3raB9atujkEiPpxYAdlgQ_0[8];
NTIpterminal58objecttype__EcU8GhMNGo9bGDXbfqZ82og_.size = sizeof(tyObject_PTerminalcolonObjectType___EcU8GhMNGo9bGDXbfqZ82og);
NTIpterminal58objecttype__EcU8GhMNGo9bGDXbfqZ82og_.align = NIM_ALIGNOF(tyObject_PTerminalcolonObjectType___EcU8GhMNGo9bGDXbfqZ82og);
NTIpterminal58objecttype__EcU8GhMNGo9bGDXbfqZ82og_.kind = 18;
NTIpterminal58objecttype__EcU8GhMNGo9bGDXbfqZ82og_.base = 0;
NTIpterminal58objecttype__EcU8GhMNGo9bGDXbfqZ82og_.flags = 1;
TM__CN3raB9atujkEiPpxYAdlgQ_2_7[0] = &TM__CN3raB9atujkEiPpxYAdlgQ_0[1];
TM__CN3raB9atujkEiPpxYAdlgQ_0[1].kind = 1;
TM__CN3raB9atujkEiPpxYAdlgQ_0[1].offset = offsetof(tyObject_PTerminalcolonObjectType___EcU8GhMNGo9bGDXbfqZ82og, trueColorIsSupported);
TM__CN3raB9atujkEiPpxYAdlgQ_0[1].typ = (&NTIbool__VaVACK0bpYmqIQ0mKcHfQQ_);
TM__CN3raB9atujkEiPpxYAdlgQ_0[1].name = "trueColorIsSupported";
TM__CN3raB9atujkEiPpxYAdlgQ_2_7[1] = &TM__CN3raB9atujkEiPpxYAdlgQ_0[2];
TM__CN3raB9atujkEiPpxYAdlgQ_0[2].kind = 1;
TM__CN3raB9atujkEiPpxYAdlgQ_0[2].offset = offsetof(tyObject_PTerminalcolonObjectType___EcU8GhMNGo9bGDXbfqZ82og, trueColorIsEnabled);
TM__CN3raB9atujkEiPpxYAdlgQ_0[2].typ = (&NTIbool__VaVACK0bpYmqIQ0mKcHfQQ_);
TM__CN3raB9atujkEiPpxYAdlgQ_0[2].name = "trueColorIsEnabled";
TM__CN3raB9atujkEiPpxYAdlgQ_2_7[2] = &TM__CN3raB9atujkEiPpxYAdlgQ_0[3];
TM__CN3raB9atujkEiPpxYAdlgQ_0[3].kind = 1;
TM__CN3raB9atujkEiPpxYAdlgQ_0[3].offset = offsetof(tyObject_PTerminalcolonObjectType___EcU8GhMNGo9bGDXbfqZ82og, fgSetColor);
TM__CN3raB9atujkEiPpxYAdlgQ_0[3].typ = (&NTIbool__VaVACK0bpYmqIQ0mKcHfQQ_);
TM__CN3raB9atujkEiPpxYAdlgQ_0[3].name = "fgSetColor";
TM__CN3raB9atujkEiPpxYAdlgQ_2_7[3] = &TM__CN3raB9atujkEiPpxYAdlgQ_0[4];
TM__CN3raB9atujkEiPpxYAdlgQ_0[4].kind = 1;
TM__CN3raB9atujkEiPpxYAdlgQ_0[4].offset = offsetof(tyObject_PTerminalcolonObjectType___EcU8GhMNGo9bGDXbfqZ82og, hStdout);
TM__CN3raB9atujkEiPpxYAdlgQ_0[4].typ = (&NTIint__rR5Bzr1D5krxoo1NcNyeMA_);
TM__CN3raB9atujkEiPpxYAdlgQ_0[4].name = "hStdout";
TM__CN3raB9atujkEiPpxYAdlgQ_2_7[4] = &TM__CN3raB9atujkEiPpxYAdlgQ_0[5];
TM__CN3raB9atujkEiPpxYAdlgQ_0[5].kind = 1;
TM__CN3raB9atujkEiPpxYAdlgQ_0[5].offset = offsetof(tyObject_PTerminalcolonObjectType___EcU8GhMNGo9bGDXbfqZ82og, hStderr);
TM__CN3raB9atujkEiPpxYAdlgQ_0[5].typ = (&NTIint__rR5Bzr1D5krxoo1NcNyeMA_);
TM__CN3raB9atujkEiPpxYAdlgQ_0[5].name = "hStderr";
TM__CN3raB9atujkEiPpxYAdlgQ_2_7[5] = &TM__CN3raB9atujkEiPpxYAdlgQ_0[6];
TM__CN3raB9atujkEiPpxYAdlgQ_0[6].kind = 1;
TM__CN3raB9atujkEiPpxYAdlgQ_0[6].offset = offsetof(tyObject_PTerminalcolonObjectType___EcU8GhMNGo9bGDXbfqZ82og, oldStdoutAttr);
TM__CN3raB9atujkEiPpxYAdlgQ_0[6].typ = (&NTIint4954__kDPg4wXyR8DDyA0MeEjIsw_);
TM__CN3raB9atujkEiPpxYAdlgQ_0[6].name = "oldStdoutAttr";
TM__CN3raB9atujkEiPpxYAdlgQ_2_7[6] = &TM__CN3raB9atujkEiPpxYAdlgQ_0[7];
TM__CN3raB9atujkEiPpxYAdlgQ_0[7].kind = 1;
TM__CN3raB9atujkEiPpxYAdlgQ_0[7].offset = offsetof(tyObject_PTerminalcolonObjectType___EcU8GhMNGo9bGDXbfqZ82og, oldStderrAttr);
TM__CN3raB9atujkEiPpxYAdlgQ_0[7].typ = (&NTIint4954__kDPg4wXyR8DDyA0MeEjIsw_);
TM__CN3raB9atujkEiPpxYAdlgQ_0[7].name = "oldStderrAttr";
TM__CN3raB9atujkEiPpxYAdlgQ_0[0].len = 7; TM__CN3raB9atujkEiPpxYAdlgQ_0[0].kind = 2; TM__CN3raB9atujkEiPpxYAdlgQ_0[0].sons = &TM__CN3raB9atujkEiPpxYAdlgQ_2_7[0];
NTIpterminal58objecttype__EcU8GhMNGo9bGDXbfqZ82og_.node = &TM__CN3raB9atujkEiPpxYAdlgQ_0[0];
NTIpterminal__flNJLrANZti6Wiy5LTlGGA_.size = sizeof(tyObject_PTerminalcolonObjectType___EcU8GhMNGo9bGDXbfqZ82og*);
NTIpterminal__flNJLrANZti6Wiy5LTlGGA_.align = NIM_ALIGNOF(tyObject_PTerminalcolonObjectType___EcU8GhMNGo9bGDXbfqZ82og*);
NTIpterminal__flNJLrANZti6Wiy5LTlGGA_.kind = 22;
NTIpterminal__flNJLrANZti6Wiy5LTlGGA_.base = (&NTIpterminal58objecttype__EcU8GhMNGo9bGDXbfqZ82og_);
NTIpterminal__flNJLrANZti6Wiy5LTlGGA_.marker = Marker_tyRef__flNJLrANZti6Wiy5LTlGGA;
if (!((TM__CN3raB9atujkEiPpxYAdlgQ_4 = nimLoadLibrary(((NimStringDesc*) &TM__CN3raB9atujkEiPpxYAdlgQ_6)))
)) nimLoadLibraryError(((NimStringDesc*) &TM__CN3raB9atujkEiPpxYAdlgQ_7));
	Dl_2432696387_ = (tyProc__oew1DfaGl5XhHmnBK0HYXQ) nimGetProcAddr(TM__CN3raB9atujkEiPpxYAdlgQ_4, "DuplicateHandle");
	Dl_2432696395_ = (tyProc__uryidYWkntM7ddjZSyxvyQ) nimGetProcAddr(TM__CN3raB9atujkEiPpxYAdlgQ_4, "GetCurrentProcess");
	Dl_2432696396_ = (tyProc__vjGHiWUJwFzOgSxDffBb6Q) nimGetProcAddr(TM__CN3raB9atujkEiPpxYAdlgQ_4, "GetConsoleScreenBufferInfo");
	Dl_2432696469_ = (tyProc__oPCjp4xTgEl9a8fqSzOv8lw) nimGetProcAddr(TM__CN3raB9atujkEiPpxYAdlgQ_4, "SetConsoleTextAttribute");
	Dl_2432696454_ = (tyProc__aqCTygSFeRmCMIAcNfrPcQ) nimGetProcAddr(TM__CN3raB9atujkEiPpxYAdlgQ_4, "SetConsoleCursorPosition");
	Dl_2432696399_ = (tyProc__Ag9bpoEvIZqYa8ny0e3IH9cw) nimGetProcAddr(TM__CN3raB9atujkEiPpxYAdlgQ_4, "GetConsoleCursorInfo");
	Dl_2432696402_ = (tyProc__Ag9bpoEvIZqYa8ny0e3IH9cw) nimGetProcAddr(TM__CN3raB9atujkEiPpxYAdlgQ_4, "SetConsoleCursorInfo");
	Dl_2432696457_ = (tyProc__U0n37n0G5WXtFwK5fJhDmg) nimGetProcAddr(TM__CN3raB9atujkEiPpxYAdlgQ_4, "FillConsoleOutputCharacterA");
	Dl_2432696463_ = (tyProc__pXMrjvyowjvaOKheIba8Fg) nimGetProcAddr(TM__CN3raB9atujkEiPpxYAdlgQ_4, "FillConsoleOutputAttribute");
}

